### ISSUE TITLE
wttr.in possibly down

### ISSUE THREAD

**Issue by ikubetoomuzik** [chubin/wttr.in#1016]
Hello,

I am getting timeout errors when trying to make requests to wttr.in. I've tried both v1 and v2 endpoints and even had friends try from other IP addresses and none were able to get a response.

Apologies if this is not the correct place to report the service is down.

Cheers,

**Comment by trekkie1701c** [comment]
If you go to the main site you get a response of "This query is already being processed"

The help page loads fine so I suspect something somewhere got stuck.

**Comment by nikolasdmtr** [comment]
It is the same for me. Curl also gets stuck and does not provide results.

**Comment by chubin** [comment]
It should work now, please check

**Comment by nikolasdmtr** [comment]
It is back to normal, thank you!

**Comment by ikubetoomuzik** [comment]
Also confirmed working again, thank-you for the quick response!
