### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by commet24** [chubin/wttr.in#1024]
Your website is down. Please get it back up

**Comment by DieterKoblenz** [comment]
It's not down. At least not at the moment, have you read the message? 

Sorry, we processed more than 1M requests today and we ran out of our datasource capacity.
We hope to solve the problem as soon as possible, so you can enjoy
your favourite weather service 24x365 even if it rains or snows.

**Comment by chubin** [comment]
At the time the ticket was created, the service was down, so everything was correct. I apologize that the service is still unavailable, but it will be back online at midnight tonight.

**Comment by markiatheus** [comment]
let's just keep making this issue every night we go past 1M requests 🤭

**Comment by commet24** [comment]
> let's just keep making this same issue every day we go past 1M requests 🤭

this time this error is harder to solve so my thread makes perfect sense

**Comment by chubin** [comment]
Please try again. It should work now

**Comment by markiatheus** [comment]
> Please try again. It should work now

anyway we can get https://www.weather.gov/documentation/services-web-api implemented into wttr.in?

**Comment by chubin** [comment]
@markiatheus Added the data source to #1025

**Comment by chubin** [comment]
The site is back online. I am closing the issue.

**Comment by AngryPhantom** [comment]
> The site is back online. I am closing the issue.

Sorry, we are running out of queries to the weather service at the moment.
Here is the weather report for the default city (just to show you what it looks like).
We will get new queries as soon as possible.

Again?
