### ISSUE TITLE
Using the `format=` parameter causes the curl to timeout

### ISSUE THREAD

**Issue by jeffdupont** [chubin/wttr.in#1045]
Example: `https://wttr.in/?format=3`
Response: `curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)`

**Comment by aclemens** [comment]
same here, without format is works just fine...

**Comment by chubin** [comment]
Fixed, please try again

**Comment by MacGurk** [comment]
Works again for me
