### ISSUE TITLE
No colors when using watch

### ISSUE THREAD

**Issue by FreeSlave** [chubin/wttr.in#110]
```
watch --color -n 43200 'curl -s wttr.in'
```

Output is not colorful.

**Comment by chubin** [comment]
That's a bug indeed. I should investigate it.

Fast (but not so perfect) workaround:

```
while true; do curl -s wttr.in; sleep 43200; clear; done
```

**Comment by chubin** [comment]
It seems to be a bug, but in watch, not in wttr.in.
In some cases additional option `--color` may help.

Some details here:

* https://stackoverflow.com/questions/13639475/
* https://stackoverflow.com/questions/3793126/

(please don't wonder, I think it is finally the time to go through the ancient issues)
