### ISSUE TITLE
Service appears broken

### ISSUE THREAD

**Issue by aesnyder** [chubin/wttr.in#114]
The service appears broken both in browser and curl:

[http://wttr.in/boulder](http://wttr.in/boulder)
```2017/05/22 22:34:50 invalid character '\x1f' looking for beginning of value 2017/05/22 22:34:50 Malformed response.```

```
curl wttr.in/~boulder
2017/05/22 22:31:36 invalid character '<' looking for beginning of value
2017/05/22 22:31:36 Malformed response.
```

**Comment by chubin** [comment]
I can't reprodruce it. Is it working now for you?

**Comment by aesnyder** [comment]
It is now, sorry about the alarm!
