### ISSUE TITLE
How to add wttr.in to  .conkyrc   so that conky can show the weather

### ISSUE THREAD

**Issue by wonderil** [chubin/wttr.in#118]
thanks

**Comment by chubin** [comment]
Try this:
```
${texeci 1800 curl -s wttr.in | sed -n '3,7{s/\d27\[[0-9;]*m//g;s/^..//;s/ *$//;p}'}
```

**Comment by mingyumu** [comment]
@chubin  thanks for you

**Comment by chubin** [comment]
@mingyumu Have you tried it? Does it work for you?

**Comment by mingyumu** [comment]
@chubin      no！ conky not work

**Comment by mingyumu** [comment]
@chubin I tried to modify the grammar to make it run as if it were not

**Comment by mingyumu** [comment]
@chubin  I really do not know how to add, and hope to free time to inform

**Comment by vitich** [comment]
Does not work in new conky:
conky: Syntax error (/home/vitich/.conky/conky_tr:2: unexpected symbol near '#') while reading config file. 
conky: Assuming it's in old syntax and attempting conversion.
conky: [string "..."]:150: [string "converted config"]:119: nesting of [[...]] is deprecated near '['

**Comment by tronje** [comment]
Works like a charm for me! Many thanks, @chubin 
It's too bad that conky can't handle the colors though...

**Comment by vitich** [comment]
Transparent variant with imagemagick  

```
${texeci 1800 curl wttr.in/kyiv_0pq_lang=uk.png | convert - -transparent black $HOME/.config/conky/out.png}
${image $HOME/.config/conky/out.png -p 0,0}
```

**Comment by EvgenyiRa** [comment]
Правильней
${texeci 1800 curl wttr.in/kyiv_0pq_lang=uk.png | convert - -transparent black $HOME/.config/conky/out.png}
${image $HOME/.config/conky/out.png -p 0,0 **-n**}

**Comment by chubin** [comment]
@EvgenyiRa Is `-n` critical here?

@EvgenyiRa @vitich Could you please share a couple of screenshots with conky + wttr.in?
I am going to add them to README.md

**Comment by vitich** [comment]
@chubin 
![Знімок екрану_2022-06-06_16-33-45](https://user-images.githubusercontent.com/12166319/172171489-bea0062d-d2ac-4298-a51d-56ab38dc7558.png)

**Comment by Foxap** [comment]
the ascii is all bugged for me

**Comment by vitich** [comment]
> the ascii is all bugged for me
![Screenshot from 2023-09-19 20-09-39](https://github.com/chubin/wttr.in/assets/12166319/1ae15d46-7484-44ea-9267-4403b62f4953)

**Comment by vitich** [comment]
${voffset 65}
${texeci 30 phantomjs $HOME/phantomjs/rasterize.js http://wttr.in/Kyiv /dev/stdout | convert - -crop 200x140+0+0 -transparent black /tmp/wttr.png}
${image /tmp/wttr.png -p}

![Screenshot_2024-09-06_06-29-14](https://github.com/user-attachments/assets/acd7ed0f-6d35-4d20-9336-85cfdc597736)

**Comment by Laucha** [comment]
This is my conky with a weather applet totally powered by wttr.in
![Image](https://github.com/user-attachments/assets/14034fa9-16d5-4e81-ae4f-147c892f811e)

Thank for the good work @chubin

**Comment by victorhck** [comment]
```
conky.text = [[
${texeci 1800 curl es.wttr.in/Madrid_0FQ_lang=es.png -so /tmp/img.png && magick /tmp/img.png -transparent black /tmp/transparent.png
}
${image /tmp/transparent.png -p 0,0 -n}
```

![Image](https://github.com/user-attachments/assets/c49b8dbb-2a2e-4e3b-bdc3-424f99c6e0a1)
