### ISSUE TITLE
How to set up no colors

### ISSUE THREAD

**Issue by thewaiter** [chubin/wttr.in#121]
For some reason I don't wanna colors in the weather output. Is there any setting for this?

**Comment by thewaiter** [comment]
Ah, OK. I Should read manual more precisely. Thx :)

**Comment by thewaiter** [comment]
https://www.enlightenment.org/ss/e-5931c16eb31cb9.88958334.jpg

**Comment by chubin** [comment]
Looks great. You should post it on unixporn (https://www.reddit.com/r/unixporn/). People will like it (and you will read many interesting comments about your setup). (aporpos: sk.wttr.in )

**Comment by thewaiter** [comment]
I know. But I wanted it in English for our Bodhi community. Thanx for your feedback...
