### ISSUE TITLE
Requests to wttr.in result in "504 Gateway Time-out"

### ISSUE THREAD

**Issue by stevensona** [chubin/wttr.in#124]

**Comment by legitosaurus** [comment]
Just noticed I was getting this too.

**Comment by blueyed** [comment]
http://downforeveryoneorjustme.com/wttr.in

**Comment by chubin** [comment]
@stevensona @legitosaurus @blueyed 
Thank you for reporting!
It should work now

Can you confirm it please?

**Comment by stevensona** [comment]
Great. Thank you!
