### ISSUE TITLE
Translate help

### ISSUE THREAD

**Issue by chubin** [chubin/wttr.in#125]
Translate help (wttr.in/:help) into other languages (take Russian as example).

**Comment by chubin** [comment]
Feature request came from here: https://www.opennet.ru/openforum/vsluhforumID3/110766.html#122

**Comment by daftaupe** [comment]
Hello I did the french translation of the help page in pr #128 

I saw that you wrote the french translation, so you can comment on things you don't like.

Regards,

**Comment by chubin** [comment]
Thank you very much! I've merged it + added you (if you don't mind) to the list of the translators.
Could you please translate error messages in lib/translations.py also?

**Comment by daftaupe** [comment]
@chubin : sure I appreciate being in the translators :)

Of course I can also translate error messages.

Actually there was one typo in one of the message concerning the weather itself, but I couldn't locate where it was. There's the word tonerre (thunder) but it should have 2 n, at least in one sentence I've seen. If you tell me where it is, maybe I can change it as well.

**Comment by chubin** [comment]
@daftaupe It is not that easy :) The problem is that some translations (weather conditions; tonerre in this case) come not from us but from our datasources. We could patch them (we do it for many translations), but we need to know what has to be patched. So we have to nail it down, and after that add the patch.

**Comment by daftaupe** [comment]
That's what i deduced from not finding this word in the code actually. I understand that it's not easy.
You can find my translations in this new pr #129 

Regards,

**Comment by daftaupe** [comment]
@chubin is there something wrong with the last pr ?

**Comment by chubin** [comment]
I'm sorry, I've missed it. Now I've merged it and updated the code on the server:
Please check the updated the code.

(hhmmm, I see that there are some problems with the message at the bottom: curl fr.wttr.in).
I'll check it tomorrow.

Thank you very much for your help!

**Comment by daftaupe** [comment]
No worries, I just asked so I can move forward to other things :)
Yes I see these weirds characters being displayed :/ Is this some encoding issue in the commit ?

**Comment by lgeurts** [comment]
Can help translate in Dutch if needed.

**Comment by chubin** [comment]
@lgeurts Luk, it would be really great.

Ik kan een beetje Nederlands spreken, maar een moedertaalspreker is nodig :)

Just fork it and add help-nl.txt

**Comment by chubin** [comment]
Implemented
