### ISSUE TITLE
Failing on install

### ISSUE THREAD

**Issue by MAGICCC** [chubin/wttr.in#126]
Hi, 
So I tried following the readme, but after starting the srv.py it 'updates' the .wegorc file and then giving me an error about depracted settings so it doesn't accept cities but longitudes/latitudes

**Comment by MatejMecka** [comment]
a log of the error messages is going to be nice :)

**Comment by chubin** [comment]
@MAGICCC Why have you closed it? It is not possible to install it still (at least if you to have it fully-functional; it should say, it is still a bug (of course, you don't need to install wttr.in to use it, but if you have fancy to install it, you'll not succeed; not yet).

**Comment by MAGICCC** [comment]
I can try to install it later again if you want

**Comment by chubin** [comment]
Thank you very much @MAGICCC 
I have to fix it first. As soon as it is fixed, I will write you
