### ISSUE TITLE
The website is down

### ISSUE THREAD

**Issue by alexanderepstein** [chubin/wttr.in#133]
Navigating to wttr.in brings up a webpage that just says ERROR. This also translates to trying to curl wttr.in either leading to an ERROR or it prints out ```New feature: multilingual location names wttr.in/станция+Восток (in UTF-8) and location search wttr.in/~Kilimanjaro (just add ~ before) 
Follow @igor_chubin for wttr.in updates ``` but without the weather.

**Comment by chubin** [comment]
It should work now. Thank you for reporting!
