### ISSUE TITLE
Requesting non-HTML output

### ISSUE THREAD

**Issue by hilton** [chubin/wttr.in#138]
I figured out that if I want to get plain text instead of HTML output from a custom HTTP client, I can add this HTTP request header:

    User-Agent: curly

Suggestion: it would be better to be able to disable HTML output with the request header:

    Accept: text/plain

**Comment by chubin** [comment]
You are right, it's a good idea. At the moment you can just force curly to use `curl` as the `User-Agent` header

**Comment by chubin** [comment]
Now you can force ANSI output with the `A` option.
```
curl wttr.in/?A
```
does not matter what User-Agent you actually have:
```
curl -A firefox wttr.in/?A
```

(@hilton @adius @Reiiii @jkmartindale excuse me for the delay, guys, but on the other hand, you now know that the service still exists)
