### ISSUE TITLE
Show more than three days.

### ISSUE THREAD

**Issue by dwrz** [chubin/wttr.in#140]
Feature request: the ability to preview weather for up to a week/ten days.

Proposed implementations:

1. f/b: scroll fordward and back in dates (re-render for next set of dates).
2. A simple table without the ASCII art.

**Comment by chubin** [comment]
The problem is not with the rendering, but with the data. It's hard to find reliable data for more than 3 days (or it is really expensive)

**Comment by dwrz** [comment]
Ah, I see. Too bad!
