### ISSUE TITLE
Weather data delivered for (some?) IPs seems to be completely wrong, though location is detected correctly

### ISSUE THREAD

**Issue by CyberShadow** [chubin/wttr.in#146]
Here is the weather for my location from some weather websites:

![screen shot 2017-09-03 at 13 20 16](https://user-images.githubusercontent.com/160894/30003389-a3e00740-90ab-11e7-9f07-79ec2e9a7f08.png)
![screen shot 2017-09-03 at 13 19 13](https://user-images.githubusercontent.com/160894/30003391-af2baaaa-90ab-11e7-9bee-c0cd41f66ccf.png)
![screen shot 2017-09-03 at 13 21 18](https://user-images.githubusercontent.com/160894/30003392-b118714a-90ab-11e7-8627-ed0c15f5dcab.png)
![screen shot 2017-09-03 at 13 21 30](https://user-images.githubusercontent.com/160894/30003393-b30b0486-90ab-11e7-91d7-d6f8c30fca29.png)
![screen shot 2017-09-03 at 13 21 43](https://user-images.githubusercontent.com/160894/30003394-b4c62e5e-90ab-11e7-8362-eae679a49988.png)

And here is what wttr.in says:

![z13 22 15-upload](https://user-images.githubusercontent.com/160894/30003397-bdf0d1a0-90ab-11e7-8b3f-6a865bad7b78.png)

How can there be such an incredible difference in temperatures? A difference of 20°C is not some rounding or caching error, especially when it's even below the forecasted night temperature - in the afternoon.

**Comment by chubin** [comment]
Strange indeed. The report may be sometimes wrong, but not that wrong

Now I get 32 ⁰C for your location:

http://wttr.in/Chi%C8%99in%C4%83u

The data seems to be pretty accurate.
Is it possible that in your case you've checked weather data for someother location? (probably not)
What have you seen in the location line under the report?

In my case it is 
`Emplacement: Chișinău, Municipiul Chișinău, Moldova [47.0122737,28.8605936]`

**Comment by CyberShadow** [comment]
> http://wttr.in/Chi%C8%99in%C4%83u

Hmm, that seems to be a different "location" as far as wttr.in is concerned.

The lookup by IP still gives the incorrect data:

http://wttr.in/89.28.117.1

**Comment by chubin** [comment]
Hmmmmm. It seems to be a bug. What is really strange, that if I use the location detected for this IP directly (http://wttr.in/chi%C5%9Fin%C4%83u,+MD) everything works just fine. It's a bug indeed

**Comment by chubin** [comment]
I suppose I know what is the reason for that

**Comment by chubin** [comment]
@CyberShadow Vladimir, I have fixed it. Please test

**Comment by CyberShadow** [comment]
Works for me, thank you!

**Comment by CyberShadow** [comment]
Google says -4°C and wttr.in says -14--7. Both seem "about right". Will keep an eye for major discrepancies.

**Comment by chubin** [comment]
The data sources deliver sometimes wrong data for some location. We should add new ones.
