### ISSUE TITLE
Google Chrome fail

### ISSUE THREAD

**Issue by drcrazyde** [chubin/wttr.in#148]
Hi, i experiment a bit with it.
And i think i find a problem.

http://wttr.in/ashausen_0tqp_transparency=255_lang=de.png

Brings me an big different color box to the background. But only in google chrome (Different systems)

**Comment by chubin** [comment]
I think that the problem is already fixed now. Please comment/reopen if it is not
(if you are still using wttr.in; and please excuse me for the late reply).
