### ISSUE TITLE
curl witt.in not working

### ISSUE THREAD

**Issue by wildbi111** [chubin/wttr.in#149]
Navigating to wttr.in brings up a webpage that just says ERROR. This also translates to trying to curl wttr.in either leading to an ERROR or it prints out New feature: multilingual location names wttr.in/станция+Восток (in UTF-8) and location search wttr.in/~Kilimanjaro (just add ~ before) Follow @igor_chubin for wttr.in updates but without the weather.  Same thing happened back in July.

**Comment by chubin** [comment]
Fixed! Thank you for reporting
