### ISSUE TITLE
Add a flag to force ANSI output (or html)

### ISSUE THREAD

**Issue by MightyPork** [chubin/wttr.in#153]
So, I've been trying to fetch this with my terminal (you've seen it earlier with the 80x24 problem ;)

I've actually added escape sequences to perform HTTP requests, but it kept failing with "response too big".
So I analyzed that a bit, tried some data dumping, and discovered it was receiving HTML (with the kilometer long CSS block).

This was solved after I added `like curl` to my User-Agent. (Now I see why the browser's user agent string is always so messy).

So the idea is to add a flag that will force ANSI (or HTML) output, regardless of user agent.
(I might try to make a PR for this later, but it's quite possible I'll forget, as it's now solved with this work-around)

for curiosity, here's my current headers block:
```
GET / HTTP/1.1 
Host: 192.168.0.10:80 
Connection: close 
User-Agent: ESPTerm 2.1.0 "Anthill" like curl wget HTTPie 
Content-Type: text/plain; charset=utf-8 
Accept-Encoding: identity 
Accept-Charset: utf-8 
Accept: text/*, application/json 
Cache-Control: no-cache,private,max-age=0 
```

**Comment by chubin** [comment]
@MightyPork Ondřej, you already forgot probably, that such service, wttr.in, exists.
Your feature request is implemented now. (and sorry for the delay)

We have a new option now to force ANSI, `-A`:
```
curl wttr.in/?A
```
It does not matter, what User-Agent you have, you will get ANSI:
```
curl -A firefox wttr.in/?A
```
