### ISSUE TITLE
Malformed response

### ISSUE THREAD

**Issue by matthias-vogt** [chubin/wttr.in#155]
Right now, there's an error at http://wttr.in/berlin-kreuzberg?lang=de
```
2017/10/05 21:48:46 invalid character '<' looking for beginning of value
2017/10/05 21:48:46 Malformed response.
```
The english report works. If you use a `+` instead of a `-`, it works too.

**Comment by chubin** [comment]
There were probably some problems on the data sources side. Does it work for you now?

**Comment by matthias-vogt** [comment]
Yup works
