### ISSUE TITLE
Self-signed SSL certificate on https://wttr.in

### ISSUE THREAD

**Issue by mrshu** [chubin/wttr.in#16]
While one of the features of [wego](https://github.com/schachmat/wego) is SSL, https://wttr.in is serving a self-signed certificate.

In the post Let's Encrypt worlds I do not really see why a self-signed certificate would be necessary.

If I can be of any help with regards to this, please do let me know.

**Comment by chubin** [comment]
In this case it has nothing common with wego, wego is used for rendering only, and in this case it does not matter completely, if wego supports SSL or not. Regarding your question, I agree with you completely, and I'm sure, that we have no reasons why we should use self-signed certificates in wttr.in.
We have discussed it here: https://twitter.com/igor_chubin/status/701843685021978625 and I will fix it soon.

**Comment by FernandoMiguel** [comment]
if I can help in anyway, ping me.
I would recommend taking a look at either acme.sh (a lets encrypt client) or CloudFlare origin certs.

**Comment by chubin** [comment]
@FernandoMiguel Thank you very much! I will try do it, and if I have any problems, I will write you

**Comment by tommey** [comment]
Started to use the service in Mattermost (by linking png URLs), complains for all joiners about the cert. Please make it happen. :)

**Comment by HacKanCuBa** [comment]
bump

**Comment by chubin** [comment]
Will be fixed soon (sorry that still didn't fix it)

**Comment by leon332157** [comment]
@chubin I believe that some command line browser doen't support https? Is it possible to use both http and https?

**Comment by chubin** [comment]
@leon332157 Yes, of course it is possible, not a problem at all

**Comment by leon332157** [comment]
@chubin Yesss! I never find a weather website that can use with Links ! 😎

**Comment by chubin** [comment]
@leon332157 Don't use it with lynx, use it with curl (lynx is supported though; and by the way if you still want to use a console browser user elinks, it supports colors; compare `lynx wttr.in` with `elinks wttr.in`, you will see the difference)

**Comment by leon332157** [comment]
@chubin Yes, I'm using mac and I used brew to install w3m, links, elinks. But curl is also good!

**Comment by leon332157** [comment]
@chubin That's the color difference.

**Comment by chubin** [comment]
@chubin curl is not just good, curl is better :)

**Comment by leon332157** [comment]
@chubin Yeah! :p

**Comment by leon332157** [comment]
@chubin And seems like elinks is not working on my mac :(

**Comment by leon332157** [comment]
![jpeg](https://user-images.githubusercontent.com/30728609/35534845-b8a20498-050f-11e8-8796-8bf031bb1e81.jpeg)

**Comment by leon332157** [comment]
@chubin Waiting for 3 mins :(

**Comment by chubin** [comment]
@leon332157 try it with other sites please

**Comment by leon332157** [comment]
@chubin Hmm... Google is not working as well 👎

**Comment by leon332157** [comment]
![jpeg](https://user-images.githubusercontent.com/30728609/35534965-15f93ac6-0510-11e8-912e-06e4225c35be.jpeg)

**Comment by chubin** [comment]
Me culpa.
Will be fixed on this weekend

**Comment by chubin** [comment]
```
$ curl https://wttr.in/
...
$ openssl s_client -showcerts -connect de.wttr.in:443 < /dev/null 2> /dev/null | grep issuer
issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
```

Finally fixed. Sorry guys for ignoring it so long
