### ISSUE TITLE
GeoIp incorrect for some IPs

### ISSUE THREAD

**Issue by drbayer** [chubin/wttr.in#162]
I have noticed that my IP address returns incorrect location. It appears to be pulling data for Antioch, CA but I'm in Nashville, TN (near Antioch, TN).  I checked ip2location, maxminddb and a legacy geoip db, and all return the correct location.  When I check using long/lat, it returns the correct location data.  Perhaps it is finding my IP in a local maxminddb that needs to be updated?

**Comment by merced317** [comment]
I too am having an issue with this.  I am in Rochester, NY and am receiving weather for Rochester, UK.

**Comment by chubin** [comment]
@drbayer @merced317 
The problem is fixed now (I hope). Please check if it works for you.
And thank you for reporting

**Comment by chubin** [comment]
Yes, this bug was introduced yesterday indeed. It is fixed now, please test. Thank you for reporting!

**Comment by merced317** [comment]
Looks great now.  Thanks for the continued awesome work!  Love this project. <3
