### ISSUE TITLE
Support GPS Coordinates

### ISSUE THREAD

**Issue by KthProg** [chubin/wttr.in#164]
If we're using the browser location or other geo-location  APIs, we will sometimes get only GPS latitude and longitude to work with. It would be really nice if this supported using those coordinates.

**Comment by chubin** [comment]
I'm not sure if it is that what you are looking for, but please try:

~~~~
curl wttr.in/-90,0
~~~~

and compare it with:

~~~~
curl wttr.in/~South+pole
~~~~

Here wttr.in/:help you can find all supported input formats.

**Comment by KthProg** [comment]
Aha. That sounds good. I didn't see any documentation that it supported that format. Thank you.

**Comment by LouBracken** [comment]
Hello! I cannot get GPS coordinates to work, I always get a 404 Unknown Location error. I've looked at https://wttr.in/:help and as far as I can tell this should work:

`curl wttr.in/45.512230,-122.685722?m`

However I get the 404 error. I have tried switching the lat and long, tried different locations, tried only 2 numbers after the decimal, but it is the same. Can you help me find out what I'm doing wrong?

Thank you!

**Comment by vitusson** [comment]
"tried only 2 numbers after the decimal, but it is the same."

If I try that with just two decimals, like in the help, it works 
curl wttr.in/45.51,-122.68?m gives no 404 error

**Comment by LouBracken** [comment]
> "tried only 2 numbers after the decimal, but it is the same."
> 
> If I try that with just two decimals, like in the help, it works curl wttr.in/45.51,-122.68?m gives no 404 error and "Location: 724, Southwest 3rd Avenue, University District, Downtown, Portland, Multnomah County, Oregon, 97201, USA [45.5100979,-122.6800103]"

Hm, perhaps only some coordinates work? Including two places after the decimal does work for the coordinates above, but another set of coordinates (48.83,-76.54) gives the 404 again:

![Screenshot from 2024-09-26 14-25-33](https://github.com/user-attachments/assets/d75e34bf-128f-477b-aa6e-29f2de16aa45)

**Comment by vitusson** [comment]
Can reproduce that 404 here too.
Google maps tells me that these coordinates are in the middle of some Canadian wilderness. Maybe just too fa away from a known station? 
But that's just a wild guess, I don't know how the database really works when it comes to coordinates

**Comment by LouBracken** [comment]
My bad! I assumed all coordinates would work (or return a closest estimate) and that I was just doing something wrong.

Thank you! I absolutely love this and I'm glad I found it.
