### ISSUE TITLE
your png command output , how to format ? how to beautify?

### ISSUE THREAD

**Issue by anlexN** [chubin/wttr.in#166]
![687474703a2f2f777474722e696e2f4d794c6f636174696f6e2e706e673f](https://user-images.githubusercontent.com/8686739/33485228-90d36c0c-d6e0-11e7-92c1-89555ee7cec5.png)

**Comment by chubin** [comment]
@anlexN: What do you mean? Could you give me a couple of examples?

**Comment by anlexN** [comment]
@chubin , my computer is win10 pro x64, 
i run command: 
#### curl wttr.in
but command output is not such beautiful like your png
![default](https://user-images.githubusercontent.com/8686739/33485889-09832366-d6e3-11e7-9206-af9cf4374f7d.PNG)
### how to beautify my output?

**Comment by chubin** [comment]
@anlexN ahh, now I see. Just do curl -ks

**Comment by chubin** [comment]
@anlexN: And you know, you can switch the language this way: curl -ks zh.wttr.in

**Comment by anlexN** [comment]
Thank you! @chubin 
but please allow me ask another question: **how to highlight my output?** 
i don't like pure white color
![default](https://user-images.githubusercontent.com/8686739/33515364-18e47b56-d79d-11e7-9ee7-e015f205ca9b.PNG)

**Comment by chubin** [comment]
@anlexN What exactly do you want to highlight? Give me some examples, please.

**Comment by anlexN** [comment]
![default](https://user-images.githubusercontent.com/8686739/33526895-876e4d14-d882-11e7-850b-748690537707.PNG)
@chubin , like this.
by the way, also can format other command output

**Comment by chubin** [comment]
@anlexN There are plenty of projects for this. For example https://github.com/jingweno/ccat

**Comment by anlexN** [comment]
@chubin , awesome! Thank you so much!
As i see, js-beautify for format , ccat for color, awesome!!!

**Comment by anlexN** [comment]
@chubin , my good teacher!
and now , please allow me ask another problem: how to solve messy code?

*Actual*
![default](https://user-images.githubusercontent.com/8686739/33543033-5d0aa3ea-d910-11e7-8fad-97ec6f1ce7b9.PNG)

*Except*
![1](https://user-images.githubusercontent.com/8686739/33543111-bb895c4a-d910-11e7-9204-29b3be62be03.PNG)

Because my computer is chinese, i have set encoding to utf-8.

**Comment by liyishuai** [comment]
> and now , please allow me ask another problem: how to solve messy code?

(Using Chinese might make communication more convenient here)
请详细描述您的问题。预期得到什么样的结果？实际与预期如何不一致？该问题是否与本项目有关？如果无关，请前往对应的项目提问。谢谢！
Please provide more details in your question. What's your expectation? How does the outcome differ from what you expect? Is your question related to this project? If not, please forward it to the corresponding project. Thanks!

**Comment by chubin** [comment]
@liyishuai Thank you very much for commenting this. I think that the issue can be closed actually, because the topic starter has disappeared. But what is much more interesting and important here, is that we should bring some order in the Chinese translations of wttr.in (#83).

I think that currently Chinese languages are ones of the worst supported languages by cheat.sh, and I find it not so good, because China is one of the major users of wttr.in.

Could you please take a look at the current translation, and say what should be fixed there?
(let us continue our discussion in #83).
