### ISSUE TITLE
Malformed response.

### ISSUE THREAD

**Issue by rvolosatovs** [chubin/wttr.in#168]
This happened since couple of minutes ago.
```sh
rvolosatovs@neon ~ % curl wttr.in/Eindhoven
2017/12/12 13:23:49 invalid character '<' looking for beginning of value
2017/12/12 13:23:49 Malformed response.
```
_btw, many thanks for the amazing service!!!_

**Comment by fedya** [comment]
Same for Saint-P.
```
:> weather 
2017/12/12 13:31:39 invalid character '<' looking for beginning of value
2017/12/12 13:31:39 Malformed response.
```

**Comment by chubin** [comment]
Thank you very much for reporting!
Our data source is experiencing problems at the moment.
They are trying to fix it, but it will take some time. 

As soon as the service is running, I'll give a sign

**Comment by chubin** [comment]
The problem is fixed. Thank you very much for reporting once again
