### ISSUE TITLE
png rendering seems to ignore q(iet) and super Q(uiet)

### ISSUE THREAD

**Issue by jomat** [chubin/wttr.in#169]
http://wttr.in/abc.png?0Q makes no difference to http://wttr.in/abc.png?0

removing .png works as expected:
http://wttr.in/abc?0Q http://wttr.in/abc?0

**Comment by chubin** [comment]
Have you tried abc_0Q.png?

**Comment by chubin** [comment]
@jomat please specify your options in the filename after underscore:

wttr.in/abc_0Q.png

The ?0Q notation is used for the text or html queries and _0Q for PNG.
I close the ticket, but if the _-notation will not work for you please reopen it.
