### ISSUE TITLE
50.150.86.x reports as Discovery Bay, Jamaica.  Should be Discovery Bay, California.

### ISSUE THREAD

**Issue by inactivist** [chubin/wttr.in#17]
Hitting wttr.in from 50.150.86.x (Comcast) (Discovery Bay, Northern California) reports "Weather for City: Discovery Bay, Jamaica"

**Comment by sashimanu-san** [comment]
Uplink geolocation provider returns correct answer http://api.ip2location.com/?ip=50.150.86.123&key=demo&package=WS10

**Comment by sashimanu-san** [comment]
... however WTTR does not :/
http://wttr.in/@50.150.86.123

**Comment by chubin** [comment]
@inactivist Does it work now? The problem should be fixed now. Could you please check it?

@sashimanu-san Please check the link once again, it should work correctly now

**Comment by inactivist** [comment]
@chubin Everything seems to work fine here.  Thanks for checking.
