### ISSUE TITLE
/files/fonts/stylesheet.css referred to but doesn't exist

### ISSUE THREAD

**Issue by Artanicus** [chubin/wttr.in#171]
Example log line: 
```
[2017-12-14 15:38:34] "GET /files/fonts/stylesheet.css HTTP/1.1" 404 342 0.001029
```

ansi2html referenses this file:
https://github.com/chubin/wttr.in/blob/e21eb76854b3dbdd787f043f6071c3aaeffa57e0/share/ansi2html.sh#L107

But it's not present in the share/static/ structure and doesn't seem to get dynamically created. Some leftover that should be removed?

**Comment by chubin** [comment]
@Artanicus Thank you very much for reporting
