### ISSUE TITLE
Site Appears to be Down

### ISSUE THREAD

**Issue by shreeramsenthi** [chubin/wttr.in#172]
I'm getting a blank page with just the words ERROR, both by curl and browser. Seems to be the same for all of the locations I tried, and there didn't seem to be a current issue reporting it.

Doubt it's relevant but I'm on Ubuntu 16.04 and Chrome Version 63.0.3239.132 .

![screenshot from 2018-01-13 21-15-49](https://user-images.githubusercontent.com/30534925/34912150-825425fc-f8a7-11e7-927f-d4ec286c2bcb.png)

**Comment by chubin** [comment]
Thank you for reporting! The problem is fixed

**Comment by shreeramsenthi** [comment]
Looks good, thanks for the quick reply!
