### ISSUE TITLE
Site seems to be down

### ISSUE THREAD

**Issue by guidedlinux** [chubin/wttr.in#173]
When trying to visit the website or curling it, I only get "ERROR" or `New feature: multilingual location names wttr.in/станция+Восток (in UTF-8) and location search wttr.in/~Kilimanjaro (just add ~ before)
Follow @igor_chubin for wttr.in updates` as a response.

![bildschirmfoto vom 2018-01-21 10-27-22](https://user-images.githubusercontent.com/28490810/35192590-edff759c-fe95-11e7-9210-0f6579681eaf.png)

**Comment by chubin** [comment]
Thank you! Fixed
