### ISSUE TITLE
Paris weather does not work!

### ISSUE THREAD

**Issue by j75** [chubin/wttr.in#180]
http://wttr.in/paris shows the weather in Paris, Philippines ! (that won't be so bad if the temperature would really be 34°C)
The solution I found was to use the GPS coordinates - and now the weather is -1°C ! :-(

**Comment by chubin** [comment]
It's some strange bug, I'm sorry for that. I'll fix it soon. Please use ~Paris for the moment.
You can use even names like ~Bastille and so on

**Comment by kev946** [comment]
"Chicago" returns the weather for Chicago, Belize, too.

**Comment by chubin** [comment]
In such cases always use the ~ prefix: ~Chicago
And it will be resolved properly.
I've fixed the problem with Paris and Chicago, you can use them directly again.

The reason why it happens, is that if you don't specify ~ before the name, then we do not use our internal wttr.in location resolving algorithm, and pass the location name directly to our weather data sources, and if they (or one of them) are buggy, then they can resolve the location name wrong.

So, the problem with Chicago and Paris is fixed. If you find other locations like that, please report them here (or in new issues if you please).

**Comment by Barca88** [comment]
The same happens in Braga, Portugal but if we use ~Braga it works

**Comment by chubin** [comment]
It should work now. Please comment if it does not, I will reopen the issue.
