### ISSUE TITLE
Kyiv is not Russia !!!

### ISSUE THREAD

**Issue by vitich** [chubin/wttr.in#182]
![wttr](https://user-images.githubusercontent.com/12166319/36616550-d47cf66e-18ec-11e8-8549-39a6b7b5dd61.png)

What the ****?

wttr.in/kyiv
wttr.in/kiev

**Comment by chubin** [comment]
It's a bug in one of our datasources.
Please try: 

wttr.in/Київ
wttr.in/~Kiev
wttr.in/~Kyiv

to use our internal (wttr.in) location resolving mechanism.

**Comment by chubin** [comment]
I added a patch for the datasource information (using our internal "aliases" mechanism).
So you can try /Kiev and /Kyiv again, it should work.

Sorry once again for the fault; if you wish, you can contact the datasource directly and claim it.

**Comment by vitich** [comment]
Thanks a lot!

**Comment by vitich** [comment]
Really good service for conky :)

**Comment by vitich** [comment]
Sorry for **** :) I hope you will understand my emotions.

**Comment by chubin** [comment]
Yes of course,  and it is really interesting how could it happen. I've contacted the datasource, and they answered me, that they have now a new location "Kiev" that situated in Russia, Prinorsky Kray. Good to know that Russia has now its own Kiev in Primorsky Kray :)

By the way, you can use not only Kiev in the query, but also location names like Подол, Борщаговка, Троещина, Русановка etc. I'm not sure that these locations will have different weather reports (but at least they could).

**Comment by vitich** [comment]
Well... Ok... Kiev, Primorskiy kray...
But Kyiv is Ukrainian language!
We have to create own Moscow in Lviv district..



24 лют. 2018 00:06 "Igor Chubin" <notifications@github.com> пише:

**Comment by vitich** [comment]
There is no Kiev, Primorsky Kray - Kiyevka (a small village with a population of 704 people - russian wikipedia)
http://town-map.ru/kiev_59_425417_1334208.htm
And russian wiki:
https://ru.wikipedia.org/wiki/%D0%9A%D0%B8%D0%B5%D0%B2%D0%BA%D0%B0_(%D0%9F%D1%80%D0%B8%D0%BC%D0%BE%D1%80%D1%81%D0%BA%D0%B8%D0%B9_%D0%BA%D1%80%D0%B0%D0%B9)

**Comment by chubin** [comment]
https://www.worldweatheronline.com/kiev-weather/primorye/ru.aspx?wwo_r=srch

Just try to enter Kiev in the search string of this weather reporting service.
Anyway, thanks to you, wttr.in does not have this problem anymore.
