### ISSUE TITLE
Powershell issue

### ISSUE THREAD

**Issue by l0g-g0l** [chubin/wttr.in#183]
До вчерашнего вечера проблем в работе не было. Использовал команду (curl http://wttr.in/Нижний+Новгород?2MnQ'&'lang=ru -UserAgent "curl" ).Content. 12 марта приблизительно после 17:00 по Мск. начал выдавать следующее:
![wttr](https://user-images.githubusercontent.com/37325112/37328665-14e11a92-26ac-11e8-94c6-0de28bccbe96.png)

**Comment by chubin** [comment]
В принципе, мы ничего не меняли на нашей стороне, по крайней мере ничего, что касается powershell. Может ли быть такое, что вы провели какие-то обновления на вашей системе?
Есть ли у вас другая система с PowerShell под рукой?

**Comment by l0g-g0l** [comment]
Да, в первую на себя грешил, прошёлся по разным машинам с разными системам Win2012r2, Win2016, с разными внешними ip, результат одинаков, никаких обновлений не было. У Вас баг не воспроизводиться?

**Comment by chubin** [comment]
У меня нет ни одной Windows-машины сейчас под рукой, но мы что-нибудь придумаем

**Comment by l0g-g0l** [comment]
На Win10 проблема не воспроизводится, только на серверных

**Comment by chubin** [comment]
Возможно, так и было раньше? 
Вот это не помогает?
https://gist.github.com/chubin/22a239783c67456eb0de

**Comment by l0g-g0l** [comment]
![wttr2](https://user-images.githubusercontent.com/37325112/37400430-f6325b0c-2795-11e8-8118-cdb9bfbe6a69.png)
Понятия не имею как я поставил эту галочку, вопрос закрыт.

**Comment by chubin** [comment]
Очень хорошо, что разобрались и большое спасибо, что задокументировали
