### ISSUE TITLE
Giessen, Germany is recognized as Giessenburg, Netherlands

### ISSUE THREAD

**Issue by mhorniq** [chubin/wttr.in#191]
Giessen, Germany is recognized as Giessenburg, Netherlands

Reproduce by 
`curl wttr.in/giessen`

**Comment by chubin** [comment]
Fixed. Thank you for reporting!


Was man immer in solchen Fällen machen kann: `,De` oder `,Germany` hinzufügen:

```
$ curl wttr.in/Giessen,DE
$ curl wttr.in/Giessen,Germany
```

Allerdings ist es nicht sicher, dass es das richtige Giessen selbst in diesem Fall gefunden wird.
Um 100% sicher zu sein, muss man noch `~` vor dem Namen schreiben:
```
curl wttr.in/~giessen,de
...
Location: Giessen, Ulm, Regierungsbezirk Tübingen, Baden-Württemberg, 89231, Deutschland [48.3614687,9.9952337]
```
