### ISSUE TITLE
Could I base a weather applet on wttr?

### ISSUE THREAD

**Issue by Jacob-Vlijm** [chubin/wttr.in#193]
Great project!

Just playing with the idea to create an applet, based on this `wttr` command, showing the current weather on the desktop. The info can be easily retrieved from the output, and used to convert the representation on the desktop.

![screenshot from 2018-05-09 13 05 42](https://user-images.githubusercontent.com/8932980/39811647-b988d9fe-5389-11e8-816d-f385c49f0722.png)

However: this would possibly lead to a substantial increase of data usage on your behalf. 

That brings me to the question if you expect the (your) service to be available in future, and more importantly: would the creation of an applet be a problem in relation to your license to the weather API?

**Comment by chubin** [comment]
Could you please write me on my email? igor@chub.in

**Comment by Jacob-Vlijm** [comment]
....Great, I just did.
