### ISSUE TITLE
What download format andf font can I use to use to display correctly?

### ISSUE THREAD

**Issue by cheapy** [chubin/wttr.in#196]
I am running linux.  I like your idea a lot and would like to download it periodically with cron and then feed the file to my screensaver as it cycles.  I am downloading it with curl.  I don't need colors, but it would look great if I could get the boxes to line up.  The download command I am using is:

curl -s wttr.in/?T?n > file.txt

I am then feeding file.txt to my xscreensaver starwars screensaver text crawl in a list of text files.  When I use the standard font, I get the linedraw characters, but the boxes don't line up.  When I try different fonts most don't get the linedraw characters, and none get the characters and have boxes that line up.

Could you please suggest a download string and font combination that will appear correctly?

Thanks

if you have this font installed and add this to the starwars screensaver settings it will work.  this info might be useful for other programs as well.  It needs to be a fixed width UTF-8 font that includes the linedraw characters being used. 
-font -*-dejavusansmono-medium-r-*-*-*-*-*-*-*-*-iso10646-*

**Comment by chubin** [comment]
Have you solved the problem, @cheapy?

First of all, combine the options together. It will not solve your problem though, but it will be better anyway:

```
curl -s wttr.in/?Tn > file.txt
```

Have you considered using the PNG output?
Will it solve your problem? (probably not)
Or have you solved the problem already?

**Comment by cheapy** [comment]
Igor, I got it working in English at least.  Here is a crudely made video of the screen saver running with the weather screen coming up after about 20 seconds.  The key to making it work was to get the right font being used. 


https://youtu.be/QcBnhVR-yls

**Comment by chubin** [comment]
It's crazy :) Thank you very much for sharing it!

**Comment by cheapy** [comment]
I thought it through and my cron idea is no good because it would run all the time.  I also think it will hit the website too often if I have it get a fresh file on each cycle, so I am thinking of checking the file on each cycle to see if its more than xxx minutes old (thinking to default to 15 minutes), and just display the existing file from the previous check instead until the file is over xxx minutes old.

**Comment by cheapy** [comment]
There is a thread about it on AntiX forum at:

https://www.antixforum.com/forums/topic/making-productive-use-of-the-xscreensaver-to-display-text-instead-of-conky/

Here is a zipfile of the code to run it. 
[bobs_xscreensaver_text_driver.20180514.zip](https://github.com/chubin/wttr.in/files/1999478/bobs_xscreensaver_text_driver.20180514.zip)
