### ISSUE TITLE
wttr.in (website) unexpected error (worldweatheronline.com)

### ISSUE THREAD

**Issue by BlackLotus** [chubin/wttr.in#198]
Didn't read the source yet, but wttr.in/bochum in browser errors out with
> 2018/05/16 13:31:58 An unexpected error has occured. The error report has been sent to the developers. If you continue to receive this error message then please do send us an email at info@worldweatheronline.com with your API Key and request url. 

Failed with curl temporary as well, but works now (somehow) http://wttr.in/~bochum works as expected for some reason. http://wttr.in gives the same error as seen above.

**Comment by chubin** [comment]
@BlackLotus Thank you for reporting! Do you still have the error?

**Comment by BlackLotus** [comment]
Nope it's fixed (sorry for the delay)
