### ISSUE TITLE
Airport code for Brno does not work

### ISSUE THREAD

**Issue by AloisMahdal** [chubin/wttr.in#201]
Probably more airports won't work, but those I could remember (BTS
for Bratislava) suffer from Issue #195 and treat the abbreviation as
town name.

    curl wttr.in/brq
    ERROR: Unknown location: brq
    ---

    Weather report: Oymyakon, RussiaA
    ...

**Comment by chubin** [comment]
The problem is fixed. Please test

**Comment by AloisMahdal** [comment]
Nice, works!

    $ for loc in brq bts rdu grr; do curl -s wttr.in/$loc | grep Location | sed "s/^/$loc|/"; done
    brq|Location: Letiště Brno Tuřany,  904/1,  Jihovýchod,  62700,  Česko [49.1547016,16.691368]
    bts|Location: Letisko (Airport), Ivanská cesta, Bratislava, Bratislavský kraj, 83107, Slovensko [48.1708708,17.2004171]
    rdu|Location: John Brantley Boulevard, Brier Creek, Wake County, North Carolina, 27560, United States of America [35.8768458,-78.7885008]
    grr|Location: Airport Viewing Area, Cascade, Cascade Charter Township, Kent County, Michigan, United States of America [42.87590595,-85.5271788718]
    $

Thanks for the fix.
