### ISSUE TITLE
T parameter does not really switch off color codes

### ISSUE THREAD

**Issue by AloisMahdal** [chubin/wttr.in#202]
Adding `T` parameter removes colors from the ASCII-art, but not from the New Feature and Follow.. texts

    $ curl -s 'wttr.in/?1&n&q&T' | hd | tail
    00000540  ba 1b 5b 30 6d 20 28 69  6e 20 55 54 46 2d 38 29  |..[0m (in UTF-8)|
    00000550  20 61 6e 64 20 6c 6f 63  61 74 69 6f 6e 20 73 65  | and location se|
    00000560  61 72 63 68 20 1b 5b 39  32 6d 77 74 74 72 2e 69  |arch .[92mwttr.i|
    00000570  6e 2f 7e 4b 69 6c 69 6d  61 6e 6a 61 72 6f 1b 5b  |n/~Kilimanjaro.[|
    00000580  30 6d 20 28 6a 75 73 74  20 61 64 64 20 7e 20 62  |0m (just add ~ b|
    00000590  65 66 6f 72 65 29 0a 46  6f 6c 6c 6f 77 20 1b 5b  |efore).Follow .[|
    000005a0  34 36 6d 1b 5b 33 30 6d  40 69 67 6f 72 5f 63 68  |46m.[30m@igor_ch|
    000005b0  75 62 69 6e 1b 5b 30 6d  20 66 6f 72 20 77 74 74  |ubin.[0m for wtt|
    000005c0  72 2e 69 6e 20 75 70 64  61 74 65 73 0a           |r.in updates.|
    000005cd

This causes issues eg. if one wants to control color of the whole text.

**Comment by chubin** [comment]
The problem is fixed, thank you for reporting!
