### ISSUE TITLE
PNG format doesn't honor q or Q options.

### ISSUE THREAD

**Issue by merced317** [chubin/wttr.in#204]
Exactly what the subject says.  When outputting the PNG option, the q or Q options are not honored.

http://wttr.in/Paris.png?0q

vs.

http://wttr.in/Paris?0q

**Comment by chubin** [comment]
Actually, it does honor, but the options have to specified in some other way in this case:

http://wttr.in/Paris_0q.png

The idea is that the options are directly in the filename, so there is mapping between queries and filenames.

I am not sure, that it is reflected in the documentation though.

**Comment by merced317** [comment]
I believe this issue has been resolved and can be closed.
