### ISSUE TITLE
Traditional Chinese translation

### ISSUE THREAD

**Issue by r2qokk** [chubin/wttr.in#207]
I will work on translating https://github.com/chubin/wttr.in/blob/master/share/help.txt and https://github.com/chubin/wttr.in/blob/master/share/translations/en.txt into traditional Chinese whenever I am available.
Since there is already 'zh' for the simplified Chinese version(#83), we also need to choose another name for traditional Chinese translation.

**Comment by chubin** [comment]
I close this as a duplicate for #359, even though this one was created earlier, because
much work is already done within that issue
