### ISSUE TITLE
Fahrenheit?

### ISSUE THREAD

**Issue by JonShepChen** [chubin/wttr.in#21]
Is there any option to have all temps displayed in Fahrenheit, instead of Celsius? Or possibly added in the future?

**Comment by JonShepChen** [comment]
Ah, just saw the 'Imperial Units' post at the bottom of the issues list that addresses this.

**Comment by jabbett** [comment]
Still, it should be configurable from the URL. It's less a preference of the server and more a preference of the visitor.

**Comment by ppwwyyxx** [comment]
Now it looks like the default is Fahrenheit. Hope to see an option for Celsius.

**Comment by chubin** [comment]
Just use ?u or ?m to override the defaults. Didn't update the documentation, sorry (but I'll do it soon).
At the moment you can find more info here: https://twitter.com/igor_chubin
