### ISSUE TITLE
wttr.in is down right now

### ISSUE THREAD

**Issue by asteinba** [chubin/wttr.in#213]
It just says "ERROR".

**Comment by asteinba** [comment]
And now "New feature: multilingual location names wttr.in/станция+Восток (in UTF-8) and location search wttr.in/~Kilimanjaro (just add ~ before)
Follow @igor_chubin for wttr.in updates" regardless of my location requests (curl wttr.in/paris, curl wttr.in/berlin)

**Comment by chubin** [comment]
Fixed! Please test.
And thank you for reporting

**Comment by asteinba** [comment]
Wow, thanks for the quick fix! Works like a charm again.

Btw: Probs to you for this awesome service (also your cheat.sh).

Do you have a donation link?

**Comment by chubin** [comment]
@asteinba No, no donation link, but I am very happy if you use the services and you like them
