### ISSUE TITLE
Remove text below weather report

### ISSUE THREAD

**Issue by Pokerkoffer** [chubin/wttr.in#214]
Hi,
please remove the text below the weather output, it defeats the purpose of having a small screenshot:

![](https://wttr.in/Hamburg_nt1.png)

Thank you!

**Comment by chubin** [comment]
@haarp @AllanLRH @Nikorasu @Artanicus @valodiadeseynes @Pokerkoffer 

New option `F` switches the "Follow" line off:

```
$ curl wttr.in/Hamburg?1nF
```
![wttr.in/Hamburg?1nF](https://wttr.in/Hamburg_1nF.png)
