### ISSUE TITLE
Misaligned HTML and badly formed HTML

### ISSUE THREAD

**Issue by Nimja** [chubin/wttr.in#22]
Suggestion: Why not use custom tags for the color, easier to write and read.
`<c1b33> or <yellow>`
The stylesheet will become more readable too:
`yellow { color: yellow; }`

No further styling or tricks would be needed and you don't have to set fonts, you can simply wrap it all in a `<pre>` tag.

![wttr misalignment](https://cloud.githubusercontent.com/assets/1355233/13313054/7b9d31b6-db9b-11e5-8574-e868c8c2e93e.png)

**Comment by blesh** [comment]
I came to report this, and was going to PR, but (judging by my *very* quick skim of the code) it looks like an issue with a third party module "ANSI2HTML", rather than this particular project.

**Comment by blesh** [comment]
Actually, looking more into it, I _think_ the ANSI2HTML code is probably fine. It seems more like the misalignment might be coming from malformed HTML.

The W3C validator is showing quite a few errors: https://validator.w3.org/check?uri=http%3A%2F%2Fwttr.in&charset=%28detect+automatically%29&doctype=Inline&group=0

The ones I think are suspect are any error were a tag isn't being closed properly.

**Comment by blesh** [comment]
Getting down to the bottom of it.

** FORGET MY PREVIOUS TWO COMMENTS **

LOL

It seems to be that the unicode characters, such as "degree" and the arrow-type characters don't keep the monospaced widths, and therefor alter the alignment.

**Comment by blesh** [comment]
Switching the font to [GNU Unifont](http://unifoundry.com/unifont.html) solves the misalignment issues. You'll need to use a `@font-face` directive in CSS in order to do so, but the result looks much better:

![screen shot 2016-03-31 at 11 30 41 am](https://cloud.githubusercontent.com/assets/1540597/14186606/0e047f42-f734-11e5-81a0-11d03c91899e.png)

**Comment by blesh** [comment]
Looking at Unifont, it might be infeasible to use it as a web font. The TTF file is about 12MB. You can probably use a conversion tool that extracts out the characters you need, however.

Either way, the problem is definitely the font. Find the right monospaced web font and you'll solve the issue.

**Comment by Artanicus** [comment]
For OS X the fix was indeed using Menlo and for Linux the fix was using DejaVu Sans Mono font-family. Letting it fall back to monospace makes everything unpredictable with so many bad monospace fonts around. DejaVu Sans Mono also fixed the unicode misalignment issue for ChromeOS.

I've seen Consolas recommended for Windows but cannot confirm as I don't have Windows to test with.

**Comment by chubin** [comment]
It should work better in Mac OS X / iOS  (and probably Windows) now (see #68).
Please test and report, if there are still problems with these and other problems.
As far as I see, there are still problems with Android at least.

**Comment by Artanicus** [comment]
So, aftermath of #68 is that we have OS provided good monospace fonts for the following:
- Mac OS X & iOS: Menlo
- Linux & ChromeOS: DejaVu Sans Mono
- There's several contenders for the best Windows font.
- The biggest remaining issue is Android. Next step is to figure out what monospace fonts does vanilla Android ship with, and hopefully one of them is good.

**Comment by chubin** [comment]
![wttr.in in iOS](https://cloclo27.datacloudmail.ru/view/pics/1.png)

**Comment by chubin** [comment]
![wttr.in in iOS](https://cloud.githubusercontent.com/assets/3875145/22622025/0ad691ce-eb31-11e6-83f7-2ba6b83a2e57.png)

**Comment by chubin** [comment]
It looks really ugly in windows:

https://twitter.com/Noooooovik/status/832190050297376768

@Artanicus @blesh If you have any ideas what fonts could be tried on Windows please give your suggestions

**Comment by Nimja** [comment]
Hmm.. Apparently nobody cares anymore?

**Comment by chubin** [comment]
@Nimja Actually the users do care, but the problem is still there. Do you have any idea about the font?

**Comment by Nimja** [comment]
I'm closing this for now, ticket has been open for 3.5 years ;)
