### ISSUE TITLE
NL lang improvements

### ISSUE THREAD

**Issue by CupOfEspresso** [chubin/wttr.in#222]
I saw a few small error in the Dutch Lang but I can't seem to find them. I would love to fix them for you

**Comment by chubin** [comment]
@CupOfEspresso

Youri hi! We are translating the new view (`curl v2.wttr.in`).
Could you please take a look at it and the Dutch translation?
It is just a single line:

[lib/translations_v2.py](https://github.com/chubin/wttr.in/blob/master/lib/translations_v2.py)

**Comment by CupOfEspresso** [comment]
I saw the Dutch translation, it was alright correct.

**Comment by chubin** [comment]
@CupOfEspresso No, I mean the v2 view. 

The NL line is empty:

https://github.com/chubin/wttr.in/blob/master/lib/translations_v2.py#L48

**Comment by CupOfEspresso** [comment]
Oh, sorry. Didn't see it, I will look add it when I'm behind my computer

**Comment by chubin** [comment]
@CupOfEspresso Thank you!
