### ISSUE TITLE
`curl wttr.in` not working

### ISSUE THREAD

**Issue by aviaryan** [chubin/wttr.in#225]
It seems `wttr.in` stopped working just now. The [web page](http://wttr.in/Patna) also shows `ERROR` (not sure if that's by design). 

```
~/g/hapramp-backend-steem ❯❯❯ curl http://wttr.in                                                        

Follow @igor_chubin for wttr.in updates
~/g/hapramp-backend-steem ❯❯❯ curl http://wttr.in/Patna                                                         

Follow @igor_chubin for wttr.in updates
~/g/hapramp-backend-steem ❯❯❯ curl http://wttr.in/Singapore                                       
~/g/hapramp-backend-steem ❯❯❯       
```

**Comment by chubin** [comment]
Fixed. Thank you for reporting!

**Comment by aviaryan** [comment]
That was fast. ⚡️

**Comment by ClarkGuitar** [comment]
curl wttr.in not working==

**Comment by chubin** [comment]
Should be working already; please check

**Comment by BlabliGam** [comment]
I just tried the "curl wttr.in" command and it just keeps thinking, it doesn't work. It was working yesterday perfectly fine

**Comment by chubin** [comment]
@BlabliGam What exactly does not work? I've just checked it and it seems to work for me. What query are you issuing?

**Comment by BlabliGam** [comment]
Could be me then. None of the curl commands work. I've tried a few and they don't work, but these same commands worked yesterday

**Comment by hello-smile6** [comment]
> Could be me then. None of the curl commands work. I've tried a few and they don't work, but these same commands worked yesterday

What happens, exactly?

**Comment by chubin** [comment]
@BlabliGam Could you please show the commands and the output?

**Comment by BlabliGam** [comment]
I've tried this:
`curl wttr.in
curl -s wttr.in
curl wttr.in/London
curl wttr.in/Amsterdam`

All of them without response, they just keep fetching but never finish

**Comment by chubin** [comment]
This looks like your local problem, some sort of firewall maybe. It is hard to tell exactly what it was, but it was definitely problem on your side.

What you can do if it occurs again:

1. try to access `https://`
2. try to access other http services with curl (you can try terminal oriented, or just regular websites).
3. use `-v` and/or `-I` with curl, to get more debug info.

**Comment by Peggy-Bar** [comment]
Hi. wttr.in is not working

**Comment by egorsha** [comment]
doesn't work now!!

**Comment by wjohnhaynes** [comment]
My very reliable startup script did not work this morning. The problem is with a curl for the weather "curl wttr.in/"mycity".
Manually tried London, Chicago, New York. Nothing resolves. Tried ping and it could not resolve. I was able to curl google and ping the dns server.  Just curl wttr.in seems to be down.
