### ISSUE TITLE
PNG output failed

### ISSUE THREAD

**Issue by lzyun** [chubin/wttr.in#227]
hi,

I got stuck at exporting a png file. The screen.buffer type is defaultdict.
And below list is the environment module. 
Does someone meet the same problem?

> Traceback (most recent call last):
>   File "/Users/tzyunlai/Dropbox/CodeLz/git/wttr.in/lib/wttrin_png.py", line 319, in make_wttr_in_png
>     typescript_to_one_frame(cached_png_file, curl_output, options=parsed)
>   File "/Users/tzyunlai/Dropbox/CodeLz/git/wttr.in/lib/wttrin_png.py", line 201, in typescript_to_one_frame
>     gen_term(png_file, screen.buffer, options=options)
>   File "/Users/tzyunlai/Dropbox/CodeLz/git/wttr.in/lib/wttrin_png.py", line 120, in gen_term
>     buf = strip_buf(buf)
>   File "/Users/tzyunlai/Dropbox/CodeLz/git/wttr.in/lib/wttrin_png.py", line 93, in strip_buf
>     for line in buf[::-1]:
> TypeError: unhashable type

`astroid==1.6.5
backports.functools-lru-cache==1.5
certifi==2018.10.15
chardet==3.0.4
Click==7.0
configparser==3.5.0
cyrtranslit==0.4
dateutils==0.6.6
dnspython==1.15.0
enum34==1.1.6
Flask==1.0.2
futures==3.2.0
geographiclib==1.49
geoip2==2.9.0
geopy==1.17.0
gevent==1.3.7
greenlet==0.4.15
idna==2.7
ipaddress==1.0.22
isort==4.3.4
ItsDangerous==1.0.0
Jinja2==2.10
lazy-object-proxy==1.3.1
MarkupSafe==1.0
maxminddb==1.4.1
mccabe==0.6.1
Pillow==5.3.0
pylint==1.9.3
pyte==0.6.0
python-dateutil==2.7.3
pytz==2018.5
requests==2.20.0
singledispatch==3.4.0.3
six==1.11.0
urllib3==1.24
wcwidth==0.1.7
Werkzeug==0.14.1
wrapt==1.10.11`

**Comment by lzyun** [comment]
Find the problem. 
change the structure of screen.buf before gen_term()

`def typescript_to_one_frame(jpeg_file, text, options=None):
    """
    Render text (terminal sequence) in png_file
    """

    # fixing some broken characters because of bug #... in pyte 6.0
    text = text.replace('Н', 'H').replace('Ν', 'N')

    screen = pyte.screens.Screen(COLS, ROWS)
    #screen.define_charset("B", "(")

    stream = pyte.streams.ByteStream()
    stream.attach(screen)

    stream.feed(text)

    buf = []
    for line in screen.buffer.values():
        line_buf_list = []
        for char in line.values():
            line_buf_list.append(char)
        buf.append(line_buf_list)
    gen_term(jpeg_file, buf, options=options)
`

**Comment by chubin** [comment]
Hi!
Yes, your changes are (almost) correct. As you probably understood, the problem was with the new pyte API. I've added today a fix to the main tree.

https://github.com/chubin/wttr.in/commit/597785e43fc533d7f8c52ec9ff450126472fc351

Strictly speaking your fix is not correct, because the order of the values() is not guaranteed.
Please use the code from the main tree
