### ISSUE TITLE
png output returns a png with png written on it

### ISSUE THREAD

**Issue by yodamerlin** [chubin/wttr.in#230]
Here is a screenshot from the readme of it:

![image](https://user-images.githubusercontent.com/8143879/47616540-284f7880-dab6-11e8-9331-4a5f2d87f80b.png)

Here is the exact image any location I try produces:
![image](https://user-images.githubusercontent.com/8143879/47616548-43ba8380-dab6-11e8-92fa-c8f055d35c89.png)

This started yesterday, as far as I am aware.

**Comment by chubin** [comment]
Fixed! Thank you for reporting
