### ISSUE TITLE
_WWO_KEY_FILE seems to be mandatory, not documented and confusing

### ISSUE THREAD

**Issue by Artanicus** [chubin/wttr.in#238]
```
./lib/globals.py:_WWO_KEY_FILE = os.environ['HOME'] + '/.wwo.key'
```

There seems to be no way to override this and since we're providing this already in the wegorc I find it a bit confusing that it's even needed? In any case, the readme doesn't call out a need for it and there's no mechanism to override this location.

**Comment by chubin** [comment]
Added `WTTR_WWO_KEY_FILE` to override WWO location key.

> I find it a bit confusing that it's even needed?

It is needed, because wttr.in uses not only wego, but there are other modules beside it;
wego also does not contact the WWO API directly, but via a special caching proxy server,
and it is this server who uses the API key
