### ISSUE TITLE
Country code ignored when specifying location and PNG format.

### ISSUE THREAD

**Issue by tenerhades** [chubin/wttr.in#252]
I live near Newmarket, UK. The geolocation works fine, unless I want an image. wttr.in/.png puts me in Germany. But that's another issue.

This one is for noting that wttr.in/newmarket gives me info for Newmarket, Canada. wttr.in/newmarket_uk correctly gives me info Newmarket, UK. The problem is that wttr.in/newmarket_uk.png gives me results for Canada again, ignoring the country specifier part of the request.

**Comment by tenerhades** [comment]
Looks like parse_wttrin_png_name() in wttrin_png.py is splitting by underscores. As per the README.md, options are specified after the first underscore, not country codes. For PNG images, if I specify the location with some other character (eg. '-' or '+'), it works fine: wttr.in/newmarket-uk.png.

I can still specify options with underscore.

**Comment by chubin** [comment]
Exactly. You can also use `,` for that. Also, you can use enhanced location resolution method (specify `~` in front of the location name):
```
wget https://wttr.in/~newmarket,uk.png
```
In this case, you will get exact location information in the footer (below the forecast).
