### ISSUE TITLE
[Question] For cmd

### ISSUE THREAD

**Issue by tilkinsc** [chubin/wttr.in#256]
It doesn't seem like this is supported on CMD

Is there a way to get it without the coloration?

I can `chcp 65001` to get utf8 for all the characters used, but the coloration garbles the data afterwards.

Look how cute it looks
![image](https://user-images.githubusercontent.com/7494772/50899601-954d8b80-13e0-11e9-82e6-cbca24ba2097.png)

**Comment by tilkinsc** [comment]
Ahh okay ?T works
![image](https://user-images.githubusercontent.com/7494772/50899735-ff663080-13e0-11e9-8cdb-86485a43d558.png)

So this is supported on window 💃

**Comment by chubin** [comment]
@tilkinsc Actually, it depends on the curl version.
In the recent versions of curl it works even without `T`:

See this:

https://github.com/curl/curl/issues/3008

**Comment by tilkinsc** [comment]
Hmm I must have a dated curl version. It will have to do.
