### ISSUE TITLE
How to set up no colors in the wttr.in output

### ISSUE THREAD

**Issue by brlndtech** [chubin/wttr.in#263]
Hey, I want to know if it's possible to execute wttr.in/town withtout the colours at the output, because I would like to the send the result to my private email. (and the colour is not supported) 

thank's 

have a good day

Ex:  
 [38;5;226m    \   /    [0m Clear
 [38;5;226m     .-.     [0m [38;5;050m1[0m-[38;5;048m4[0m °C[0m         
 [38;5;226m  ― (   ) ―  [0m [1m↖[0m [38;5;226m13[0m km/h[0m      
 [38;5;226m     `-’     [0m 10 km[0m          
 [38;5;226m    /   \    [0m 0.0 mm[0m

**Comment by chubin** [comment]
Sure you can, just use the `T` option:

curl wttr.in/Nuremberg?T

The list of options:

curl wttr.in/:help

**Comment by brlndtech** [comment]
omg thank you <3 
have a good day man
