### ISSUE TITLE
Weather for St. Petersburg, Russia use incorrect place

### ISSUE THREAD

**Issue by devbis** [chubin/wttr.in#264]
Hi!
I found a problem with an incorrect passing location somewhere in the code. When I use the default format, it detects the correct location (City + Country), but the weather is wrong.

```$ curl wttr.in/?0```
```
Weather report: St Petersburg, Russia

    \  /       Partly cloudy
  _ /"".-.     12-13 °C
    \_(   ).   ↙ 19 km/h
    /(___(__)  16 km
               0.0 mm
```

Checking the same request with the custom format, we can find the reason: the returning location is the coordinates for Saint Petersburg, Florida, United States

```$ curl wttr.in/?format=4```
```
27.7703796,-82.6695085: ⛅️ 🌡️+13⁰C 🌬️↙19 km/h
```

But when I provide the city explicitly, the weather is correct.

```$ curl wttr.in/Saint-Petersburg?format=4```
```
Saint-Petersburg: ☁️ 🌡️-2⁰C 🌬️←19 km/h
```

I suppose wttr.in use city without country somewhere and that is the cause for the incorrect location

**Comment by chubin** [comment]
@devbis Ivan, thank you very much for reporting this. Could you provide your IP address (you can drop the last octet, like here: 1.2.3.XX), I will check what is wrong with the geolocation service.

**Comment by devbis** [comment]
Sure, it is 146.120.57.XX

**Comment by devbis** [comment]
Thanks a lot, now I can see the correct weather values and the coordinates for my location are correct too!

**Comment by chubin** [comment]
I think we've just fixed a nasty bug, that was annoying many people :+1: Thank you for reporting it once again!
