### ISSUE TITLE
png size

### ISSUE THREAD

**Issue by arnauldb** [chubin/wttr.in#269]
Hello,

is it possible to change the png size? I would like to add it to an image but the png file is a little too small.

**Comment by chubin** [comment]
@arnauldb you can always use `convert` for that:
```
convert -resize 1280x orig.png big.png
```
Or did you want something else?

**Comment by arnauldb** [comment]
I run this:
`convert viewcam.jpg <( curl wttr.in/st-cloud+france_transparency=150_q0_lang=fr.png ) -geometry +10+40 -composite target.jpg`
and obtain this: 
![target](https://user-images.githubusercontent.com/13196747/52535383-1ab0bc80-2d4e-11e9-89e6-126f8d2f7c57.jpg)
But I wish to have the resulting insert (showed by the pink arrow) bigger.

**Comment by chubin** [comment]
`convert viewcam.jpg \( <( curl wttr.in/St-cloud,France_transparency=150_q0_lang=fr.png ) -resize 600x \) -geometry +10+40 -composite target.jpg`

Voilà!

**Comment by arnauldb** [comment]
Thanks a lot! I already use wttr.in on a daily basis to check the weather, a great tool.

**Comment by chubin** [comment]
@arnauldb Thank you very much! If you need some feature, just ping me. And stay tuned, the project is being developed, we are adding new features all the time

**Comment by NightMachinary** [comment]
It loses quality though.
