### ISSUE TITLE
Estonian translation

### ISSUE THREAD

**Issue by janesmae** [chubin/wttr.in#275]
Hi, there is missing Estonian translation for the project. I would like to help. Should I just fork the project and create a pull request?

**Comment by chubin** [comment]
Yes! it would be VERY VERY great. We are missing Estonian since several years

Please translate this:

https://github.com/chubin/wttr.in/tree/master/share/translations

and this:

https://github.com/chubin/wttr.in/blob/master/lib/translations.py

**Comment by janesmae** [comment]
> https://github.com/chubin/wttr.in/blob/master/lib/translations.py

Updated in #276 
Will work on the next file asap.

**Comment by chubin** [comment]
Thank you!
Is this correct?
```
ilmaennustus = Weather forecast for:
Hommik, Päev,     Õhtu,     Öösel =
Morning, Day, Evening, Night
```

Please take a look at the current version (without weather conditions translations):

https://et.wttr.in/

**Comment by janesmae** [comment]
> Thank you!
> Is this correct?
> 
> ```
> ilmaennustus = Weather forecast for:
> Hommik, Päev,     Õhtu,     Öösel =
> Morning, Day, Evening, Night
> ```
> Please take a look at the current version (without weather conditions translations):
> 
> https://et.wttr.in/

Estonian is a weird language in the sense that it has 14 case forms. 
The words for morning, day, evening are in nominative but the word for night is in adessive (answers to question like "when"). The Nominative case version for night would be "Öö".

IMHO I would use adessive case on all the 4 words. This sounds much more logical to a native speaker: Hommikul (in the morning), Päeval (during the day), Õhtul (in the evening), Öösel (at night)

"Ilmaennustus" is technically correct but the professional term is "Ilmaprognoos". Ref: Estonian Weather Service - http://www.ilmateenistus.ee/ilm/prognoosid/4-oopaeva-prognoos/ (changing the language in top navigation swaps languages)

So, depending on what case you need/want them, I can translate the words.

**Comment by janesmae** [comment]
Updated the second file now with #277. Will take on the help page asap.

**Comment by janesmae** [comment]
Added last translations for Estonian in #286 and #285.

**Comment by chubin** [comment]
Thank you very much!
It is live now:

```
curl et.wttr.in
curl et.wttr.in/:help
```

I've added your name to /:translation if you do not mind (if you do, just say, I will remove those line).

Thank you very much once again

**Comment by janesmae** [comment]
Completely fine. Thanks. Will report some missing strings as I see them under #287

**Comment by chubin** [comment]
@janesmae 

Jaan hi! We are translating the new view (`curl v2.wttr.in`).
Could you please take a look at it and the Estonian translation?
It is just a single line:

[lib/translations_v2.py](https://github.com/chubin/wttr.in/blob/master/lib/translations_v2.py)

**Comment by janesmae** [comment]
done -> https://github.com/chubin/wttr.in/pull/399

Sry took so long.

**Comment by chubin** [comment]
@janesmae Jaan, thank you for the translation. It is not yet activated, but will be activated soon
