### ISSUE TITLE
Forecast calls for a partially sunny... night time?

### ISSUE THREAD

**Issue by jmccorm** [chubin/wttr.in#282]
Perhaps a bright sun peaking out from behind the clouds isn't an ideal way of representing Partly Cloudy for the Night time period?

![image](https://user-images.githubusercontent.com/18018091/54178644-8e84d880-4464-11e9-8a24-10b92ee1aa8a.png)

**Comment by cmdcolin** [comment]
Would also be curious if the oneline format at night could be moon icon instead of sun icon :)

**Comment by vophatechnicus** [comment]
Duplicate of Issue #258

...

**Comment by msikma** [comment]
This and #258 are actually duplicates of an older issue, #52.

**Comment by chubin** [comment]
I think we should close both this and #258 in favor of #52.
And the only reason why #52 is still open (besides the implementation itself, of course)
is the "One weather condition - one notation." controversy.
Probably, we should just implement it and add an configuration option for the "sunny night" format
