### ISSUE TITLE
"Out of queries" again...

### ISSUE THREAD

**Issue by vitich** [chubin/wttr.in#292]
$ curl wttr.in

Sorry, we are running out of queries to the weather service at the moment.
Here is the weather report for the default city (just to show you, how it looks like).
We will get new queries as soon as possible.
You can follow https://twitter.com/igor_chubin for the updates.
======================================================================================

I found temporary solution:
1) install ansiweather
2) add to your conkyrc
`${font Liberation:style=Normal:pixelsize=17}${texeci 300 ansiweather -l Kyiv,UA -u metric -s true -d true -a false | awk '{split($0,a,"-"); print a[1]; print a[2]; print a[3]; print a[4]; print a[5]}'}
`

**Comment by vitich** [comment]
$ ansiweather -l Kyiv,UA -u metric -s true -d true -a false | awk '{split($0,a,"-"); print a[1]; print a[2]; print a[3]; print a[4]; print a[5]}'
 Weather in Kyiv => 19 °C ☀ 
 Wind => 2 m/s S 
 Humidity => 20 % 
 Pressure => 1029 hPa 
 Sunrise => Apr 23 05:48:46 AM

**Comment by chubin** [comment]
It was a temporary problem, it should work now. Does it work for you? Please test

**Comment by vitich** [comment]
@chubin Yes, it works. Thank you!

**Comment by HettikLimbani** [comment]
I am also having the same ERROR ..

**Comment by chubin** [comment]
@HettikLimbani The problem was fixed (29 days ago); just wanted to say you thanks for reporting

**Comment by Abates-95** [comment]
Having the same problem again
