### ISSUE TITLE
ip2location correctly reports as London, UK, but wttr.in is giving me weather for Annan, UK

### ISSUE THREAD

**Issue by godeater** [chubin/wttr.in#298]
Every GeoIP service I've tried correctly sees my IP address as London UK - but wttr.in is reporting the weather for a location "Annan, UK" (Somewhere I had to look up, as I'd never heard of it!)

**Comment by chubin** [comment]
@godeater Thank your for reporting it. Could you please share your IP (at least the first three octets)?

**Comment by godeater** [comment]
@chubin Sure - should have included that in the first place:

86.184.37.xxx

**Comment by godeater** [comment]
Actually, I've just noticed it's getting it even more wrong when I'm at work (and you can have the full IP there - don't care about work's network :) )
>$ dig +short myip.opendns.com @resolver1.opendns.com
185.14.147.170
$ curl https://wttr.in/\?0qnT
Oymyakon, Russia
    \  /       Partly cloudy
  _ /"".-.     6..8 °C        
    \_(   ).   ↖ 14 km/h      
    /(___(__)  20 km          
               0.0 mm   
$ geoiplookup 185.14.147.170
GeoIP Country Edition: GB, United Kingdom
`

**Comment by chubin** [comment]
Should be better now, please check:
```
ic$ curl wttr.in/@86.184.37.5?q0
Bethnal Green, United Kingdom

    \  /       Partly cloudy
  _ /"".-.     12..13 °C      
    \_(   ).   → 9 km/h       
    /(___(__)  10 km          
               0.0 mm         
ic$ curl wttr.in/@185.14.147.170?q0
Staines-upon-Thames, United Kingdom

    \  /       Partly cloudy
  _ /"".-.     9..11 °C       
    \_(   ).   → 13 km/h      
    /(___(__)  10 km          
               0.0 mm   
```

**Comment by godeater** [comment]
Fantastic - much better now - thanks for such a speedy fix.

**Comment by chubin** [comment]
@godeater Are these location correct (especially Staines-upon-Thames), or would you prefer `London` instead?

**Comment by godeater** [comment]
The Bethnal Green one is close enough. 

The Staines-Upon-Thames one may well be where our datacenter is, so is probably also true enough.

**Comment by chubin** [comment]
@godeater Thank you!
