### ISSUE TITLE
Wrong translation for Vietnamese

### ISSUE THREAD

**Issue by phuclv90** [chubin/wttr.in#299]
The translation for Vietnamese currently has a lot of issues. There's a ticket for the translation #86 but it was closed

The most obvious one was that the time periods for morning/noon/were "buổi sáng/ngày/tối/đêm" but in fact they should be "sáng/trưa/chiều/tối" (or maybe a little bit different depending on what time ranges you're talking about)

A lot of the words arealso  too long and truncated so I couldn't understand what they say. Some are even wrong in terms of grammar or usage. They're never used in weather forecasts or even normal day. Some examples: "Các cơn giông…", "Mưa rào vừa hoă…", "Mưa lả tả gần...", "Mưa rào xối xả"

The date format is also wrong. I know it's on the locale setting for Vietnam but no one writes like that ever. I have no idea whoever thought that it's the way Vietnamese write dates. For May 12th we always write 12/5

**Comment by chubin** [comment]
@phuclv90 I reopened the old ticked (#86). Could you please help us with fixing the Vietnamese translation?

**Comment by phuclv90** [comment]
@chubin can you tell me where the translation is?

I've looked at https://github.com/chubin/wttr.in/blob/master/lib/translations.py and https://github.com/chubin/wttr.in/tree/master/share/translations but found nothing related to Vietnamese

Besides, "noon" refers to the point of time at exact 12am right? So I find it a little bit strange to give weather report for noon or the time around noon. If it refers to the afternoon period then we'll have a different translation

**Comment by chubin** [comment]
@phuclv90 Actually, I've checked it and now I see, that the Vietnamese translation comes from the datasource and that is really so, that the quality of this translation maybe not that good as from other translations made by the wttr.in community.

If you want to help to improve it (and it would be really great), you should:

1. Fork the repo
2. Add the new translation here: https://github.com/chubin/wttr.in/tree/master/share/translations (you can use any of the existing translation files as the basis for your translation)
3. Add missing phrases to `translation.py`

Regarding the noon translation, actually it should be not noon, but `day`, it is more correct

**Comment by phuclv90** [comment]
thanks for the clarification. I'll work on it this weekend

**Comment by chubin** [comment]
@phuclv90 Thank you very much! It would be really great if we could fix the Vietnamese translation, because we have quite many users from Vietnam

**Comment by chubin** [comment]
@phuclv90 Thank you very much for your fix (#307). I've merged it now and deployed live.
Could you please take a look?

```
$ curl vi.wttr.in/Paris
Báo cáo thời tiết: Paris

     \   /     Trời nắng
      .-.      23..25 °C      
   ― (   ) ―   ↙ 24 km/h      
      `-’      10 km          
     /   \     0.0 mm         
                                                       ┌─────────────┐                                                       
┌──────────────────────────────┬───────────────────────┤  CN 07 Th07 ├───────────────────────┬──────────────────────────────┐
│             Sáng             │             Trưa      └──────┬──────┘      Chiều            │              Tối             │
├──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┤
│               Nhiều mây      │    \  /       Có mây         │    \  /       Có mây         │               Nhiều mây      │
│      .--.     21 °C          │  _ /"".-.     26 °C          │  _ /"".-.     25..26 °C      │      .--.     21 °C          │
│   .-(    ).   ↓ 9-11 km/h    │    \_(   ).   ↓ 7-9 km/h     │    \_(   ).   ↖ 14-17 km/h   │   .-(    ).   ↙ 16-19 km/h   │
│  (___.__)__)  10 km          │    /(___(__)  10 km          │    /(___(__)  10 km          │  (___.__)__)  10 km          │
│               0.0 mm | 0%    │               0.0 mm | 0%    │               0.0 mm | 0%    │               0.0 mm | 0%    │
└──────────────────────────────┴──────────────────────────────┴──────────────────────────────┴──────────────────────────────┘
                                                       ┌─────────────┐                                                       
┌──────────────────────────────┬───────────────────────┤  T2 08 Th07 ├───────────────────────┬──────────────────────────────┐
│             Sáng             │             Trưa      └──────┬──────┘      Chiều            │              Tối             │
├──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┤
│               Âm u           │    \  /       Có mây         │    \  /       Có mây         │    \  /       Có mây         │
│      .--.     19 °C          │  _ /"".-.     22 °C          │  _ /"".-.     22..24 °C      │  _ /"".-.     19 °C          │
│   .-(    ).   ↙ 16-19 km/h   │    \_(   ).   ↙ 17-19 km/h   │    \_(   ).   ↙ 18-21 km/h   │    \_(   ).   ↙ 17-21 km/h   │
│  (___.__)__)  10 km          │    /(___(__)  10 km          │    /(___(__)  10 km          │    /(___(__)  10 km          │
│               0.0 mm | 0%    │               0.0 mm | 0%    │               0.0 mm | 0%    │               0.0 mm | 0%    │
└──────────────────────────────┴──────────────────────────────┴──────────────────────────────┴──────────────────────────────┘
                                                       ┌─────────────┐                                                       
┌──────────────────────────────┬───────────────────────┤  T3 09 Th07 ├───────────────────────┬──────────────────────────────┐
│             Sáng             │             Trưa      └──────┬──────┘      Chiều            │              Tối             │
├──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┤
│    \  /       Có mây         │    \  /       Có mây         │    \  /       Có mây         │    \  /       Có mây         │
│  _ /"".-.     16..17 °C      │  _ /"".-.     21 °C          │  _ /"".-.     22..24 °C      │  _ /"".-.     20 °C          │
│    \_(   ).   ↙ 14-16 km/h   │    \_(   ).   ↙ 14-17 km/h   │    \_(   ).   ↓ 18-21 km/h   │    \_(   ).   ↓ 14-19 km/h   │
│    /(___(__)  10 km          │    /(___(__)  10 km          │    /(___(__)  10 km          │    /(___(__)  10 km          │
│               0.0 mm | 0%    │               0.0 mm | 0%    │               0.0 mm | 0%    │               0.0 mm | 0%    │
└──────────────────────────────┴──────────────────────────────┴──────────────────────────────┴──────────────────────────────┘

Theo dõi @igor_chubin để cập nhật thông tin về wttr.in
```

In my opinion, everything works just perfect here.

The only problem that I've found is that in PNG files some characters
are not displayed correctly:

![Prague](https://user-images.githubusercontent.com/3875145/60772248-f3d79600-a0f3-11e9-8788-7f3d2d3e463f.png)

I suppose that the problem here is related to PIL rendering problems
(i.e.: https://github.com/python-pillow/Pillow/issues/2255)

**Comment by phuclv90** [comment]
@chubin I think it's good. But maybe a few more comments from others will be better

**Comment by chubin** [comment]
@phuclv90 Thank you very much! I will tweet about it later, and maybe some of my followers take a look it. Thank you very much for your help once again
