### ISSUE TITLE
Option for shorter output.

### ISSUE THREAD

**Issue by cjwelborn** [chubin/wttr.in#30]
It would be great to have options for shorter/longer output. Like:

``` bash
$ curl 'http://wttr.in/?now'
```

```
               Overcast 
      .--.     64 °F          
   .-(    ).   ↑ 18 mph       
  (___.__)__)  9 mi           
               0.0 in   
```

Another one I would use is `curl http://wttr.in/?week`, where just a 5 day forecast it shown with only one row of output. 

I'm sorry I don't have a pull request to go with this. I just wanted to put the idea out there.

**Comment by bndr** [comment]
You can get shorter output by using
`curl -s -N http://wttr.in/Frankfurt | head -n 7`

**Comment by nathan-v** [comment]
I believe this can be closed...

```
$ curl "http://wttr.in/?Q0"
      .-.      Light Rain
     (   ).    55 – 57 °F
    (___(__)   ↗ 6 mph
     ‘ ‘ ‘ ‘   8 mi
    ‘ ‘ ‘ ‘    0.0 in```

**Comment by chubin** [comment]
@nathan-v Right! Thank you for reminding me about this issue!! (and you don't need http:// actually).

**Comment by cjwelborn** [comment]
Thanks, the 'number of days' thing is perfect.

**Comment by chubin** [comment]
Thank you @cjwelborn ! I hope to publish tomorrow another feature, that you like even more (I hope).

**Comment by cjwelborn** [comment]
@chubin, awesome, I'm looking forward to it 😀.
