### ISSUE TITLE
Which terminal font do you recommand ?

### ISSUE THREAD

**Issue by gbetous** [chubin/wttr.in#312]
Not a really issue, but I cannot find in the documentation which terminal font do you recomand to enjoy all weather symbols. With my default terminal settings, I only see garbage signs :(

Maybe you could specify one or two ?

Thanks !

**Comment by iago-lito** [comment]
I'm not the authority here at all. But my guess is that this is more about fonts and utf-8 support than about a particular terminal.

Can you see the symbols correctly [online](http://wttr.in/)? What if you copy-paste them in your terminal, or anywhere on your machine?

**Comment by elias-boemeke** [comment]
It sounds like there are no emoji fonts installed on your system.
So your browser probably doesn't render these symbols well too.
If you are searching for fonts, the <a href="https://wiki.archlinux.org/index.php/Fonts">Arch Wiki Article</a> on this topic is a good place to start, even if you don't have Arch.

I think installing the noto emoji fonts might fix your issues.

**Comment by chubin** [comment]
I've added a couple of recommendations regarding the font and emoji support to README.md.
@gbetous thank you for the question, @iago-lito and @elias-boemeke thank you very much for the help!
