### ISSUE TITLE
The site is down

### ISSUE THREAD

**Issue by juacq97** [chubin/wttr.in#315]
I can't enter wttr.in anymore, `curl wttr.in` get me an error, and on firefox I get `504 Gateway Time-out`

**Comment by CollinChaffin** [comment]
I don't know how I'll survive without my weather......I can feel the anxiety rising.....what if rain is on the way? :cloud_with_lightning_and_rain:

**Comment by chubin** [comment]
@CollinChaffin @juacq97 Does it work for you now?

**Comment by danielmichaels** [comment]
@chubin, it is still down for me. Curl sends a 504, [isitdown](https://www.isitdownrightnow.com/wttr.in.html) reports it offline, too. 

Just a heads up. :ok_man:

**Comment by chubin** [comment]
@danielmichaels It should work now. Please check

**Comment by danielmichaels** [comment]
All good! moments after sending sending my message, the weather reappeared in Tmux.

Thank you! :+1:

**Comment by chubin** [comment]
@danielmichaels @CollinChaffin @juacq97 Thank you all!

**Comment by JeremyKennedy** [comment]
Seems down again: https://www.isitdownrightnow.com/wttr.in.html

**Comment by juacq97** [comment]
It's not loading for me

**Comment by chubin** [comment]
@JeremyKennedy @juacq97 Do you still have the problem? I can't reproduce it
The internal monitoring systems reports that everything is up and running too

**Comment by juacq97** [comment]
It's working now, the webpage and the `curl` command
