### ISSUE TITLE
Hi, testing your weather app... I came across this issue...

### ISSUE THREAD

**Issue by inglesuniversal** [chubin/wttr.in#322]
I tried loading this URL from within my Amazon bucket static website and even though that I added the M metric conversion for the temp. I still get the Fahrenheit reading instead.

TEST URL:

https://wttr.in/Mexico?m&format=%l+%c+%t+%h+%w+%p

Is there a way to force it to get the Celsius degrees?

Regards

**Comment by chubin** [comment]
@inglesuniversal Hi Hugo,

you are doing everything right, and the URL should work.
To force the USCS you use the `u` option, and to force SI (Metric) you use `m`:

```
$ curl 'https://wttr.in/Mexico?m&format=%l+%c+%t+%h+%w+%p'
Mexico 🌦 +15°C 69% ↙5 km/h 0.1mm
$ curl 'https://wttr.in/Mexico?u&format=%l+%c+%t+%h+%w+%p'
Mexico 🌦 +58°F 69% ↙3 mph 0.1mm
```

I am doing my queries from Europe, and as you can see the `u` switch worked,
and switched output to USCS.

The only thing that seems suspicious to me is that you wrote `M` uppercase in your text (but in the query, everything is fine). Could you please check it with `m` and if it still will not work, then write about it here?

**Comment by inglesuniversal** [comment]
ok, I just remembered the scenario of how this issue took place... I loaded the url above using javascript and fetch inside an Amazon Bucket located on the West Coast of the US... and even though I had the m (lowercase) to enforce Celsius degrees, the output would come as Fahrenheit, I guess because the location of the bucket resides with in the states, and was not fully delivering my request of a location in Mexico. Do you think you could tackle this issue or do you want me to run more tests tomorrow? Regards and by the way... Beautiful script you came up with!

**Comment by chubin** [comment]
@inglesuniversal Yes, that's right, that the only reason why the output could be in Fahrenheit was that the IP-address of the client was classified as a US one, that is clear, but the question is why the `m` option that had to force SI, did not do it? Please recheck if it is possible; I will check it too

**Comment by chubin** [comment]
I've just checked it from a US East network, everything works at expected:

```
$ curl 'https://wttr.in/Mexico?m&format=%l+%c+%t+%h+%w+%p'
Mexico 🌦 +15°C 72% ↓6 km/h 0.6mm
$ curl 'https://wttr.in/Mexico?u&format=%l+%c+%t+%h+%w+%p'
Mexico 🌦 +60°F 72% ↓4 mph 0.6mm
$ curl 'https://wttr.in/Mexico?format=%l+%c+%t+%h+%w+%p'
Mexico 🌦 +60°F 72% ↓4 mph 0.6mm
$ curl 'https://wttr.in/?format=%l+%c+%t+%h+%w+%p'
Ashburn, United States ⛅️ +81°F 67% ↓0 mph 0.1m

```

So I suppose that you indeed used `M` instead of `m`.
Please double check, and if the problem will persist, please post the details how it can be reprodruced

**Comment by inglesuniversal** [comment]
Under my set up I am loading that URL using the fetch API inside a webpage and then placing the output inside a DIV. Can that be supported besides Curl?

Enviado desde mi iPhone

**Comment by chubin** [comment]
@inglesuniversal Yes, it is possible; actually, it does not matter what client you use when fetching the information when using one-line format (`format=`), for the normal queries you can just use `A` to force the ANSI output format, or just specify `curl` as `User-Agent`

**Comment by chubin** [comment]
All problems mentioned in this issue are fixed (+ CORS is enabled now);
if you will have any new questions, please comment the issue

**Comment by inglesuniversal** [comment]
Thanks @chubin I will be more than happy to test drive the updates!!!

STAY SAFE!!! --> The world needs developers like you!

**Comment by chubin** [comment]
@inglesuniversal Thank you Hugo!
