### ISSUE TITLE
Unable to add my characters in oneline custom format

### ISSUE THREAD

**Issue by daniel-1964** [chubin/wttr.in#325]
I would like to add my text in custom format.
If I add ':' or space, it work, if I add letter it fail.
samples to reproduce:
curl -s4 wttr.in/toulouse?format=%l:+%C+Température:+%t
-->
toulouse: : +32°C

curl -s4 wttr.in/toulouse?format=%l:+%C+Temperature:+%t
-->
toulouse: : +32°C

curl -s4 wttr.in/toulouse?format=%l:+%C+Température:+%t+Vent:+%w
-->
toulouse: : +32°C: →17 km/h

curl -s4 wttr.in/toulouse?format=%l:+%C+Température:+%t+Vent:+%w+Pression:+%P
-->
toulouse: : +32°C: : 1015hPa

What's I do wrong?

Daniel

**Comment by chubin** [comment]
@daniel-1964 I think that it is a bug indeed; it seems to me that some text can be added only at the beginning of the string currently, but after added special characters it has no effect (in the best case):

```
$ curl wttr.in/toulouse?format=Température:+%t
Température: +32°C
```

**Comment by chubin** [comment]
It is fixed now, please test

```
$ curl fr.wttr.in/toulouse?format=%l:+%C+Température:+%t+Vent:+%w+Pression:+%P; echo
toulouse: Ensoleillé Température: +33°C Vent: →15km/h Pression: 1016hPa
```
