### ISSUE TITLE
wttr.in error on load webpage

### ISSUE THREAD

**Issue by Tabetha** [chubin/wttr.in#33]
[wttr.in](wttr.in) page showing ERROR

![image](https://cloud.githubusercontent.com/assets/1709099/14460343/4e0c1270-00bd-11e6-9681-2afba51f7c4c.png)

**Comment by JD557** [comment]
This also happens to me when making a request from Portugal.

However, if I make my request from my VPS in the United States, everything works as expected.

**Comment by chubin** [comment]
It may happen periodically if our data service provider has problems. It happens. If the problem will not disappear, please let me know if it happens if you access not wttr.in but wttr.in/Berlin for example

**Comment by Tabetha** [comment]
I have still problem even on dsl or mobile network. Requesting wttr.in or wttr.in/Berlin ends with same error for now, I will see evening or tommorow :)

**Comment by JD557** [comment]
@chubin on my local machine, both cases (`wttr.in` and `wttr.in/Berlin`) fail, while on my remote machine both of them work fine.

**Comment by chubin** [comment]
I think I've fixed it. Can you please recheck it?

**Comment by Tabetha** [comment]
Its working thx :)

**Comment by JD557** [comment]
Same here. I think this issue can be closed.

**Comment by chubin** [comment]
Thank you for the help, guys!

**Comment by Kingshish** [comment]
Hi

This is still an issue, if you're in South Africa

**Comment by chubin** [comment]
@Kingshish Is it still an issue now?

**Comment by Kingshish** [comment]
Yes

Curl wttr.in

Returns

ERROR

**Comment by chubin** [comment]
@Kingshish Please check it again. It should work now. If your location is unkown it should write the name of your location (how it was detected) and bring you to Oymakon. Please check it, if it works as expected

**Comment by Kingshish** [comment]
Still says ERROR,  I'm in Johannesburg if that helps

**Comment by chubin** [comment]
And now?

**Comment by Kingshish** [comment]
It works! Thanks man,  awesome work

**Comment by chubin** [comment]
@Kingshish Thank you for the reporting!

**Comment by peter9teufel** [comment]
Hi @chubin
same for me, opening it in the browser or via "curl wttr.in" gives me an error, for some locations (e.g. Vienna) it just displayed a note "New feature: multilingual location....."

Thx and cheers from Austria :-)

**Comment by chubin** [comment]
@peter9teufel Thank you very much for the reporting! (es sollte jetzt wieder laufen und schöne Grüße aus Bayern :)

**Comment by peter9teufel** [comment]
Das geht ja sprachlich gleich viel leichter von der Hand :-D
Perfekt danke!

**Comment by chubin** [comment]
@peter9teufel apropos: curl de.wttr.in

**Comment by vijaygalagali20** [comment]
ITS NOT WORKING STILL GET ERROR

**Comment by chubin** [comment]
@vijaygalagali20 It works now. Thank you for reporting!

**Comment by vijaygalagali20** [comment]
yup its working thank you all

**Comment by ngoctnq** [comment]
now I'm having the "ERROR" problem, with or without the ".de" prefix. for what it's worth, I am currently in the US.

**Comment by chubin** [comment]
@ngoctnq Fixed! Thank you for reporting

**Comment by hopkins001** [comment]
ERROR Problem for me. Tried http://wttr.in/Toronto and http://wttr.in/Hamilton

**Comment by chubin** [comment]
@hopkins001 Fixed! Thank you for reporting
