### ISSUE TITLE
[Feature Request] Graph to show weather temperature throughout the day

### ISSUE THREAD

**Issue by nebulaw2081d** [chubin/wttr.in#332]
I am a frequent user of wttr.in and was thinking how nice it would be to have some kind of sine graph or chart included with the output of the weather through some kind of switch. I am thinking of creating something with matplotlib, but I am not entirely how to implement it.

**Comment by chubin** [comment]
That is how it looks like in the next version we are currently working on:

![Selection_032](https://user-images.githubusercontent.com/3875145/62429720-934b7100-b712-11e9-8497-8cf3e630c8cb.png)

Do you like it?

**Comment by nebulaw2081d** [comment]
@chubin I do! Thank you for your guys' hard work.
