### ISSUE TITLE
"website is down" (500 error)

### ISSUE THREAD

**Issue by vitich** [chubin/wttr.in#333]
![Screenshot from 2019-08-09 14-36-04](https://user-images.githubusercontent.com/12166319/62776356-09edc300-bab3-11e9-9ed3-df1a0626feda.png)

![Screenshot from 2019-08-09 14-36-58](https://user-images.githubusercontent.com/12166319/62776395-2db10900-bab3-11e9-9965-265ad57a88cf.png)

**Comment by dimir** [comment]
I confirm the issue.

**Comment by LittleMonkeyMojo** [comment]
Also confirmed

**Comment by chubin** [comment]
@vitich @dimir @LittleMonkeyMojo Thank you for reporting; please check it now

**Comment by LittleMonkeyMojo** [comment]
Yes, it's up and running again.
