### ISSUE TITLE
ERROR: out of queries — will be back online soon

### ISSUE THREAD

**Issue by tbergeron** [chubin/wttr.in#335]
I used to have the request throttle limit message but now the entire website says:

> ERROR
http://wttr.in/

sometimes it still says:

> Sorry, we are running out of queries to the weather service at the moment.
> Here is the weather report for the default city (just to show you, how it looks like).
> We will get new queries as soon as possible.
> You can follow https://twitter.com/igor_chubin for the updates.

Just thought I'd report this here since it's been like that for the past days.

Thanks!

**Comment by chubin** [comment]
@tbergeron Tommy, thank you very much for reporting. In this case it is a real root of the problem indeed; in 4 hours we will be back online.

**Comment by tbergeron** [comment]
@chubin no worries, thanks for your awesome work!

**Comment by chubin** [comment]
@tbergeron It should work now, please test

**Comment by tbergeron** [comment]
@chubin works now! thanks 😀
