### ISSUE TITLE
curl wttr.in/moon displays a town instead

### ISSUE THREAD

**Issue by Rosika2** [chubin/wttr.in#337]
Hi,

"curl wttr.in/moon" gives me 
`Location: Muhu, Muhu vald, Saare maakond, Eesti [58.5959044,23.219646086]
`
instead of moon phase.
Could you help me?

Tnx and greetings.
Rosika

**Comment by chubin** [comment]
Please check it now, it should work

**Comment by Rosika2** [comment]
@chubin:

I just checked it and it works now.
Thank you very much for fixing it. I like **wttr.in** a lot and use it on a regular basis.

Greetings
Rosika

**Comment by chubin** [comment]
@Rosika2 Thank you! Then you will probably like the new feature too:

Please take a look at it:

```
curl v2.wttr.in
```

**Comment by Rosika2** [comment]
@chubin:
Hi again and thanks  a lot for that new version. I´m quite excited about it and I must say I like it very much.
What a nice supplement to the first version.
On thing though: **curl v2.wttr.in/Moon** doesn´t seem to work here. Again it´s
`Location: Muhu, Muhu vald, Saare maakond, Eesti [58.6023,23.2179]
`
which is displayed.

Greetings.
Rosika

**Comment by chubin** [comment]
@Rosika2 I am not sure that it is wrong. Maybe, it is ok to have it this way, because there is no point to use the new view (v2) (as well as one-line formats) for the special Moon query

**Comment by Rosika2** [comment]
Hi chubin and thanks for the explanation.
It makes sense.  And moon display works well with the old view.

Yet another "problem" arises:
I often check the weather in Alsómocsolád (a small village in Hungary).
**curl wttr.in/Alsómocsolád** works well but curl **v2.wttr.in/Alsómocsolád** gives an error-message:
(Unknown location).
Do the two versions of wttr.in use different data-bases as far as the towns are concerned?

Geetings 
Rosika

**Comment by chubin** [comment]
Actually, it is another problem that we are experiencing currently because of the very high load. If you are trying to get informartion for some location is not cached (though it can be cached for the v1 frontend) it is possible that you will get the "wrong location" error message. Of course, it is a bug, but it is bug not related to the v2 view directly.

Please try `v2.wttr.in/Alsómocsolád` again; the chances are high that it will work now

**Comment by Rosika2** [comment]
Hello chubin,

thank you so much for the information.
It´s alright now - as you suggested. `v2.wttr.in/Alsómocsolád` works fine today.
The very high load is surely due to the high popularity of wttr.in  :) .

So thanks again for helping me so patiently with my "problems" and for bringing **v2.wttr.in** to my attention. Otherwise I would have missed it.

Greetings
Rosika
