### ISSUE TITLE
unwanted location and coordinates

### ISSUE THREAD

**Issue by v1nc** [chubin/wttr.in#342]
Hey,
I am using curl to pipe wttr.in output on my launcher: `curl -s wttr.in/dortmund\?0T`
It only showed the ascii art and weather text, like it should.

Unfortunately since some weeks, it also prints `Location www, xxx, yyy, zzz`
`[aaaa,bbbb]`
with details for my location.
Is this intended?
Can I turn the location string off with some parameter?

**Comment by chubin** [comment]
@v1nc It is not intended, but it is known. We should add some parameter to switch it off, but currently there is no such parameter.

What I did now, I switched the location off for the 0 days forecast, where it looks really ugly.

Please test if it works for you (append `+`  to the test query to bypass the caching mechanism: `curl -s wttr.in/dortmund+\?0T`).

**Comment by v1nc** [comment]
Yeah that works, thanks :)
