### ISSUE TITLE
weather icons on v2

### ISSUE THREAD

**Issue by iomari** [chubin/wttr.in#344]
Greetings,
I just tried v2 on my desktop and it looks great. But on my laptop the cloud symbols and moon symbols are rectangles.

my desktop is ubuntu cosmic and my laptop is ubuntu disco. Both are using tilda as terminals. I keep both systems updated daily.

What am I missing on my laptop?

Thanks
iomari

**Comment by chubin** [comment]
@iomari Could you please try gnome-terminal (just to test it)?

**Comment by iomari** [comment]
Not working on gnome-terminal either.

**Comment by chubin** [comment]
Have you tried this:
To see emojis in terminal, you need:

    Terminal support for emojis (was added to Cairo 1.15.8);
    Font with emojis support.

For the Emoji font, we recommend Noto Color Emoji, and a good alternative option would be the Emoji One font; both of them support all necessary emoji glyphs.

Font configuration:

```
$ cat ~/.config/fontconfig/fonts.conf
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <alias>
    <family>serif</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <alias>
    <family>sans-serif</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <alias>
    <family>monospace</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
</fontconfig>
```
(to apply the configuration, run `fc-cache -f -v`)

**Comment by iomari** [comment]
Thanks. Noto did it. :-)

**Comment by iomari** [comment]
Thanks. Noto did it. :-)
