### ISSUE TITLE
Weather report Image not loads on Readme.md 

### ISSUE THREAD

**Issue by ohld** [chubin/wttr.in#346]
![image](https://user-images.githubusercontent.com/5613295/64437652-55ee5080-d0cf-11e9-82d4-3b384310dc69.png)

Just noticed this. May me helpful.

**Comment by chubin** [comment]
@ohld Yes, I know this, Daniil. It is a performance problem, because of the high load that we are currently experiencing. We are working on it, and the issue should be fixed soon

**Comment by chubin** [comment]
@ohld Avg query handling time is under 100ms now, and the problem with embedded PNG files should be fixed too

```
$ time curl wttr.in/?format=3
Nuremberg, Germany: ⛅️ +17°C

real	0m0.080s
user	0m0.008s
sys	0m0.009s
```
