### ISSUE TITLE
Multiple word US format failing

### ISSUE THREAD

**Issue by dessalines** [chubin/wttr.in#347]
Running `curl 'wttr.in/~San+Francisco?format="%t"'` gets me 

`Unknown location; please try ~37.7792808,-122.4192362`

**Comment by chubin** [comment]
@dessalines Actually, it is not the real problem; the real problem is that today our datasource is experiencing partial outage, and it does not deliver information data for almost all locations in the world. I don't know how much does it take to recover, but certainly it will not happen today.

**Comment by dessalines** [comment]
What's the data source? It might also be a good idea for that to pull that as a static file, that is periodically pulled on every new build of wttr. Especially if it happens frequently.

**Comment by chubin** [comment]
I am not sure that I understand what you mean, what kind of file should be pulled.

Anyway, the problem is fixed, please test

**Comment by dessalines** [comment]
Its good, thanks. 

> what kind of file should be pulled.

What's your data source for locations? You could save a csv of the cached location names, if those go down frequently.

**Comment by chubin** [comment]
@dessalines No, you've got me wrong. I meant not the location data source, it is not a problem at all (though even this can't be converted into a CSV file because we support all possible languages and all possible location names), but the problem was with the weather data source; the error message was just irritating.

**Comment by dessalines** [comment]
Ah okay, then maybe a better error message returned is necessary, since that wasn't the actual error. Something like `weather service down / unavailable`

**Comment by chubin** [comment]
Yes, you are right. By the way, after you opened the issue, I changed the error message to the default  one (that we have usually in such cases).
