### ISSUE TITLE
Simple caching

### ISSUE THREAD

**Issue by munrocape** [chubin/wttr.in#35]
If you are running into the 1M query limit, why not implement some sort of caching?

Maybe something like 

```Python
weather = {
        {'city': 'Halifax', weather_info: ..., 'cached': datestamp}
        , ... 
        }
```

Only requery if the info is 30 minutes old - or even then are you seeing issues?

**Comment by chubin** [comment]
That's of course implemented already. Without caching it were much worse. it were actually impossible to work at all. There are dozens of users that just have some scripts that query wttr.in every minute or even every 5 seconds (that makes no sense because of the caching, but they don't care).

**Comment by munrocape** [comment]
@chubin I may be reading things incorrectly, but not just caching on an IP - but caching weather results for a location.

So even if you have 20 different IPs requesting info for whereever every minute, if they are in the same city, it counts as one request to the weather provider within the cache limit.

**Comment by chubin** [comment]
Yes, we do this type of caching. We cache the results basing on locations, IP is ignored in this case
