### ISSUE TITLE
es translation of app messages (es.txt)

### ISSUE THREAD

**Issue by jmcastagnetto** [chubin/wttr.in#352]
Did a Spanish translation of the application messages. Will submit a PR in a bit.

**Comment by chubin** [comment]
@jmcastagnetto 

Jesus hi! We are translating the new view (`curl v2.wttr.in`).
Could you please take a look at it and the Spanish translation?
It is just a single line:

[lib/translations_v2.py](https://github.com/chubin/wttr.in/blob/master/lib/translations_v2.py)

**Comment by jmcastagnetto** [comment]
It's done. 
Happy New Year 2020! 😄

**Comment by chubin** [comment]
@jmcastagnetto Thank you Jesus! I wish you Happy new year and a lot of interesting projects too! (and thank you for the pull-request)
