### ISSUE TITLE
add option for station model display

### ISSUE THREAD

**Issue by ClariNerd617** [chubin/wttr.in#368]
as a user who would like to maximize their available space, i would like to have an option for [station model plot](https://en.wikipedia.org/wiki/Station_model) as the display as it is compact and (after a little learning) easy to read in a single glance.

**Comment by chubin** [comment]
@ClariNerd617 Henry, it is an interesting feature.
Do you mean that it should be just printed in the console like that?
Something like a new additional output format or view?
Do we have all necessary unicode symbols for that?

**Comment by ClariNerd617** [comment]
If we don't have the unicode symbols, I'm sure it can be accomplished with ascii art or something similar. An optional output for those of us who like/prefer minimalism.

**Comment by chubin** [comment]
That is in interesting idea; do you maybe have some drafts? If we do it in ASCII, what do you think,
how this should look like? What width and height should it have?
