### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by vitich** [chubin/wttr.in#375]
${voffset 81}${texeci 300 curl -A "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36" http://wttr.in/Kyiv_0pq_transparency=200_lang=ua.png -o $HOME/.conky/out.png}
${image $HOME/.conky/out.png -p 0,0}

![Screenshot from 2019-11-13 14-40-51](https://user-images.githubusercontent.com/12166319/68764611-b051e300-0623-11ea-9c49-b738e6c73b8a.png)

**Comment by chubin** [comment]
I can't reproduce it. Do you still have the problem?

**Comment by vitich** [comment]
But "russian style Kiev" works...
![Screenshot from 2019-11-13 14-44-48](https://user-images.githubusercontent.com/12166319/68764862-2ce4c180-0624-11ea-9b7d-1ab73cacb0f3.png)

**Comment by vitich** [comment]
Try 'curl http://wttr.in/Kyiv_0pq_transparency=200_lang=ua.png -o $HOME/.conky/out.png'
And what you`ll get in out.png ?
Already had similar problems (Kyiv not Kiev)

**Comment by vitich** [comment]
Thank you. It works.
