### ISSUE TITLE
Negative test. Failed to substitute unknown location as Oymyakon.

### ISSUE THREAD

**Issue by kromanenko** [chubin/wttr.in#38]
Hello, i was looking into code and decided to perform some tests :)

Test command:
$ curl wttr.in/SomeVillage
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     5  100     5    0     0     15      0 --:--:-- --:--:-- --:--:--    15ERROR

Expected result: 
It seems from code that in case of unknown location service should return following text:
"""
We were unable to find your location,
so we have brought you to Oymyakon,
one of the coldest permanently inhabited locales on the planet.
"""

Actual result:
$ curl wttr.in/SomeVillage
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     5  100     5    0     0     15      0 --:--:-- --:--:-- --:--:--    15ERROR

But I see weather report for Oymyakon if i type "$ curl wttr.in/NOT_FOUND"

Environment: Windows 10 x64, mintty 2.0.3 (x86_64-pc-msys)

**Comment by chubin** [comment]
@kromanenko Thank you very much for your test. It should work now. Can you please check it?

**Comment by kromanenko** [comment]
Verified on Windows Cygwin terminal and Ubuntu 14.04. Both work as expected.
