### ISSUE TITLE
wttr.in Let’s Encrypt certificate just expired

### ISSUE THREAD

**Issue by kirb** [chubin/wttr.in#383]
The certificate on https://wttr.in just expired. There should be a cron task on the server to run `certbot renew` to ensure this cert is always current. [This](https://certbot.eff.org/docs/using.html#renewing-certificates) should help.

Thanks for running this, it’s amazing 😁

**Comment by chubin** [comment]
Actually, we have a crontask for that, but there was some misconfiguration in this case. Thank you for reporting!
