### ISSUE TITLE
Blue shades in V2

### ISSUE THREAD

**Issue by simphide** [chubin/wttr.in#385]
Can somebody explain me the blue shades in the rain section? 

What does the height and the color of the bars mean? Thanks in advance!

**Comment by chubin** [comment]
Hi Simon!

Height: precipitation level
Color: precipitation probability

+ also, the values are displayed usually at the peak level in digital form, say: `0.41mm|77%`
so you can derive the rest from these values + from the curve form and color

**Comment by chubin** [comment]
I close this as a (subset) duplicate of #440
