### ISSUE TITLE
希望输出html格式后界面能对齐

### ISSUE THREAD

**Issue by lixiaotong** [chubin/wttr.in#390]
curl -o index.html 后排版有点乱

**Comment by chubin** [comment]
@lixiaotong I am not sure about the original question, but I assume, you want to know how to force the HTML output format. You can do it this way (`-A firefox`):
```
curl -A firefox -o index.html wttr.in
```

**Comment by lixiaotong** [comment]
http://cdn.learningpartner.club/myself/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202019-12-31%20%E4%B8%8B%E5%8D%881.06.44.png

试下来截图如上，排版还是有点问题？

**Comment by chubin** [comment]
The problem in this case, is that the font of your terminal is not a monowidth font, and the width of the space character and some other character are not equal. Probably, the best solution
is to remove the "broken" lines with sed:
```
curl -s wttr.in | sed '8,10d; 11s/.*//; 17,20d; 21s/.*//; 27,30d; 31s/.*//; 37d'
```

(but even better would be to change the font)

**Comment by lixiaotong** [comment]
Thankyou, I tried to add the font set <pre style="font-family: Monaco;"> in html, worked well.

**Comment by lixiaotong** [comment]
`<pre style="font-family: Monaco;">`

**Comment by chubin** [comment]
Thank you!
