### ISSUE TITLE
how to set degree centigrade by curl

### ISSUE THREAD

**Issue by yihchu** [chubin/wttr.in#391]
I get the weather using 'wget wttr.in/Dalian.png', but the format is in fahrenheit, what can i do?

**Comment by chubin** [comment]
@yihchu Probably, you've already fond the solution, but if not::
```
wget wttr.in/Dalian_m.png
```

**Comment by yihchu** [comment]
> @yihchu Probably, you've already fond the solution, but if not::
> 
> ```
> wget wttr.in/Dalian_m.png
> ```

Yes, thank you ~
