### ISSUE TITLE
Documentation should cover multi-word cities

### ISSUE THREAD

**Issue by charlesreid1** [chubin/wttr.in#397]
Documentation does not cover how to specify city names consisting of multiple words (Los Angeles, Hong Kong, etc). Should it be `wttr.in/LosAngeles`, or `wttr.in/Los_Angeles`, or `wttr.in/Los+Angeles`, or something else? This would be a useful thing to add to the Readme.

**Comment by charlesreid1** [comment]
Both `wttr.in/Los_Angeles` and `wttr.in/Los+Angeles` work, `wttr.in/LosAngeles` does not

**Comment by chubin** [comment]
@charlesreid1 Hey Chaz! Yes, you are right, it's a good point, we should mention
it in the documentation, maybe even in the `/:help` query.
Spaces in the wttr.in URL should be replaced, as always in URLs, with the `+` sign.
`-` will work in this particular case too, but the right way is to use `+`.

curl wttr.in/Salt+Lake+City
curl de.wttr.in/Bad+Kissingen
curl ru.wttr.in/Набережные+Челны
