### ISSUE TITLE
Please include localObsTime in json results

### ISSUE THREAD

**Issue by pragma-** [chubin/wttr.in#405]
https://www.worldweatheronline.com/developer/api/docs/local-city-town-weather-api.aspx

It says the request parameters can include the `extra` parameter, which in turn can specify the `localObsTime` parameter in order to "Add the current weather observation time in UTC as well as local time of the location requested."

It seems like this would be a very small and simple change to the request string to include the `extra` and `localObsTime` parameters.  Maybe even expose an API method to allow us to customize the request string ourselves, if that's not asking too much? But at least, please add `extra` and `localObsTime`!

Thank you for reading.

**Comment by chubin** [comment]
@pragma- Yes, we can try to add it.

Have you seen the v2 view by the way?
Does it contain the data you need?

**Comment by pragma-** [comment]
Thank you for replying quickly. You have done a lot of good work on the v2 view.

I need this data in the j1 (json) format.  I have made a quick PR: https://github.com/chubin/wttr.in/pull/407 -- is this all that needs to be done for the data to go through to the `?format=j1` parameter? I hope this helps!

**Comment by pragma-** [comment]
By the way, I looked over /lib/wttr_line.py and it looks like it passes the data straight through for `format=j1`. Let me know if I missed anything.

**Comment by chubin** [comment]
It will probably not help; at least it is not a very good solution;
you should add this parameter to `proxy.py`. Can you please add it there too?
You can do it in the same PR

**Comment by pragma-** [comment]
Where do I add it in `/bin/proxy.py`?

**Comment by pragma-** [comment]
I have looked over `proxy.py` and I do not understand where the parameter should go there.

Why is it not a very good solution? The parameter will add timestamps to the content. As far as I was able to understand, wttr_line() calls get_weather_data() which sends the query to WWO and format_weather_data() will send the content from the parameter through to render_json() when format_line == "j1". This appears to do exactly what is needed for the parameter. It does not need any language translation.

What am I missing? I look forward to fixing my misunderstanding.

**Comment by pragma-** [comment]
edit: I am resubmitting this as a new comment due to edits

I have looked over proxy.py and I do not understand where the extra=localObsTime parameter should go in that file.

Why is it not a very good solution? The extra=localObsTime parameter will add a timestamp to the content. As far as I was able to understand:

*    wttr_line() calls get_weather_data()
*    get_weather_data() sends the query to WWO
*    format_weather_data() checks format_line
*    when format_line == "j1" then the content will be sent to render_json()
*    render_json() formats the content as JSON and returns it

This appears to do exactly what is needed for the parameter. It does not need language translation.

What am I missing? I look forward to fixing my misunderstanding.

**Comment by chubin** [comment]
The problem here is that you have the same data twice: with and without the parameter.
That's why I say that it would be better to implement it on the proxy side,
but maybe it could be ok to leave it this way as you did it, but in order to eliminate duplicates we should add the parameter to the we-lang code too

**Comment by pragma-** [comment]
Where is the data duplicated? I only noticed the one `data` argument to `format_weather_data()` in wttr_line.py.  Where is the data duplicated with and without the parameter?

You mentioned the we-lang code, but I do not see the code in this repository.  I see these references to it:

* Dockerfile: `ENV WTTR_WEGO="/root/go/bin/we-lang"`
* globals.py: `WEGO = os.environ.get("WTTR_WEGO", "/home/igor/go/bin/we-lang")`

I am unsure of how you wish me to proceed from here. I want to do everything I can to help.

**Comment by pragma-** [comment]
Oh, I see https://github.com/chubin/wttr.in/blob/master/share/we-lang/we-lang.go now! I am looking at it...

**Comment by pragma-** [comment]
Ok, I am not sure what specifically to do to add it to the `extra=localObsTime` to the we-lang.go file. The reason is because I do not have an API key for WWO, and I do not know precisely how WWO adds the `localObsTime` data to the JSON structure.

I would appreciate very much if you would send me an example JSON result with the `extra=localObsTime` parameter used.  Or if you can update we-lang.go yourself when you see how the JSON is structured, this would be appreciated.

Let me know if you need anything. I hope my PR and your edit to we-lang.go will do the trick!

**Comment by chubin** [comment]
Why the data is duplicated:

the proxy caches the replies based on their urls, i.e. if URLs differ in one parameter, the objects are seen as completely different and saved to times (and what is even worse, they are queried two times, because the first replica can't be found in the cache; which, in turn, produces addtional load and costs).
So I propose to have the unified upstream query for all types of reports, i.e.
the parameter should be added either in the proxy or in each "client": v2, line, we-lang

**Comment by pragma-** [comment]
I will be happy to amend my PR. You said the proxy is the best place to add it, yes? I will be happy to do it. But I am unsure specifically where to add it. Where should I add the parameter in the proxy?

**Comment by chubin** [comment]
Here you have the query from the clients:

https://github.com/chubin/wttr.in/blob/master/bin/proxy.py#L180

Somewhere you can modify it and the parameters you want.
Actually, we already have some modifications there (e.g. language).
You can use the same way

**Comment by pragma-** [comment]
I have updated https://github.com/chubin/wttr.in/pull/407

Is this the correct way?

**Comment by chubin** [comment]
Yes, it seems to be exactly the way.
I've merged/deployed it, can you test it?

**Comment by pragma-** [comment]
Fantastic! I have tested it and the new data shows up. Perfect.

**Comment by chubin** [comment]
:+1: And we have it now everywhere, in all calls, not only in `j1`!

**Comment by pragma-** [comment]
Nice.

**Comment by pragma-** [comment]
By the way, I just made another PR for `locationname=yes`. I am unsure exactly how the result will be included since it says "nearest weather point". I am hoping it is a human-readable City name. I would like to test this field, if it is not too much trouble.

PS, it can be tested here too (I cannot do it because I do not have an API key, but you can): https://www.worldweatheronline.com/developer/premium-api-explorer.aspx

**Comment by pragma-** [comment]
I probably should have opened a new issue about `locationtime=yes`. We can close this issue and start a new issue, or just move this discussion to the PR comments instead.

I'll go ahead and close this issue. Please continue this discussion in the comments of https://github.com/chubin/wttr.in/pull/409
