### ISSUE TITLE
What are the possibilities for the weather description in the json format? 

### ISSUE THREAD

**Issue by LeducH** [chubin/wttr.in#414]
I want to get the list of all weather description when making the call 

    https://wttr.in/<city>?format=j1

There is the property `weatherDesc` which return the the description for the day. I looking for a list that contains all possibilities. where can this be found? 

Moreover I looking for an explanation of the json body in general .

**Comment by chubin** [comment]
Currently, the output is fully compatible with the WWO API.
So for the moment, the WWO API documentation must be the best source for you

**Comment by chubin** [comment]
@LeducH Here: https://www.worldweatheronline.com/developer/api/docs/

There some missing features in the API, that wttr.in supports much more translations, etc.) but the output format of the data is the same (for `j1`). It will be different format for `j2`
