### ISSUE TITLE
How to specify unit in oneliner

### ISSUE THREAD

**Issue by Xunius** [chubin/wttr.in#415]
Hi all,
How do I specify the unit for temperature (maybe for wind speeds as well) in the oneliner like this:

```
curl wttr.in/Shanghai?format="%l:%t"
```

**Comment by chubin** [comment]
You can use the same options as usually: `m`, `u` etc.

```
curl wttr.in/Shanghai?format="%l:%t"\&mu
```

Does it work for you?

**Comment by Xunius** [comment]
@chubin Yes it does! Thanks!
