### ISSUE TITLE
Data scalability problem

### ISSUE THREAD

**Issue by kyprifog** [chubin/wttr.in#417]
I noticed my weather widget stopped working.   The site mentions data scalability problems but I dont see any central issue for solving it.  Can you guide me to it?  How can I help out?

**Comment by kyprifog** [comment]
I'll go ahead and just run it locally for now, let me know if you need help.

**Comment by chubin** [comment]
@kyprifog Kyle, thank you for reporting; it should work again now

**Comment by kyprifog** [comment]
Cool, let me know if you need help scaling anything out.

**Comment by chubin** [comment]
If you need the access data (to wttr.in) for your local replica, just ping me. Also, if you can give public access t your replica, let me know its name
