### ISSUE TITLE
Chinese date format

### ISSUE THREAD

**Issue by liyishuai** [chubin/wttr.in#423]
Previously mentioned in https://github.com/chubin/wttr.in/issues/83#issuecomment-570409668

The current `date +"%a %d %B"` is hard to read in Chinese, as `%a` and `%d` are both numbers.
Consider changing it to `date +"%B%-d日%A"`:

- ```shell
  $ LANG=zh_CN date +"%B%-d日%A"
    ```
    > 三月23日星期一

- ```shell
  LANG=zh_TW date +"%B%-d日%A"
  ```
  > 3月23日週一

**Comment by chubin** [comment]
Thank you for helping with the chinese translation @liyishuai 
We have a lot of minor issues with Chinese, what is holding us back
from having the full fledged Chinese support.

I've changed it to `"%b%d日%A"` now:

```
────┤3月31日星期二├───
```

I think that the `%a` part looks somehow wrong.

Please check `curl zh.wttr.in`

**Comment by liyishuai** [comment]
LGTM. Thanks!
