### ISSUE TITLE
Add parameter for time period (amount of days)

### ISSUE THREAD

**Issue by yafp** [chubin/wttr.in#43]
It would be great if we could manually set the amount of forecast days the url-call delivers.

i.e. if i want to see just 1 day instead of 3 days

Might be related with #30

**Comment by Artanicus** [comment]
wego does have a parameter for the amount of days, so should be feasible to implement.

**Comment by chubin** [comment]
Yes, it's easy to implement. There were some caching issues related to it, but not anymore, so that is a trivial issue now.

**Comment by chubin** [comment]
It works now: just use options 0,1 or 2. More info here: http://wttr.in/:help
