### ISSUE TITLE
very small thing... typography stuff

### ISSUE THREAD

**Issue by hern42** [chubin/wttr.in#433]
hi,
there is one small thing that bugs me... in "Weather: ☀️ Clear, +21°C, 28%, **↙6 km/h**, 1015hPa" there shouldn't be a space between the figure and the unit for windspeed. besides, it's not coherent with your choice of typographical rules...

i am sure it is super easy to fix.
and, do not get me wrong, wttr.in is totally amazing.

cheers from france (yes yes in lockdown... time to mess around on the computer)
best,
a-

**Comment by chubin** [comment]
Bonsoir, merci pour la suggestion :) 

We here in Bavaria have the lockdown too, not so hard as you of course, and it is supposed to start weakening from the next week; we will see.

Back to your suggestion: if I understood it right, you mean the v2.wttr.in view.
Please test it now

**Comment by hern42** [comment]
hi, that was fast :)
yes indeed that fixed it... i failed to mention it appeared also with the wttr.in/Wherever?format=4 (or using the %x thing... i use that for my conky config) but as i guessed it worked as well there. very nice and consistent now. it actually doesn't matter if you put a space between a figure and its associated unit or not, as long as you do it always the same way. i do some scientific journal layouting and magazine layouting so i'm kinda cranky when it gets to typography ahah... 

anyhow thanks again and glad i could help a tiny little bit.
i'm all new to this git and github stuff so it was nice to be able to do it.

ce fut un plaisir, bien amicalement...
all the very best, stay safe.
a-

ps: i enjoy tremendously your list of things console-based, being a fan of console versions of all things because i find it pretty... i worship ncurses.

**Comment by chubin** [comment]
@hern42 Thank you for your help! I think it is better now, though it is still not fully
consistent, because at the main view we still have a space between the value and the unit name.
Probably, we should make it with spaces everywhere. What do you think?

**Comment by hern42** [comment]
well. that's a tough one...

https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9.pdf (go page 38 section 5.4.3)
so it seems that there should be a space indeed. 

however one may think that it can be more compact and readable without as it "separates" data better... and we are not speaking typesetting for paper print here. so i guess at the end it is your choice :) my gut feeling and scientific upbringing would point at following the rule but i love compact things, especially for terminal/console applications.

as i said, tough one.

**Comment by hern42** [comment]
there is the english version p149 of the pdf... sorry, didn't check that. just after a while i wondered if the french and english rules were different (they are for punctuation...)
doesn't change a thing though...

**Comment by chubin** [comment]
I think that it is better with space, because in UNIX/Linux it is better to have spaces, as additional separators for the case if the user wants to cut something (units in this case) off.
Also, it is easier to remove space (if the user doesn't like it) than add space.
So I would say, with space it is better

**Comment by hern42** [comment]
> Also, it is easier to remove space (if the user doesn't like it) than add space.
word!
i totally agree...
let me know if it is up to me to close that thread or whatever.

**Comment by chubin** [comment]
If everything works as expected, let's close it :)

**Comment by hern42** [comment]
ok let's wait until you do your magic then...

**Comment by chubin** [comment]
I think we can close it :)
