### ISSUE TITLE
ignores view options for PNG request

### ISSUE THREAD

**Issue by agryaznov** [chubin/wttr.in#436]
Suddenly it ignores View options for PNG request
`$ wget wttr.in/Moscow_1nqF.png -q`

expected:   

- 1 = 1 day forecast,
- n = narrow version (only day and night)
- q = quiet version  (no "Weather report" text)

real response:
![Screenshot from 2020-04-27 14-56-09](https://user-images.githubusercontent.com/3878903/80370234-62126280-8898-11ea-97aa-83493608454d.png)

has no one of these three options above applied

**Comment by chubin** [comment]
I've switched it to the experimental branch (`v2`) yesterday evening, and it seems that some cases (short options in the png filename) were not covered with the tests. For the moment use this form, it should work:
```
wttr.in/Moscow.png?1nqF
```
and I will fix it today.

**Comment by chubin** [comment]
It should work now, please test

**Comment by OPortista** [comment]
Yep it's working again for me, thanks for the update
