### ISSUE TITLE
"Running out of queries" again

### ISSUE THREAD

**Issue by YvonneHou98** [chubin/wttr.in#441]
Hi there,

I got the "running out of queries" problem again while trying to run the app. I checked previous issues and it seems like this is something that happened before, and is a problem with your data source. Just wondering if there were a time estimate for when this will be fixed? 

Thank you!

**Comment by chubin** [comment]
Yes, it is known; the problem will be fixed in two hours. Sorry for the downtime

**Comment by YvonneHou98** [comment]
Hi Igor,
Thanks for the quick fix! It was impressive. It worked on my end now :)

Best,
Yvonne Hou
