### ISSUE TITLE
Polling frequency

### ISSUE THREAD

**Issue by Silent-Hunter** [chubin/wttr.in#448]
How often does wttr.in update its weather information?

Also, how often is it appropriate for me to request data? I don't want to overwhelm your servers. Currently I'm sending two requests every 5 minutes, one for the regular wttr.in data, and one for the v2 data. But I can do it less if that's too much.

**Comment by chubin** [comment]
wttr.in has several layers of caching, and expiration time of data is dynamically calculated depending on the populatrity of the location (shorter update time for more popular locations).
On average, it is something around 30 minutes.

Polling frequency for the same location is not limited; polling frequency for different locations is limited.

5 minutes polling interval is absolutely normal, no need to be changed.
