### ISSUE TITLE
WWO strings changed, breaking translations

### ISSUE THREAD

**Issue by renyhp** [chubin/wttr.in#449]
WWO code 296 has become "Light Rain" with capitalized R, which broke the translations (as the original strings are coded as "Light rain". I would suggest applying `.capitalize()` to the weatherDesc string to prevent this from being a problem in the future, or even switching to use WWO codes as keys for the translation dict.

EDIT: I actually found code 266 became Drizzle instead of "Light drizzle", again breaking translations. So, yes, codes should be definitely used as keys.

**Comment by chubin** [comment]
Thank you for the fix; I've deployed it; let's see if it helps
