### ISSUE TITLE
is wttr.in down?

### ISSUE THREAD

**Issue by BachoSeven** [chubin/wttr.in#452]
I hope it's not an issue on my side, I only get the social hyperlinks output on wttr.in and `Unknown location; please try ~42.926326,10.761625` on v2. Tried with different browsers and with different locations.

EDIT: I can only get to work certain locations, like http://v2.wttr.in/newyork, http://wttr.in/ankara but not, say, http://wttr.in/ham or http://wttr.in/london

**Comment by chubin** [comment]
Please test it now. I think it was just a temporary problem yesterday, but it works again now

**Comment by BachoSeven** [comment]
Yep, all good.
