### ISSUE TITLE
curl wttr.in/Berlin and other readme examples gives no response

### ISSUE THREAD

**Issue by Klizzy** [chubin/wttr.in#454]
In the past i just used `curl wttr.in` and got the result right for my location.
This also dont work for me sadly anymore. 

some examples from the readme don't return any output to me
these are the one that i tested:

* curl wttr.in/Berlin
* curl wttr.in/@github.com
* curl wttr.in/Detroit?format=j1
* curl v2.wttr.in/München

in the most cases i just get the following response:
```
Follow @igor_chubin for wttr.in updates
```
**or**
```
Unknown location; please try ~48.152126,11.544467
```

Do i have to add a local config for it to work properly?

**Comment by aerophile** [comment]
Facing same issue

**Comment by aerophile** [comment]
@Klizzy Can you check again.

**Comment by chubin** [comment]
Yes, the problem was that the upstream quota was exceeded
It will work now, but let us see tonight if the quota will be enough now

**Comment by Klizzy** [comment]
it works now, thanks!
