### ISSUE TITLE
Wind direction wrong?

### ISSUE THREAD

**Issue by epoweripione** [chubin/wttr.in#455]
The wind direction looks like not correct, for example:
```
...
"winddir16Point": "ENE",
"winddirDegree": "68"
...
```
Use `curl wttr.in`, the wind direction display `←`, i think 68° display as `↗` maybe more clearer.

I did some dig to the source code, maybe some fix can do the trick:
line 98-100 in `lib/constants.py`
```
WIND_DIRECTION = [
   "↑", "↗", "→", "↘", "↓", "↙", "←", "↖", 
]
```

line 148 in `lib/view/line.py`:
````
wind_direction = WIND_DIRECTION[(degree%360)//45]
````

**Comment by chubin** [comment]
Thank you for opening the issue, but I think that wttr.in is right here.

Wind direction is reported by the direction from which it originates. For example, a northerly wind blows from the north to the south [[1](https://en.wikipedia.org/wiki/Wind_direction)], [[2](https://www.weather.gov/jetstream/wind)].

ENE means that the wind blows from ENE.

What is ENE (68⁰)?

E is 90 strictly east, and ENE is slightly rotated to the north,
so it must be displayed either as `↙` (45⁰) or `←` (90⁰);
68 is a little bit close to 90⁰ (67.5⁰ is directly in the middle),
that is why `←` is chosen.

![wind_bln1](https://user-images.githubusercontent.com/3875145/83406831-c54f6180-a40f-11ea-8f85-437e86168135.gif)

**Comment by chubin** [comment]
Please also keep in mind, that the v1 view (wego-based) and the v2/single-line view
have different methods of wind direction calculations; in the v1 view wind direction is mapped to the 16-point direction (`ENE` in our example), and in the v2/single-line view it is calculated from the wind degree (`68⁰` in our example), and thus the latter is a little preciser in some cases.

**Comment by epoweripione** [comment]
I had a wrong understanding about the wind direction before, thanks for the explanation.
