### ISSUE TITLE
Cyclic Location Query Doesn't Work (Repeating Queries)

### ISSUE THREAD

**Issue by natehouk** [chubin/wttr.in#460]
I can not get cyclic location queries to work.

For example, using the following query with  the colon ":"  separating the locations:
```
$ curl wttr.in/Amsterdam:Berlin?period=1\&format=4
Amsterdam: 🌦 🌡️+13°C 🌬️↓20km/h
```

No matter how often I run it, or how short or long I wait between running it, I always get the weather back for *only* Amsterdam.

```
Amsterdam: 🌦 🌡️+13°C 🌬️↓20km/h
```

I never get back the weather for Berlin.

I have looked through the code extensively and I do not see any bugs with the _cyclic_location_selection function, nor do I see any bugs that might cause this. It functions as if the time.time() call is failing and always returning the same time value.

It should work. But it doesn't.

P.S. It would be nice to add the "time" as part of the weather output, so you know at what time the forecast was made. It would also help debug this issue.

**Comment by chubin** [comment]
Yes, I can acknowledge that this bug exists. I will fix it. Thank you for reporting

**Comment by chubin** [comment]
Please test, it should work properly now

**Comment by chubin** [comment]
It seems to work now. Please comment if it does not work (or if it works too :)

**Comment by natehouk** [comment]
Confirmed that it is now working as expected. **Fixed.**
