### ISSUE TITLE
specify format for current location

### ISSUE THREAD

**Issue by vzaliva** [chubin/wttr.in#478]
The following works:
```
$ curl 'wttr.in/Detroit?format=3&T&q'                                          
Detroit: ⛅️  +74°F
```

As well as following:
```
$ curl wttr.in\?m                                                                                                                                                                   14:14:10
Weather report: Los Gatos, United States
...
```

But the following does not:
```
$ curl 'wttr.in?format=3&T&q'                                                   
Unknown location; please try ~37.226611,-121.9746797
```

**Comment by MyriaCore** [comment]
This appears to be a recent bug. `curl 'wttr.in?format=3&T&q'` worked just yesterday.

**Comment by vzaliva** [comment]
not sure about curl. Same happening when I am opening this URL in Chrome browser (no `curl`)

**Comment by vzaliva** [comment]
it suddenly started working. If there is a limit to the number of requests per time interval which could have been causing this error?

**Comment by chubin** [comment]
wttr.in had an outage yesterday for a couple of hours, and this issue was caused exactly by it. It should not happen when all subsystems work properly

**Comment by vzaliva** [comment]
works now. thanks
