### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by Anteus** [chubin/wttr.in#482]
Doesn't handle for example swedish characters for example Å, Ä and Ö.

Does find Malmö but trunks the last char to a square. Doesn't find Kågeröd but does find Kagerod.

**Comment by chubin** [comment]
What exactly do you mean?

```
$ curl wttr.in/Kågeröd?0
Weather report: Kågeröd

    \  /       Partly cloudy
  _ /"".-.     27..28 °C
    \_(   ).   ↖ 20 km/h
    /(___(__)  10 km
               0.0 mm
```

**Comment by Anteus** [comment]
Sorry my bad was using the built in Windows 10 curl.
