### ISSUE TITLE
Prob. of precip. doesn't work with one line format

### ISSUE THREAD

**Issue by paraseba** [chubin/wttr.in#485]
Readme lists a %-modifier:

> o    Probability of Precipitation,

But doesn't seem to work.

### Steps to reproduce:
```
$ curl --compressed 'wttr.in/SFO?m&format=[%o]'
$ []
```

### Expected result
Show a probability between the brackets. 

I have tried several locations with the same result

**Comment by chubin** [comment]
Accepted

**Comment by chubin** [comment]
The problem here is that `chance-of-rain` make sense only for forecast,
but not for the current condition. This is related to #447

**Comment by SamantaTroper** [comment]
Would it make sense to remove it from the Readme until implementation? The docs make it seem like it's currently supported.

https://github.com/chubin/wttr.in/blame/master/README.md#L168

**Comment by chubin** [comment]
@SamantaTroper It is a good idea; done
