### ISSUE TITLE
Unknown location; please try $lat,$long

### ISSUE THREAD

**Issue by aksel** [chubin/wttr.in#498]
wttr.in seems to be down.

```
$ curl wttr.in
> Follow @igor_chubin for wttr.in updates

$ curl wttr.in/Copenhagen?format=%c+%t
> Unknown location; please try ~55.6867243,12.5700724
```

Seems to be same issue as in #454

**Comment by pkoziol** [comment]
If you go to https://wttr.in/ in you browser you will see:

> Sorry, we processed more than 1M requests today and we ran out of our datasource capacity.
We hope to solve the problem as soon as possible, so you can enjoy
your favourite weather service 24x365 even if it rains or snows.
>
> We will solve the problem as soon as possible.
> Follow @igor_chubin for the updates. 
>
> If you like to code (and you surely do), you can check the wttr.in repository
to see how the scalability problem is (not yet) solved.

which explains empty response for `curl wttr.in`

**Comment by aksel** [comment]
Thanks for the heads up!

**Comment by chubin** [comment]
Yes, the location problem yesterday was caused by the problem that @pkoziol metinoned. It should be fixed now, please test

**Comment by aksel** [comment]
It does indeed :smile: 

I use this extensively in my setup. Is there any way to support the project? Maybe a Patreon page or something?

**Comment by chubin** [comment]
No Patreon page, just keep using it; bug reporting/criticism is also helpful

**Comment by MyriaCore** [comment]
Not sure that this should be closed, I've been getting it on and off recently

![image](https://user-images.githubusercontent.com/35076430/89714614-f7c88e00-d96d-11ea-8aa1-0c3d80479fae.png)

**Comment by chubin** [comment]
@MyriaCore Yes it is ok that this one is closed; the problem occurs sometimes (when the load is peaking); the problem is known and referred by other open issues
