### ISSUE TITLE
Forecast pulled for Dallas, TX instead of Dallas, GA

### ISSUE THREAD

**Issue by johnlrussell** [chubin/wttr.in#509]
I live in Dallas (the good one), Georgia, USA. The forecast, however is pulled for Dallas, TX when querying wttr.in with no city selected. If I query wttr.in/Dallas+GA the correct forecast is pulled, however. I've confirmed that my IP address is correctly being identified as being in Dallas, GA.

**Comment by chubin** [comment]
Yes, it is a bug, I acknowledge this. It is #492
I close this issue as a duplicate.
Thank you very much for reporting, and please follow #492 for the fix
