### ISSUE TITLE
wttr.in down?

### ISSUE THREAD

**Issue by mdigga39** [chubin/wttr.in#512]
Running curl or connecting to browser via wttr.in or wttr.in/LOCATION results in the following:

`Follow @igor_chubin for wttr.in updates`

No weather is displayed

**Comment by chubin** [comment]
Yes, because of a misconfiguration today, we reached the upstream data source quota limit; the service will be back online in 6 hours

**Comment by mdigga39** [comment]
Gotcha! Appreciate the quick reply! 

V/R-
MDIGGA39

**Comment by TurnUpforButt** [comment]
@chubin Great to hear chubin, thank you for maintaining this useful piece of software! I have one question for you though: How do we combine the 'format:' flag with '-u' to get a string that is both formatted and in USCS? Thanks again!

**Comment by chubin** [comment]
The outage was fixed in a short time after it was reported. I close the issue and thank you for reporting!

@TurnUpforButt Have you tried to combine it like this (with `&u`)?
`'curl wttr.in/?format=1&u'`
(feel free to answer here, or open a new issue)
