### ISSUE TITLE
Is wttr.in down

### ISSUE THREAD

**Issue by maxdog0099** [chubin/wttr.in#513]
Hopefully its not something I'm doing on my side.  Accessing the wttr.in site gives a blank page except for the social links.  Trying to specify weather for a city lands me with Unknown location; please try ~42.926326,10.761625 no matter what city I specify using curl.

**Comment by Cordelya** [comment]
It's not just you - I'm getting similar issues.

**Comment by chubin** [comment]
It was fixed in a short time after you reported the outage. No outages/downtimes since that time. I close the issue and thank you for reporting!
