### ISSUE TITLE
Content-type of json responses is not correct

### ISSUE THREAD

**Issue by mjg123** [chubin/wttr.in#514]
Requests which specify `?format=j1` are returned as JSON in the body but with a `content-type` header of `text/plain` ([here](https://github.com/chubin/wttr.in/blob/master/lib/wttr_srv.py#L343)).

This should be `application/json`. Many services which consume APIs will not attempt to parse responses unless the content-type indicates that the payload is JSON.

**Comment by chubin** [comment]
It works now:

```
$ curl -I wttr.in/London?format=v1
HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Wed, 14 Oct 2020 05:21:34 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 2
Connection: keep-alive
Access-Control-Allow-Origin: *

$ curl -I wttr.in/London?format=j1
HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Wed, 14 Oct 2020 05:21:38 GMT
Content-Type: application/json
Content-Length: 45452
Connection: keep-alive
Access-Control-Allow-Origin: *
```

Thank you for reporting!
