### ISSUE TITLE
No translation for the top-line of forecast

### ISSUE THREAD

**Issue by dvmn-tasks** [chubin/wttr.in#520]
Fore some reason the top-line forecast is not translating.

My request: https://wttr.in/london?lang=ru

Response: 
![lond](https://user-images.githubusercontent.com/44063469/91552191-151cc680-e934-11ea-9b2d-aa3246502f80.png)

**Comment by chubin** [comment]
I suppose that the problem here is not with the first line, but with `Rain shower`; thank you for reporting, I will add it
