### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by 532910** [chubin/wttr.in#527]
```
% curl wttr.in/Moscow          

Follow @igor_chubin for wttr.in updates
% curl wttr.in/~Eiffel+Tower

Follow @igor_chubin for wttr.in updates
% curl wttr.in/@msu.ru


Follow @igor_chubin for wttr.in updates
% curl wttr.in/@github.com

Follow @igor_chubin for wttr.in updates
%
```

**Comment by BenSYZ** [comment]
Knowing from [http://wttr.in/Moscow.png](http://wttr.in/Moscow.png)

> Sorry, we are running out of queries to the weather service at the moment.
> Here is the weather report for the default city (just to show you what it looks like).
> We will get new queries as soon as possible.
> You can follow https://twitter.com/igor_chubin for the updates.


Check the [twitter](https://twitter.com/igor_chubin/status/1311648849652523009).

> wttr.in is experiencing an outage; it will be offline until 0:00UTC tonight; many apologies

**Comment by 532910** [comment]
![image](https://user-images.githubusercontent.com/14617699/94819546-1005d800-0408-11eb-8547-7ba63bac0f0c.png)

**Comment by BenSYZ** [comment]
This may be your network problem. 
<img src="https://user-images.githubusercontent.com/42512930/94824498-aef5f880-0437-11eb-8af4-7d3e3601663e.png" width="302" height="302" />

**Comment by chubin** [comment]
I am sorry for the outage; I hope the service will be back online at 0:00UTC.
I close this as a duplicate for #522

**Comment by 532910** [comment]
It was ff bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1665368

**Comment by 532910** [comment]
In fact it's hard to say unequivocally, as it's some kind of heisenbug and this happens from time to time, but I've not seen it on 81.0.2.
