### ISSUE TITLE
The website shows different weather than the terminal curl request

### ISSUE THREAD

**Issue by edowado** [chubin/wttr.in#529]
![web](https://user-images.githubusercontent.com/11145139/95106332-ea3e4300-0727-11eb-9812-8bae8024aeb1.png)
![terminal](https://user-images.githubusercontent.com/11145139/95106342-edd1ca00-0727-11eb-8b0a-6b257f32a898.png)

**Comment by chubin** [comment]
Yes, it is possible because of caching. If you want to switch the caching effect off, just append some neutral characters to the queries, for example `+++`:

https://wttr.in/London+++
```
curl https://wttr.in/London+++
```

I expect that in this case there should be no difference between the results.
Please test

**Comment by edowado** [comment]
I tested and works ok.
I think the problem was the url I was using..
On the browser:
wttr.in (Weather report: London, United Kingdom)
is different than
wttr.in/london (Weather report: london)
