### ISSUE TITLE
wttr.in out of datasource capacity

### ISSUE THREAD

**Issue by skip-** [chubin/wttr.in#53]
Love the service and the text weather!
Just found this project after installing LXLE.

I'm not sure what the datasource capacity is. Based on the error message on your webpage, it sounds like it could be 1M queries per day.

Doing some quick math, you can serve up 
- 11 different locations once per second for 24 hours
- 57 different locations once per 5 seconds for 24 hours

I'd be curious to see the traffic log and see how many different locations are being served and at what rate. If a lot of traffic comes from a few locations, caching either using srv.py or at the client could help. Weather doesn't change by the second usually, so it might be useful to cache weather for between 5 seconds and 5 minutes to reduce the number of queries sent to your datasource.

I may try to implement something like that given some time free after my day job :)

**Comment by skip-** [comment]
Please excuse the above if you did implement caching. I didn't see it when I read through srv.py but perhaps it is implemented in wego or some other dependency. 

I did go to worldweatheronline.com and found in their FAQ the following entry requesting that free API users cache requests in 15 minute intervals (even longer than I was thinking):

> **Is there a limit on the number of weather data requests per day for Free API users?**
> 
> Our free weather API users have a limit of 250 requests per day.
> 
> We also request the proper caching of data before new requests for same location are made within 15 minutes.

**Comment by chubin** [comment]
see also: #58

**Comment by alexellis** [comment]
Is there a rate limit on the public service?

**Comment by chubin** [comment]
@alexellis Yes, but it can be hardly reached. Why? Are you experiencing some problems currently?

**Comment by alexellis** [comment]
Curious how much it can be used by an individual user. 100 times? 1k times? 100k times?

I might accept it into the [OpenFaaS Function Store](https://github.com/openfaas/store/issues/53)

**Comment by chubin** [comment]
@alexellis currently we have the following limits (per IP):
```
# (minute, hour, day) limitations:
QUERY_LIMITS = (300, 3600, 24*3600)
```
but they will be increased soon

I've just gone through the issue you've mentioned, I would like to make a couple of remarks:

1. wttr.in supports configurable queries (/:help for that), you should consider making them configurable; via some additional function parameters etc;
2. wttr.in is translated into 60 languages, is should be configurable too;
3. wttr.in supports single line mode with many addtional data that can't be seen in the main mode (see: `curl wttr.in/?format=3 for example`)
4. Several new cool features (output formats) will be added soon

**Comment by chubin** [comment]
The query limits are removed now.
