### ISSUE TITLE
is it working?

### ISSUE THREAD

**Issue by neil-wwt** [chubin/wttr.in#531]
Both in the browser and at the CLI I'm not getting any weather info.

![Screen Shot 2020-10-07 at 15 35 57](https://user-images.githubusercontent.com/22230865/95390574-d5da8180-08b2-11eb-9cf1-d03033b1bf8f.png)

![Screen Shot 2020-10-07 at 15 36 57](https://user-images.githubusercontent.com/22230865/95390639-f4407d00-08b2-11eb-9724-b07132f20762.png)

**Comment by jack-faller** [comment]
same here

**Comment by chubin** [comment]
It was done for couple of hours four days ago, but it is running since that.

https://twitter.com/igor_chubin/status/1311648849652523009
