### ISSUE TITLE
wrong temperature or wrong state

### ISSUE THREAD

**Issue by vzaliva** [chubin/wttr.in#536]
I am in Saratoga, CA. It is +25C outside right now according to my thermometer. Hower wttr reports +1C!

```
$ curl -s 'wttr.in?format=3&m'
Saratoga, United States: ☀️ +1°C
```

It looks more like the temperature in Saratoga, NY.

**Comment by chubin** [comment]
Yes, it is a bug. It is #492 
You reported it a couple of months ago, but it is still open.
I close this one as a duplicate
