### ISSUE TITLE
Location depends on translation

### ISSUE THREAD

**Issue by 532910** [chubin/wttr.in#538]
```
% curl -s https://wttr.in/Санкт-Петербург | grep Location
Location: Санкт-Петербург [59.935531,30.327029]
```
```
% curl -s https://wttr.in/Saint-Petersburg | grep Location
Location: Санкт-Петербург, Центральный район, Санкт-Петербург, Северо-Западный федеральный округ, 190000, РФ [59.9387318,30.3162286]
```

**Comment by chubin** [comment]
It is possible, but the difference is minimal and there will be no difference in forecast in this case. You can safely round the coordinates to the second (and actually even to the first) digit after the decimal point:

[59.9, 30.3]

Anyway, there is nothing to be fixed here, so I close the issue (theoretically there could be some other locations, that resolve to fully different coordinates; such particular locations must be rewritten to the canonical ones via aliases).

**Comment by 532910** [comment]
I wonder why it differs?

**Comment by chubin** [comment]
It is possible, because it is a community driven dataset (we use openstreetmap dataset for location resolution), and so it is possible that the coordinates in entries slightly differ
