### ISSUE TITLE
Different results for same IP address using different methods

### ISSUE THREAD

**Issue by gregdan3** [chubin/wttr.in#543]
# Demonstration
This is what I see on the first few lines when I `curl wttr.in`, and this is the expected result that matches my local weather and other services:
```
Weather report: Birmingham, United States

      \   /     Sunny
       .-.      64 °F          
    ― (   ) ―   ↘ 0 mph        
       `-’      9 mi           
      /   \     0.0 in         
```

This is what I see when I use a format string and no location, but from the same IP address:
```
curl -s 'wttr.in/?format=%c+%l:+%C+%t+%w+%h'

☀ Birmingham, United States: Sunny +58°F ↘6mph 30%
```

With the same format string and an explicit location specifying the country, but not the state:
```
curl -s 'wttr.in/Birmingham,US?format=%c+%l:+%C+%t+%w+%h'

☀ Birmingham,US: Sunny +58°F ↘6mph 30%
```

With the same format string and an explicit location specifying the state, but not the country (this produces expected behavior)
```
curl -s 'wttr.in/Birmingham,AL?format=%c+%l:+%C+%t+%w+%h'
☀ Birmingham,AL: Sunny +64°F ↓0mph 23%
```

With the same format string and specifying city, state, country (expected behavior):
```
curl -s 'wttr.in/Birmingham,AL,US?format=%c+%l:+%C+%t+%w+%h'
☀ Birmingham,AL,US: Sunny +64°F ↓0mph 23%
```

# Expected behavior
`curl -s 'wttr.in/?format=%c+%l:+%C+%t+%w+%h'` should produce the same results as `curl -s 'wttr.in/Birmingham,AL,US?format=%c+%l:+%C+%t+%w+%h'` while using an IP that is in Birmingham,AL,US, but this is not the case.

`curl -s 'wttr.in/?format=%c+%l:+%C+%t+%w+%h'` and `curl -s wttr.in` should produce congruent results for the current weather status, but they do not.

**Comment by chubin** [comment]
Yes, this is the problem that we have in #492 and that must be closed with #542

**Comment by gregdan3** [comment]
I'm thus far convinced that this issue is unrelated to the missing province, which is why I posted this; the location derived appears dependent on the method used to get weather information. There's a correlating effect with the province, but I provided the different location strings as comparisons to what the behavior should be.

In short, somehow, `wttr.in` itself has the correction location, but providing a format string changes the location `wttr.in` derives, even with the same IP address.

**Comment by chubin** [comment]
You suppose, that the v1 view (default view) provides data for some other location, than the one-line output?

That's how they are resolved:

```
$ curl -ks localhost:8004/Birmingham,AL,US | jq .address
"Birmingham, Jefferson County, Alabama, United States of America"
$ curl -ks localhost:8004/Birmingham,AL | jq .address
"Birmingham, Jefferson County, Alabama, United States of America"
$ curl -ks localhost:8004/Birmingham,US | jq .address
"Birmingham, Jefferson County, Alabama, United States of America"
igor@wttr:~$ curl -ks localhost:8004/Birmingham | jq .address
"Birmingham, West Midlands Combined Authority, West Midlands, England, United Kingdom"
```

If you send me three octects of your IP address, we can check what
is the cache entry for the IP address

**Comment by chubin** [comment]
Also, you can make queries for IP-addresses explicitly:

```
curl wttr.in/@1.1.1.1
curl wttr.in/@1.1.1.1?format=3
```
