### ISSUE TITLE
Wrong spelling

### ISSUE THREAD

**Issue by inchw0rm** [chubin/wttr.in#547]
It says "Sunnyn" instead of "Sunny" in certain circumstances.

![image](https://user-images.githubusercontent.com/45134902/99538275-041ca800-29ad-11eb-83a7-84ea258fddfa.png)

May I send an "ultimate open source contribution" PR fixing this? :D

**Comment by chubin** [comment]
@inchw0rm thank you for reporting this, but I don't know how this could happen.
If it were a translated version, then it would be clear. In this case we get the info directly from the data source, and so the problem should be on their side.

If the problem persists, we can add a "patching layer" on our side, which will fix error in weather conditions names (like here)

**Comment by inchw0rm** [comment]
@chubin do you think I can still send a PR?

**Comment by chubin** [comment]
Sure

**Comment by neophytte** [comment]
I've also seen this on the word "partial" being spelt with a random f in the middle as "Parftial" as per the image:

[Image](url https://imgur.com/a/TSW8L4a)

I don't have the smarts to fix this, so hope someone else can!!

**Comment by chubin** [comment]
@neophytte Thank you for reporting this. It seems we really need a solution here, as there are quite a few errors in the upstream weather condition names.
