### ISSUE TITLE
help file with unsuitable strings

### ISSUE THREAD

**Issue by Danfro** [chubin/wttr.in#549]
Help file does look like [this](https://github.com/chubin/wttr.in/blob/master/share/help.txt#L16):
```
Special locations:

    /moon                   # Moon phase (add ,+US or ,+France for these cities)
    /moon@2016-10-25        # Moon phase for the date (@2016-10-25)
```
I am quite sure this does not want to be "special locations" but something moon related, right?

**Comment by chubin** [comment]
Special queries would be better, right?

**Comment by Danfro** [comment]
Either this if you plan to add more queries there. Or just "Moon phase" or "Moon phase information".

**Comment by chubin** [comment]
Thank you! Fixed now
