### ISSUE TITLE
First weather widget not translated for fr

### ISSUE THREAD

**Issue by thierrybo** [chubin/wttr.in#552]
Hi,

as you can see below,
https://i.imgur.com/os8LAAI.png
the text of the first widget is "Rain shower" whereas all other text is translated.

**Comment by gregdan3** [comment]
This is a typo in the translation map text file. The string `Rain Shower` is present and translated to `Averses`, but `Rain shower` is not present.


The following will fix the issue, present in `wttr.in/share/translations/fr.txt`:
```diff
--- fr.txt	2020-12-29 09:55:27.336187194 -0600
+++ fr.txt	2020-12-29 09:54:52.366381577 -0600
@@ -1,6 +1,7 @@
 : Pluie                                            : Rain
 : Pluie légère, Averses                            : Light Rain, Rain Shower
 : Averses                                          : Rain Shower
+: Averses                                          : Rain shower
 113 : Temps clair                                  : Clear
 113 : Ensoleillé                                   : Sunny
 116 : Partiellement couvert                        : Partly cloudy
```

`patch < fr.txt.patch`, where `fr.txt.patch` has the content of the above diff.

**Comment by chubin** [comment]
I made it case-insensitive, so it should work now
