### ISSUE TITLE
No translation for the second-line of forecast

### ISSUE THREAD

**Issue by keinen87** [chubin/wttr.in#554]
Fore some reason the second-line forecast is not translating.

My request: http://wttr.in/Кельн?lang=ru

Response:
![image](https://user-images.githubusercontent.com/14131872/102319097-d028a880-3f93-11eb-8fda-e4381c621c19.png)

My request: http://wttr.in/Москва?lang=ru

Response:
![image](https://user-images.githubusercontent.com/14131872/102319347-2990d780-3f94-11eb-8341-405db0332f41.png)

My request: http://wttr.in/Калининград?lang=ru

Response:
![image](https://user-images.githubusercontent.com/14131872/102319483-62c94780-3f94-11eb-9a5a-2252d19f94a0.png)

My request: http://wttr.in/Магадан?lang=ru

Response:
![image](https://user-images.githubusercontent.com/14131872/102319598-999f5d80-3f94-11eb-9027-c676c593118c.png)

My request: http://wttr.in/Краснодар?lang=ru

Response:
![image](https://user-images.githubusercontent.com/14131872/102319904-01ee3f00-3f95-11eb-8ce0-a695056c77e6.png)

My request: http://wttr.in/Магадан?lang=ru

Response:
![image](https://user-images.githubusercontent.com/14131872/102320284-83de6800-3f95-11eb-9302-caf556c7ad7f.png)

My request: http://wttr.in/Ставрополь?lang=ru

Response:
![image](https://user-images.githubusercontent.com/14131872/102320558-e33c7800-3f95-11eb-847b-31d955d2a941.png)

My request: http://wttr.in/Дербент?lang=ru

Response:
![image](https://user-images.githubusercontent.com/14131872/102320734-27c81380-3f96-11eb-890c-1ba374505458.png)

My request: http://wttr.in/Атырау?lang=ru

Response:
![image](https://user-images.githubusercontent.com/14131872/102320943-6eb60900-3f96-11eb-91c3-21685c85c419.png)

**Comment by gregdan3** [comment]
All of these strings have a common problem: they are not present in the `ru.txt` translation file. Most of these do have partial translations in the file, but since these are multiple-weather strings (separated by a comma), they are not translated.

Can you provide translations for those strings? Or alternatively, is the google translate translation sufficient?

If you do provide translations, the preferred format is this:

```
: [translated string] : [Original Text exactly] : 
```

**Comment by chubin** [comment]
The main problem here (at least what I saw from the posted screenshots) was
that the comma-separated terms were not translated, and some terms were missing indeed.
I've translated them into German and Russian, and some of them into French, but I wan not sure about French for things like  `Low drifting snow` (posted them to #324).

@keinen87 Nurbek, thank you for the bug report; I hope it is fixed now; if you see it again, please let us know.

**Comment by keinen87** [comment]
![image](https://user-images.githubusercontent.com/14131872/104186465-e2c9bc80-542f-11eb-8495-c21b1de8fd60.png)

**Comment by chubin** [comment]
@keinen87 I've added the translations. Thank you for reporting!

**Comment by chubin** [comment]
Closing this in favor of #535
