### ISSUE TITLE
curl wttr.in/city?format=3 does not work on Mac's with apple silicon

### ISSUE THREAD

**Issue by TheMartian32** [chubin/wttr.in#556]
Hi!

Intro:
So I wanted a way to check the weather for my location through my terminal and wttr.in has been a great way to do this.

Issue:
However, I only want one line of info, not the whole thing. But when I went down and looked for that option, it did not work on my machine. ZSH was giving me an error telling me that the command was not found. I'm not sure if this is due to the machine I'm running this on ( apple silicon mac ), or if it just doesn't work. 

Outro:
Anyway, just thought I'd bring it to your attention.

**Comment by chubin** [comment]
Just quote the query or escape the `?` in the query with `\`

**Comment by TheMartian32** [comment]
@chubin Thanks! Escaping the query didn't work, however quoting it did.

**Comment by chubin** [comment]
No, escaping should work too. How are you doing it?

```
$ zsh
% curl wttr.in/Nuremberg\?format=3
Nuremberg: 🌦 +11°C
```

**Comment by TheMartian32** [comment]
Sorry, had a typo when I was escaping the command. Thanks again!
