### ISSUE TITLE
Wrong airport labelled as YYZ

### ISSUE THREAD

**Issue by korolrom** [chubin/wttr.in#557]
`curl wttr.in/yyz` returns the weather at 
`Location: Airport, Queen Street East, Peel Region, Ontario, L6T 5P9, Canada [43.7438133,-79.6951011]`.
The Pearson internaitonal Airport (much larger than the one returned above) is actually at:
`6301 Silver Dart Dr, Mississauga, ON L5P 1B2, Canada [43.677034, -79.624325]`.

**Comment by chubin** [comment]
Thank you for the heads up! I've added a workaround now, so YYZ should resolve properly.
If the problem will persist with some other airport codes, we will search for a generalized solution here
