### ISSUE TITLE
"Light rain and snow" not translated in French

### ISSUE THREAD

**Issue by glostis** [chubin/wttr.in#561]
Hi,

Thanks for this wonderful service!

I noticed today that the phrase "Light rain and snow" is not translated to French, and therefore shows in English - see attached screenshot.

![Screenshot from 2021-01-06 09-23-44](https://user-images.githubusercontent.com/25295717/103746580-992d3c00-5001-11eb-9428-90885dc88081.png)

I am not very familiar with the translation process: since it is part of the longer phrase "Light rain and snow, Mist", should a translation for the full phrase be added to `fr.txt`, or only a translation for "Light rain and snow" will suffice?

Also on a side-note, the weather provider has been predicting heavy snowfall over Paris for the past 3 days, but a single snowflake has yet to be seen :) But I know that is beyond the scope of this project and there is nothing you can do about that.

**Comment by glostis** [comment]
Hi,

I'm encountering the same issue with a slightly different phrase this time:

```
Light drizzle and rain, Brumeux
```

**Comment by chubin** [comment]
> since it is part of the longer phrase "Light rain and snow, Mist", should a translation for the full phrase be added to fr.txt, or only a translation for "Light rain and snow" will suffice?

Only `Light rain and snow` will suffice.

How would you translate it:

* `Pluie légère avec neige`
?

> the weather provider has been predicting heavy snowfall over Paris for the past 3 days, but a single snowflake has yet to be seen

Yes, our data source is slightly off; we are working on that. Hopefully, we will fix this problem in future (see #526 for example)

**Comment by chubin** [comment]
I close it as no feedback followed; please comment if you think there is something to do here still
