### ISSUE TITLE
v2 temperature graph has been way off for a couple of weeks

### ISSUE THREAD

**Issue by marlonn** [chubin/wttr.in#562]
Since some point last month, the v2 temperature has consistently been about 4° too low for my location. Check out this screenshot and compare the graph to the display temperature in the "Weather" line:

![2021-01-06-173912_595x734_scrot](https://user-images.githubusercontent.com/19227239/103795597-1676a200-503e-11eb-9d2e-ebaa70b748e1.png)

(data obtained with terminal command `curl v2.wttr.in/hannover` in lxterminal)

**Comment by chubin** [comment]
I switched it from `FeelsLike` to the real temperature, but it still fully off.
Unfortunately, the data from our data source seems to be really bad (though quite expensive). I think it is slowly the time to think about the support of other data sources.

**Comment by marlonn** [comment]
Thanks! At least the graphic is internally consistent now, which is certainly an improvement. I'll close the issue.
