### ISSUE TITLE
Text output

### ISSUE THREAD

**Issue by Mystik01** [chubin/wttr.in#563]
Hi, 
If I make a get request to the api in javascript using request,  get the html of the site.
Is it possible just to get the text of it? I'm not sure how to parse the html,

My qustion is the same as this: https://github.com/chubin/wttr.in/issues/197#issue-323466573

**Comment by chubin** [comment]
@Mystik01 I am not sure that your question was exactly the same as #197.

If you want to have the response in the plain-text form, without ANSI, and without HTML,
you can specify `A` (force ANSI) and `T` (text) options, like this:

`wttr.in/Parist?AT`

**Comment by Mystik01** [comment]
Yeah, I worked that out which is why I closed it back then. But thanks
