### ISSUE TITLE
Timezone of location queried

### ISSUE THREAD

**Issue by opeRaptor** [chubin/wttr.in#566]
First of all, thank you so much for your amazing work! I am really enjoying working with wttr.in.

Would it be possible to include the timezone of the location queried to the dataset? Perhaps as a offset from UTC/GMT.

This would be especially useful in conjunction with the astronomy data that is returned in the local timezone.

Perhaps something like this:

    m    Moonphase 🌑🌒🌓🌔🌕🌖🌗🌘,
    D    Dawn*,
    S    Sunrise*,
    z    Zenith*,
    s    Sunset*,
    d    Dusk*.
    t    Timezone UTC/GMT offset*.

    (*times are shown in the local timezone)

Thank you your consideration.

**Comment by chubin** [comment]
Have you seen `curl v2.wttr.in`? We have timezone info there; do you want to have the same info as one-line format output field, right?

**Comment by opeRaptor** [comment]
Sorry for the delayed reply @chubin Yes, that would be ideal!
Something like v2.wttr.in/?format="%S+%s+%m+%T" where T is the UTC/GMT offset? Something along these lines.

Would it be possible to have all the new data of V2 added to the one-line format? That would be grand!
Thank you again for your amazing work!

**Comment by chubin** [comment]
We already have `t` for temperature, but it would be possible to add these two:

* `T` current local time
* `z` timezone of the location

What do you think?

**Comment by chubin** [comment]
I added support of these two format modifiers, `%T` and `%Z`.
That is how it works:

```
$ curl wttr.in/Katmandu?format="%T\n"
15:12:09+0545
$ curl wttr.in/Katmandu?format="%Z\n"
Asia/Kathmandu
```

Responses are being cached on the server side,
so to bypass the cache and see the real local time, currently you need to add the `nonce` URL parameter:

```
$ curl wttr.in/Katmandu?format="%T\n"\&nonce=$RANDOM
15:12:09+0545
```

**Comment by opeRaptor** [comment]
Sorry for the delay, this is excellent and comes in very useful! Thank you.
