### ISSUE TITLE
Translation is not loaded

### ISSUE THREAD

**Issue by Skillkiller** [chubin/wttr.in#568]
Hello,
I have loaded here the weather information for Weinheim. In the second line you can see that this text was not translated.
But in the translation file there is also no translation for this weather.
![grafik](https://user-images.githubusercontent.com/18444809/104876164-6830fd80-5957-11eb-9822-c091ee25cf60.png)

Is it possible to add a translation for this weather as well?
"Light drizzle and rain" -> "Light drizzle and rain".

**Comment by chubin** [comment]
Ja, das stimmt; wie würdest du `Light drizzle and rain` übersetzen?
`Leichter Nieselregen und Regen`?

**Comment by chubin** [comment]
I've added the translation; thank you for reporting; please test and evtl. close

**Comment by Skillkiller** [comment]
Yes, that's how I would translate it.
Testing is of course difficult, for this the weather had to occur once again.
But I think the problem was solved with it.
Thank you
