### ISSUE TITLE
Ошибка при выводе погоды 

### ISSUE THREAD

**Issue by BLRrubik** [chubin/wttr.in#572]
Когда я пытаюсь получить погоду на ubuntu через curl wttr.in/{city} , то выдается ошибка 

`Sorry, we are running out of queries to the weather service at the moment.
Here is the weather report for the default city (just to show you what it looks like).
We will get new queries as soon as possible.
You can follow https://twitter.com/igor_chubin for the updates.`

Хотя через среду разработки все проходит гладко.

**Comment by chubin** [comment]
Странно; всё сейчас должно работать из терминала нормально.
Вы можете проверить такие вещи:

1. Как работает в браузере
2. Из терминала: не работет только на определённый город или вообще ни на какие не рабоет
3. Можно ли прислать скриншот с ошибкой; может быть там какая-то незаметная мелочь

**Comment by BLRrubik** [comment]
В браузере работает стабильно, однако как только я пытаюсь запустить на ubuntu возникает ошибка

![image](https://user-images.githubusercontent.com/60672771/106927058-d41ab080-6722-11eb-8752-4e6c041b965b.png)
![image](https://user-images.githubusercontent.com/60672771/106927183-f9a7ba00-6722-11eb-8907-855525cc7aed.png)

**Comment by chubin** [comment]
Попробуйте, пожалуйста ещё раз? Сейчас должно быть лучше

**Comment by BLRrubik** [comment]
Заработало, спасибо
