### ISSUE TITLE
No Color option

### ISSUE THREAD

**Issue by Ramiferous** [chubin/wttr.in#573]
Any chance of getting a no colour option for the output. This really only bothers me with the Moon phase output, but in general a no colour option would be awesome. 

I have tried the `format?I` option which inverts the colours but this still doesn't work with my colour scheme.

**Comment by chubin** [comment]
What about `?T`?

**Comment by chubin** [comment]
![Moon_TF](https://user-images.githubusercontent.com/3875145/106990961-97c47000-6775-11eb-8b5d-07525a66e16d.png)
![Moon_TF](https://wttr.in/Moon_TF.png)

**Comment by chubin** [comment]
Interesting. I've just learnt that you can't use images in comments
posted by mail. Really strange

![Moon_TF](https://user-images.githubusercontent.com/3875145/106990961-97c47000-6775-11eb-8b5d-07525a66e16d.png)

**Comment by Ramiferous** [comment]
Thanks, I'm sorry, I didn't actually see that option!
