### ISSUE TITLE
Option not working

### ISSUE THREAD

**Issue by shinokada** [chubin/wttr.in#575]
According to `curl wttr.in/:help`,

```
...
Options can be combined:

    /Paris?0pq
```

But when I run this, it returns no matches.

```
❯ curl wttr.in/Tokyo?0pq
zsh: no matches found: wttr.in/Tokyo?0pq
```

I tried other options, but none of them working.

Is it a bug?

**Comment by chubin** [comment]
No, it is not a bug; in zsh you should escape special characters like `?`.
So please try `curl wttr.in/Tokyo\?0pq` or `curl 'wttr.in/Tokyo?0pq'` instead; it will work.
