### ISSUE TITLE
wttr.in down?

### ISSUE THREAD

**Issue by 1ctinus** [chubin/wttr.in#577]
All it shows are the embeded links on the main page. for locations, it says unknown location; please try (COORDS). I know somebody reported it 2 days ago, but It just started sometime today,

**Comment by 1ctinus** [comment]
Going on 
https://v3.wttr.in/Tabasco.png
I see, 
"500 Internal Server Error"
"Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

**Comment by chubin** [comment]
https://twitter.com/igor_chubin/status/1361706329887375361

Yes, it will be down for several hours today

**Comment by 1ctinus** [comment]
Looks Back Online :)
