### ISSUE TITLE
Dockerfile out of date

### ISSUE THREAD

**Issue by namidairo** [chubin/wttr.in#578]
The golang:1-alpine image referenced in the Dockerfile is now based on Alpine Linux 3.13, which does not have llvm9 packages.

Users may either target golang:1-alpine3.12 or switch the packages to llvm10 (don't forget to set the LLVM_CONFIG env variable to `/usr/bin/llvm-config`).

**Comment by chubin** [comment]
Thank you Richard. Fixed
