### ISSUE TITLE
Weather within Tmux statusbar.

### ISSUE THREAD

**Issue by Dan1jel** [chubin/wttr.in#579]
i tried to put weather within tmux statusbar with `"$WEATHER ..."` but when i do, my statusbar gets an extra line, the last text on my statisbar jump to one row (see attatchment). so so i tried with only `#(curl wttr.in/Sollentuna?format=3)` and thats the same thing.. When i remove the Weather, everything gets back to normal.

is this something within the code (curl wttr.in/Sollentuna?format=3) that makes my Statusbar Jump one line? Because of all the stuff i have tried to add, the line never jumps except when i add the weather. 
![error_tmux](https://user-images.githubusercontent.com/4266424/108165611-22508c00-70f3-11eb-8678-16c37d25329d.png)

**Comment by ljonsson** [comment]
Have you tried without the weather symbol, e.g. `wttr.in?format='%l+%t+%h'` ?  I have a similar issue, but with an extraneous space (that red space at the end, below), not a new line.  Dropping the weather symbols makes it work every time, but since it's only a space I'm willing to live with it.

<img width="533" alt="image" src="https://user-images.githubusercontent.com/3597419/108198530-bd446880-70e9-11eb-8f01-414757a26ae6.png">

**Comment by Dan1jel** [comment]
> Have you tried without the weather symbol, e.g. `wttr.in?format='%l+%t+%h'` ?  I have a similar issue, but with an extraneous space (that red space at the end, below), not a new line.  Dropping the weather symbols makes it work every time, but since it's only a space I'm willing to live with it.
> 
> <img width="533" alt="image" src="https://user-images.githubusercontent.com/3597419/108198530-bd446880-70e9-11eb-8f01-414757a26ae6.png">
> 

Wierd that i get a new line and you get a space instead... Can't you put a colour on that space so it's invisible?

I did try without the icon and that works flawless. To bad tho because I would like that icon... But now it works as it should at least. Thanks for the tip.

**Comment by chubin** [comment]
Sorry for the late comment and thank you for the issue.

The problem here is that your terminal and your tmux have different understanding on the emoji width.
One of them thinks that it is 1, and one of them that it is 2, and the discrepancy occurs because of that.

Actually, there is not so much to fix (exceptthe terminal), but if you are curious you can prove my conjecture easily:

1. just save the emoji in a file, and `cat` this file instead of curling wttr.in. You will see that the problem is there.

Additional tests:

2. Use other terminals and check if the problem occurs there too. Different terminals have different notions of emojis width.


Also, JFYI, how new lines are handled (not related to your problems at all, but useful to know):

```
wttr.in one line output does not contain new line, when the %-notation is used,
but does contain it when preconfigured format (1,2,3 etc.) are used.
To specify newline in the output for the %-notation, one should use \n and single
quotes when doing a query from the shell.
```

**Comment by Dan1jel** [comment]
> Sorry for the late comment and thank you for the issue.
> 
> The problem here is that your terminal and your tmux have different understanding on the emoji width.
> One of them thinks that it is 1, and one of them that it is 2, and the discrepancy occurs because of that.
> 
> Actually, there is not so much to fix (exceptthe terminal), but if you are curious you can prove my conjecture easily:
> 
> 1. just save the emoji in a file, and `cat` this file instead of curling wttr.in. You will see that the problem is there.
> 
> Additional tests:
> 
> 1. Use other terminals and check if the problem occurs there too. Different terminals have different notions of emojis width.
> 
> Also, JFYI, how new lines are handled (not related to your problems at all, but useful to know):
> 
> ```
> wttr.in one line output does not contain new line, when the %-notation is used,
> but does contain it when preconfigured format (1,2,3 etc.) are used.
> To specify newline in the output for the %-notation, one should use \n and single
> quotes when doing a query from the shell.
> ```

This is what i use if anyone is wondering -> `#(curl wttr.in/Sollentuna?format='%%C,+%%t+(feels+like+%%f)+%%h')`

I tought that it was the "emoji" fault, but i can live without it. I think its great that this wttr exist and works as it should. HUGE thanks for creating this service and all the hard work you do.

**Comment by ljonsson** [comment]
I upgraded to tmux 3.1c (from 3.1b I think) a week or so ago and haven't had an issue since

**Comment by Dan1jel** [comment]
> I upgraded to tmux 3.1c (from 3.1b I think) a week or so ago and haven't had an issue since

well i use tmux on my raspberry and latest version via `apt update` is 2.8. But that is great news if this issue is gone with a newer version of tmux.

**Comment by chubin** [comment]
I think you can try to build it from source. It is trivial to build it.
From the external dependencies, libevent is the only one it needs,
if I remember it right.

**Comment by ckt114** [comment]
I'm using Tmux version 3.3a with Kitty 0.26.5 and still having this problem. Tried Alacritty or iTerm2 and they work fine so it's definitely Kitty for me but Kitty is my preferred terminal. Anyone have any solution for this?

**Comment by codebysandwich** [comment]
> I'm using Tmux version 3.3a with Kitty 0.26.5 and still having this problem. Tried Alacritty or iTerm2 and they work fine so it's definitely Kitty for me but Kitty is my preferred terminal. Anyone have any solution for this?

https://github.com/kovidgoyal/kitty/issues/5957

the same question, whether other tricks?

**Comment by Yorisoft** [comment]
Bump. 
Would be great to be able to use icons with this plugin.


Also thank you Dan1jel for the help!

**Comment by chubin** [comment]
Have you checked ghostty by the way? If yes, do you experience the same problem with it as well?
