### ISSUE TITLE
darksky.net

### ISSUE THREAD

**Issue by alucard0134** [chubin/wttr.in#58]
With the original backend making api's pay only I feel throwing the suggesting of implementing dark sky would be a good option.

The only thing that would be needed is to have it push coords instead of a city name, but will prove unreliable when it comes to accurate locations

**Comment by chubin** [comment]
see also #9 (marked #58 as duplicate)

**Comment by superusercode** [comment]
https://blog.darksky.net/ darksky api will no longer be available to the public and this issue should probably be closed.

**Comment by chubin** [comment]
Yes, you are right. I know it since march 2020, but what is still relevant, is that we need support for different data sources. But we still have #9, so this one can be closed. Thank you @superusercode
