### ISSUE TITLE
Unclear meaning of "precipitation"

### ISSUE THREAD

**Issue by donholgo** [chubin/wttr.in#582]
It is not clear what the precipitation amount in the default output or given with the `%p` format option refers to, i.e. over what time it has been measured: precipitation in the last hour? several hours? day? This should at least be made clear in the documentation for `%p`, perhaps it would also make sense to change the unit in the output accordingly.

**Comment by chubin** [comment]
It is precipitation in 3 hours. It is a good point that it must be added to documentation

**Comment by chubin** [comment]
I close it as no feedback followed; please comment if you think there is something to do here still
