### ISSUE TITLE
libfetch support

### ISSUE THREAD

**Issue by herrhotzenplotz** [chubin/wttr.in#586]
FreeBSD doesn't come with curl by default. Instead, it gives you [fetch](https://www.freebsd.org/cgi/man.cgi?query=fetch&apropos=0&sektion=0&manpath=FreeBSD+12.2-RELEASE+and+Ports&arch=default&format=html) as an equivalent utility which is capable of all the same things as curl.

It produces the following `User-Agent` string:
```
User-Agent: fetch libfetch/2.0
```

A workaround the issue, that it dumps out HTML by default, is to manually set the User-Agent like:

```
$ fetch --user-agent=cURL -o - https://wttr.in/Dublin 2>/dev/null
```

However, this is inconvenient and annoying to use.
I suggest adding support for that, as it appears to me, that it is only one entry in an array at https://github.com/chubin/wttr.in/blob/a35a0f678cf56afd7d854ff33f0aa453c4d48ed6/lib/globals.py#L75
I'm not sure about this, so please correct me if I am wrong.

**Comment by chubin** [comment]
Yes, you are right, and we even have it already in cheat.sh.
Now I added it here too. Please test

**Comment by herrhotzenplotz** [comment]
@chubin Thank you very much, now it works! I'll close the issue.
