### ISSUE TITLE
Location problem, Isfahan is a city of Iran not Afghanistan

### ISSUE THREAD

**Issue by hypermit** [chubin/wttr.in#59]
Hi,
When I try to see Isfahan weather, the output return Afghanistan country instead of Iran.

hypermit@hp ~> curl wttr.in/isfahan
Weather for City: Isfahan, Afghanistan

               Blowing Widespread Dust
      .--.     10 – 13 °C     
   .-(    ).   → 43 km/h      
  (___.__)__)  3 km           
               0.0 mm

**Comment by chubin** [comment]
You can try 
`wttr.in/Isfahan,Iran`.

That will work.
Or do you suggest to show Isfahan,Iran by default?

**Comment by hypermit** [comment]
Yes, I'm suggesting to show Isfahan, Iran by default. Because Isfahan is a city of Iran.
