### ISSUE TITLE
How are you grabbing location of request?

### ISSUE THREAD

**Issue by lodenrogue** [chubin/wttr.in#595]
Hi, just a question. How are you grabbing the geo location of the request?

**Comment by chubin** [comment]
Hi! IP based

**Comment by lodenrogue** [comment]
Can you point me to where in the code you're doing this? I need something similar for my project

**Comment by chubin** [comment]
This:

https://github.com/chubin/wttr.in/blob/master/lib/location.py

The code uses several data sources, included paid ones,
and it is pretty complicated for such a trivial task like resolution of IP-address to GPS coordinates.
You don't really need it, if you don't plan to handle tens of millions queries.

Feel free to use wttr.in for IP to address resolution.
You can do something like this:

```
$ curl -ks wttr.in/@1.1.1.1?format=j1 | jq -r '.nearest_area[0] | [.latitude,.longitude]'
[
  "22.350",
  "114.183"
]
```

Ping me if you need a special API call for that.

**Comment by lodenrogue** [comment]
Thanks! I appreciate it!
