### ISSUE TITLE
iterm2 IIP for v3?

### ISSUE THREAD

**Issue by davesgonechina** [chubin/wttr.in#596]
The documentation states that v3.wttr.in supports iTerm2/IIP on MacOS X, but `curl v3.wttr.in/Bayern.iip` returns the `We are working on the text-based weather report view` message. The message and README only provides examples for Sixel protocol images, am I using the wrong argument for IIP?

**Comment by chubin** [comment]
Please try: `curl v3.wttr.in/Bayern.it2` instead

**Comment by davesgonechina** [comment]
Works, thanks!
