### ISSUE TITLE
Differing weather results for the same location

### ISSUE THREAD

**Issue by user98765446** [chubin/wttr.in#597]
I am getting different results when requesting different formats and I am confused as to whether I am making the wrong assumption regarding the time?

Using the following command (10pm): curl wttr.in/London

I get:
(the sun?)
Clear
+6(3)  °C
← 19 km/h
10 km
0.0 mm

(followed by a forecast for the next few days -- as expected)

BUT, when I use this command: curl wttr.in/London\?format=3

I get: 
London: ☀️ +9°C

I assume that these commands should both provide the current weather. Am I reading this wrongly?

**Comment by chubin** [comment]
It may happen because of caching. Could you please add + or ++ after London to the first and to the second query?

**Comment by user98765446** [comment]
Thanks @chubin. It looks like you are right. Adding ++ to the query after London just produced a consistent +6°C.

I assume adding ++ is only a temporary solution?

Is there a way to avoid caching in the long term?

For example, is it possible to get accurate results if someone took several readings in a day (and be sure that wttr is not caching)?

**Comment by chubin** [comment]
Yes, you can append `nonce=$RANDOM` (if you are in shell) to the query:
```
curl wttr.in/London?nonce=$RANDOM
```

**Comment by user98765446** [comment]
Thank you. Could you tell me, can the same technique be used to fix caching in this circumstance? I haven't been successful in appending nonce=$RANDOM

curl -s 'wttr.in/london+\?format=+Condition:+%C\n+Humidity:+%h\n+Temperature:+%t\n+Feels+like:+%f\n+Precipitation:+%p\n+Wind:+%w\n+Pressure(hPa):+%P\n+Moonphase:+%m\n'

**Comment by chubin** [comment]
Yes, you can do it like this:

```
curl -s 'wttr.in/london+\?format=+Condition:+%C\n+Humidity:+%h\n+Temperature:+%t\n+Feels+like:+%f\n+Precipitation:+%p\n+Wind:+%w\n+Pressure(hPa):+%P\n+Moonphase:+%m\n'"&nonce=$RANDOM"
```

(I appended `"&nonce=$RANDOM"` (in double quotes, not in single quotes!))

but with such query like yours, I don't event think that it is necessary,
because it is highly unlikely that someone else already used exactly the same query,
and the response was cached. So even without appending `nonce`, you will by pass the cache (what is not the case for simple queries like `/London`)

**Comment by nick87720z** [comment]
I'm experiencing same issue, but above technic with `&noonce=$RANDOM` makes no difference.
I added tint2 executor, running two curl commands (they need different redirection) with different formats:
format=2 for applet text and missing one (default) for tooltip (this way I have multi-day info just by mouse hovering).

Default format (that one, affected by options "n012") gives a bit different result comparing to `format=` values 1..4 and v2.
For my location default one gives 21°, while 1..4 and v2 all give 18°.
![wttr-temp-mismatch-fs8-zop](https://user-images.githubusercontent.com/3896190/119032150-4a3ade80-b9c5-11eb-9327-84dc1d6bc1e7.png)

I wanted to use format=v2 in tooltip, but its display is a bit broken, producing garbage in upper-left diagram corner (as for rounded corners - I'm using customized font for now).

There is executor command:
`curl 'https://wttr.in?q&p&0&lang=ru&format=1' && printf '%s' "$(tput -Tansi.sys-old clear)$(curl 'https://wttr.in?MFTn&qQ&lang=ru')" >&2`

**Comment by chubin** [comment]
But you don’t have random nonce in your queries, as far as I can judge?

**Comment by nick87720z** [comment]
I already tried &nonce="$RANDOM" in the end, No difference, Also. New format v3 result repeats one from default format. And above customized long format (with custom fields) represents second one. Also I noticed they both change, but they still are not equal. I tend to think they could use different data sources. Difference appears with my city and around it (slightly shifted numeric coordinates), but doesn't e.g. for muc from help examples. My city is yekb.

**Comment by AnatoleLucet** [comment]
I'm having the same issue, but the `nonce` query param doesn't seem to fix it.
The default `wttr.in` seems to show the correct temperature (~17C), while `wttr.in/?format=2` is off by a few degrees.

![image](https://user-images.githubusercontent.com/35486736/122724525-4e804300-d274-11eb-87d0-2a02f2dd1a08.png)
