### ISSUE TITLE
wttr.in site in imperial units?

### ISSUE THREAD

**Issue by irrg** [chubin/wttr.in#6]
I've checked the docs and tried a few things but still get Celcius temperatures. Is there a flag to pass in the URL to switch to Fahrenheit?

**Comment by kessiler** [comment]
+1

**Comment by Evidlo** [comment]
I am also interested in this.

**Comment by chubin** [comment]
I'll fix it in the next time. It's the most wanted fix at the moment. And it will be easy to fix because the backend supports is already.

**Comment by quite** [comment]
It was fixed but not commit here on github?

**Comment by MInner** [comment]
hey, anybody? :)

**Comment by InsomniumBR** [comment]
Any news on this issue?

**Comment by InsomniumBR** [comment]
I have found this on help:

![image](https://cloud.githubusercontent.com/assets/2073799/21525654/d67bc2c6-cd05-11e6-9e28-d0b9b76a6c7c.png)

Passing parameter ?u on the end of URL will change for metric units.

And it works. Issue can be closed.

**Comment by deanturpin** [comment]
?u works for me too!

**Comment by pranaygp** [comment]
Can this issue be closed?

**Comment by chubin** [comment]
Yes it can
