### ISSUE TITLE
JSON frontend support

### ISSUE THREAD

**Issue by bahamas10** [chubin/wttr.in#60]
Hi, i love `wttr.in` and have been using it for a lot of personal projects lately.  I believe `wego` supports JSON as an output (specified as a "frontend", though I haven't tested this personally).  It would be awesome if `wttr.in` could support JSON output (or specifying any arbitrary frontend I suppose)... maybe something like:

- `GET /Buffalo` - buffalo ny weather
- `GET /Buffalo?frontend=json` - buffalo ny weather with `-f json` passed to the `wego` command

There might need to be some extra processing by `wttr.in` to specify the appropriate headers to the requesting client to let it know the response is JSON.

If there is interest in this I can take a look at the code and see what I can do

**Comment by dvv** [comment]
I believe `GET /Buffalo.json` is of less surprise.

**Comment by robertoduessmann** [comment]
Hi, I took the liberty of creating a REST API with JSON support had based on the _wttr.in_ information.
Take a look:
https://goweather.herokuapp.com/weather/Buffalo

Or try execute:
`curl -X GET https://goweather.herokuapp.com/weather/Buffalo`

If you want to check or contribute with the code (in [Go](https://golang.org/)), feel free to visit:
https://github.com/robertoduessmann/weather-api

I hope to help somebody  :smiley: 
Also, feel free to comment or request new features ;)

**Comment by curtisgibby** [comment]
I like the idea of JSON output too. @robertoduessmann 's goweather app seems a good idea in theory, but so far it's too bare-bones to be very useful, since it only includes (current) `temperature` and `wind` conditions. I'd want to see a description ("Rainy" or "Sunny"), wind and rain conditions, for both the current time as well as a forecast. Y'know, like a regular weather API.

**Comment by robertoduessmann** [comment]
Hi @curtisgibby , I understood your point of view, thanks for your feedback.

Anyway, if you still have interest in goweather, in the last weeks, we improved the API. 
We've added weather description and forecast to 2 days. Take a look and fell free to suggest more things you consider important to add in API.

**Comment by curtisgibby** [comment]
Thanks. I am still interested in consuming this API, and the improvements that you've added do make the system much more useful. I created a couple of new issues for further possible refinements.

**Comment by robertoduessmann** [comment]
Nice, I really thank for your comments @curtisgibby . I will work and add the features as soon as possible :smile:

**Comment by mikwei** [comment]
Was looking for additional text format options as did not see JSON as a current option.  Ideally JSON or XML where I can format out preferred.

In mean time existing text output, how do I add my own text for formatted output, add <br> at end and maybe <tr> or <li> tagging, or even something simple like "Wind:%w<br>Humidity:%h" to current output.

**Comment by chubin** [comment]
@mikwei I hope that both JSON and XML APIs will be published soon. Currently you can use the single output API; it possible to have using the output you are describing: 
```
$ curl wttr.in/London?format="%l:+%c+%t"
London: ☀️ +15°C
```
`w` is for Wind; `h` is for humidity etc. See the full list in [README.md](README.md).

**Comment by xewl** [comment]
There appears to be a solution built in: **?format=j1**

**Comment by chubin** [comment]
@xewl Yes, that's true; thank you for reminding me of this issue. It is fixed now
