### ISSUE TITLE
PNG with view option "p" has extra white pixel on bottom right

### ISSUE THREAD

**Issue by eliot-akira** [chubin/wttr.in#603]
Hello - Thank you for creating `wttr.in`, it's been so useful.

I noticed a tiny issue with PNG generation: when the view option "p" is enabled, there's an extra white pixel on bottom right.

[`https://wttr.in/London_0p.png`](https://wttr.in/London_0p.png)

![London_0p](https://user-images.githubusercontent.com/5352434/118176910-4857a500-b432-11eb-989f-9b1386f5a306.png)

I tried different locations, and it appears consistently.

[`https://wttr.in/Berlin_0p.png`](https://wttr.in/Berlin_0p.png)

![Berlin_0p](https://user-images.githubusercontent.com/5352434/118176924-50afe000-b432-11eb-9004-73b371993307.png)

---

Without view option "p", the pixel does not appear.

[`https://wttr.in/Berlin_0.png`](https://wttr.in/Berlin_0.png)

![Berlin_0](https://user-images.githubusercontent.com/5352434/118177338-daf84400-b432-11eb-86cd-e71a1d308793.png)

**Comment by chubin** [comment]
Yes, I know about this artifact. That is how the rendering is implemented. The reason for that it crops the rendered text area by the last visible character, so a dot was added on the right side, just to avoid removal of the padding. I thought it would be invisible but nothing will escape the eye of wttr.in purists. If the dot is really annoying, I will try to find some other solution. If it is not so annoying and you just wanted to let me know about it, let it stay. How do you think?

**Comment by eliot-akira** [comment]
Ah, I see, it makes sense that the dot is used to keep the padding within the crop. No problem, I think it can be removed or hidden on my side, if I wanted to. Please feel free to close this issue. Thanks again for the wttr.in service!

**Comment by chubin** [comment]
I think with this dot it looks even cooler :) Maybe in future, if the rendering engine will be rewritten, this dot will disappear, but if it does not annoy you too much, I would let it stay here for the moment.

I will close the issue. Feel free to reopen it, if the dot becomes too annoying.

**Comment by acid-bong** [comment]
If you're using curl, you can pipe it into `sed` (`sed 's/.$//'`) and add a `--silent` flag to `curl` to remove the download status
![изображение](https://user-images.githubusercontent.com/94849097/167291838-31a96cb3-2441-4a17-97b5-2b56627d9024.png)
