### ISSUE TITLE
Wrong temperature using powershell

### ISSUE THREAD

**Issue by Blisk** [chubin/wttr.in#610]
When I use 
curl wttr.in/Ljubljana?format=1
It shows currently 25 oC
When I check directly with chrome browser  http://wttr.in/Ljubljana I get 20 oC
All what I need is just current real temperature in town.
![2021-07-03 22_33_34-Weather report_ Ljubljana - Opera](https://user-images.githubusercontent.com/2773050/124366266-c7a57000-dc4e-11eb-8f23-35e21570fe47.png)
![2021-07-03 22_35_00-Windows PowerShell](https://user-images.githubusercontent.com/2773050/124366309-0dfacf00-dc4f-11eb-8ce4-05032d2d7237.png)

**Comment by Blisk** [comment]
![2021-07-03 22_35_00-Windows PowerShell](https://user-images.githubusercontent.com/2773050/124366302-f9b6d200-dc4e-11eb-8880-9a7ceed07ebb.png)

**Comment by chubin** [comment]
I believe that the web version is cached, so if you append `+` to bypass caching, you will get the same result for the one-line query and for the web.

Also, keep in mind that this `curl` in your case is not the real curl, and it is just some irrelevant windows command.
Try to use `Invoke-RestMethod http://wttr.in` instead

**Comment by Blisk** [comment]
I have already tried invoke but it is the same.
where to append + in web bwser address like this
http://wttr.in/Ljubljana+
it is still the same

**Comment by Blisk** [comment]
If I use invoke I get this error
You cannot call a method on a null-valued expression.
At D:\test\temp.ps1:2 char:2
+  $c = $a.Content.substring(3,4)
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by chubin** [comment]
Please test if you have the problem still

**Comment by Blisk** [comment]
It works now.

**Comment by chubin** [comment]
Thank you!
