### ISSUE TITLE
multiple locations in Python?

### ISSUE THREAD

**Issue by giovannicoppola** [chubin/wttr.in#611]
great tool!
is there a way to query multiple locations from a Python3 script? 
`import requests    
payload = {'format': '4'}
    r = requests.get("http://wttr.in/{Nuremberg,Hamburg,Berlin}" , params=payload)
`
does not seem to work (will return the last location with name `Nuremberg,Hamburg,Berlin`)
thanks!

**Comment by gregdan3** [comment]
The examples given in the README are shell syntax that performs multiple location lookups, and not a specific capability of wttr.in to perform more than one location lookup in a single request.

When the shell sees the following command:
`curl -s 'wttr.in/{Nuremberg,Hamburg,Berlin}?format=3'`
It gets processed into:
`curl -s 'wttr.in/Nuremberg?format=3'`
`curl -s 'wttr.in/Hamburg?format=3'`
`curl -s 'wttr.in/Berlin?format=3'`
And each command is run consecutively.

If you wanted to do the same in Python, it would look more like this:

```python
import requests

payload = {'format': '4'}
locations = ["Nuremberg", "Hamburg", "Berlin"]
for loc in locations:
    resp = requests.get(f"http://wttr.in/{loc}", params=payload)
    ...
```

**Comment by giovannicoppola** [comment]
makes sense. thanks!!
