### ISSUE TITLE
No Data for Turkey and its cities

### ISSUE THREAD

**Issue by emrakyz** [chubin/wttr.in#616]
There is no data since 08:30 today for Turkey and the cities of Turkey. "Unknown location; please try ~38.1491472,27"

**Comment by plasmoduck** [comment]
I'm having the same problem for Sydney Australia, it wont show data for any location as a matter of fact. Must have reached their data quota with upstream provider.

**Comment by emrakyz** [comment]
Some cities/countries didn't have a problem when I checked. Now it's completely dead, I guess.

**Comment by plasmoduck** [comment]
Berlin works

**Comment by slackline** [comment]
No joy here either...

```
 7:33:15 am BST  0  neil  ~  
❱ curl wttr.in/Berlin

Follow @igor_chubin for wttr.in updates
 7:33:28 am BST  0  neil  ~  
❱ curl wttr.in/London

Follow @igor_chubin for wttr.in updates
 7:33:33 am BST  0  neil  ~  
❱ curl wttr.in/Brest 

Follow @igor_chubin for wttr.in updates
 7:33:37 am BST  0  neil  ~  
❱ curl wttr.in/New+York

Follow @igor_chubin for wttr.in updates
 7:33:42 am BST  0  neil  ~  
❱ 
```

`v2d.wttr,in` returns the `Unknown location; please try <lat>,<lon>`...

```
❱ curl v2d.wttr.in/Berlin
Unknown location; please try ~52.52045,13.40732
Follow @igor_chubin for wttr.in updates
 7:32:58 am BST  0  neil  ~  
❱ curl v2d.wttr.in/London
Unknown location; please try ~51.509648,-0.09907
Follow @igor_chubin for wttr.in updates
 7:33:03 am BST  0  neil  ~  
❱ curl v2d.wttr.in/Brest 
Unknown location; please try ~48.3905283,-4.4860
Follow @igor_chubin for wttr.in updates
 7:33:07 am BST  0  neil  ~  
❱ curl v2d.wttr.in/New+York
Unknown location; please try ~40.7305991,-73.986
Follow @igor_chubin for wttr.in updates
```

**Comment by k4rli** [comment]
There is an [outage currently](https://twitter.com/igor_chubin/status/1430060432304353309)

**Comment by French77** [comment]
> Sorry, we processed more than 1M requests today and we ran out of our datasource capacity.
We hope to solve the problem as soon as possible, so you can enjoy
your favourite weather service 24x365 even if it rains or snows.

Follow [@igor_chubin](url) for the updates.

**Comment by chubin** [comment]
Please check; it should be back online already; there was a short outage again

**Comment by French77** [comment]
> Please check; 

- 🗸 @chubin nice work all up and running

**Comment by chubin** [comment]
The outage was fixed on the same day, and it has been working since that time. I close the issue. Please ping me if any problems occur
