### ISSUE TITLE
Add option for giving the specific country for similarly named towns

### ISSUE THREAD

**Issue by saigrandhi** [chubin/wttr.in#62]
Hi,

Is it possible to add the country next to the city so that the results come from the town that is present in that country?
For example, Carlisle is a town in USA and UK. But wttr.in/carlisle gives the results for Carlisle that is found in UK.

**Comment by chubin** [comment]
Yes, just add `,Country:`

http://wttr.in/carlisle,UK
http://wttr.in/carlisle,US

**Comment by saigrandhi** [comment]
Oh that works! 
However, when we do not pass any input to the url and it recognizes the location through ip address, the results are still from Carlisle, UK.

**Comment by chubin** [comment]
Yes, that's right, that's a bug. Opened #63
