### ISSUE TITLE
convert command not working on macOS 11.5.2

### ISSUE THREAD

**Issue by gcstang** [chubin/wttr.in#621]
I really like what I'm seeing but this command isn't working on my Mac, do I have something wrong?

convert source.jpg <( curl wttr.in/Phoenix_tqp0u.png ) -geometry +50+50 -composite target.jpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5062  100  5062    0     0   4713      0  0:00:01  0:00:01 --:--:--  4713
convert: unable to open image 'source.jpg': No such file or directory @ error/blob.c/OpenBlob/3536.
convert: image sequence is required `-composite' @ error/mogrify.c/MogrifyImageList/8153.
convert: no images defined `target.jpg' @ error/convert.c/ConvertImageCommand/3322.

I'd like it to perform the resize, have values in F i.e. using ?u and be able to display this on my desktop like you had it in the README.

Thank you

**Comment by chubin** [comment]
You are doing everything right, but you miss the backroung image (source.jpg).
Take any image you would like to use as background and specify it instead of `source.jpg`:

```
convert my_bacground_image.jpg <( curl -s wttr.in/Phoenix_tqp0u.png ) -geometry +50+50 -composite target.jpg
```

**Comment by chubin** [comment]
I close this one; please comment if it should be reopen
