### ISSUE TITLE
Minimalized plain text for embedded devices with low memory?

### ISSUE THREAD

**Issue by lorhof1** [chubin/wttr.in#624]
Hello, I'd like to suggest a very minimalized version that is just a text with the weather state (e. G. sunny).

**Comment by chubin** [comment]
Hi @lorhof1 
Yes sure, just use the the one-line-format:

```
$ curl 'wttr.in/Nuremberg?format=%C\n'
Sunny
$ curl 'fr.wttr.in/Paris?format=%C\n'
Partiellement couvert
```

**Comment by lorhof1** [comment]
thanks
