### ISSUE TITLE
Unknown Location

### ISSUE THREAD

**Issue by backslash-f** [chubin/wttr.in#638]
```
$ curl -s 'wttr.in/Berlin?format=3&m'
Unknown location; please try ~52.52045,13.40732
```

**Comment by herrwusel** [comment]
wttr.in in general seems to have problems currently.

**Comment by Jonta** [comment]
Was broken before

Works again here

**Comment by chubin** [comment]
Now this is for real. Will be not available for the next 4 hours. Stay tuned. I will update you, as soon as it is back online

**Comment by chubin** [comment]
How is it leaking? It is only you who sees the error message; but I agree, that the message could be more accurate/relevant

**Comment by chubin** [comment]
For many reasons, but mainly because of it’s absolutely free nature (free as in freedom and free as in beer) combined with high popularity (~20M queries daily). 

Regarding error message: agreed, I will fix it

**Comment by chubin** [comment]
A little bit more details: from time to time we reach the top data source capacity daily limit (as today), and so we can’t do nothing about, but just wait. We could increase the capacity permanently, but it would cost much more than it costs now; many users proposed many times to fund the service via patreon etc; maybe that is the way to go, but I am not sure how many are willing to do it for real. Just out of curiosity, my question to them who read the thread: would you support the service with $1/month if it would reduce number of outages by 80%? (serious question)

**Comment by chubin** [comment]
Thank you @MAGICCC
wttr.in is back

**Comment by chubin** [comment]
@Jonta The wttr.in data comes from openstreetmap, by the way

**Comment by Jonta** [comment]
As a logging thing for further debugging: It's happening again right now, and has happened at least once more between @chubin replying to me and now

Putting in coordinates works, so I've modified my setup to check whether the 1st word is "Unknown"

**Comment by chubin** [comment]
@Jonta How can I reproduce it?

**Comment by Jonta** [comment]
@chubin Be in my location yesterday, and run `curl -s wttr.in/?format=1`

- Error message suggests the correct coordinates
- `curl`ing with those coordinates gave me the weather

So what's happening seems to be:

Me: "What's the weather where I am?"
Wttr: "Oh, I don't know where you are. Try asking me what the weather is at [your coordinates] instead"
M: "OK. What's the weather at [my coordinates]?"
W: "This weather, and this temperature"
M: "Thanks. But if you knew all that, why didn't you just tell me from the start?"

**Comment by chubin** [comment]
Yes, this is definitely a bug, but I can't understand under circumstances it happens.
The same command works perfectly for me of course.

A couple of other questions:

1. Does `curl wttr.in` works for you?
2. Does `curl v2.wttr.in` works for you?
3. Does `curl wttr.in/<Location>?format=1` works for you?

I suppose that (3) works, but who knows

**Comment by Jonta** [comment]
```sh
~ curl wttr.in

Follow @igor_chubin for wttr.in updates
```
```sh
~ curl v2.wttr.in
Unknown location; please try ~[my coordinates]
Follow @igor_chubin for wttr.in updates
```
```sh
~ curl wttr.in/[My location]?format=1
Unknown location; please try [my coordinates]~
```

Note that in the last one, there's no newline at the end

**Comment by chubin** [comment]
Thank you for reporting it! The outage was fixed 4 days ago. Since that the service works without interruptions

**Comment by Jonta** [comment]
Same as above, except for:

```
~ curl v2.wttr.in

Sorry, we are running out of queries to the weather service at the moment.
Here is the weather report for the default city (just to show you what it looks like).
We will get new queries as soon as possible.
You can follow https://twitter.com/igor_chubin for the updates.
======================================================================================
```

**Comment by Jonta** [comment]
Same on 1 & 2 as above now

But 3 gives weather info

Tried all 3 of them twice

**Comment by Jonta** [comment]
1 and 2 work now, but 3 gives "Unknown location; please try [my coordinates here]"

**Comment by Jonta** [comment]
1 works

2 and 3 do not

**Comment by Jonta** [comment]
Possibly related: 1 now gives me a 404, unknown location. And then
```
We were unable to find your location 
 so we have brought you to Oymyakon, 
 one of the coldest permanently inhabited locales on the planet.
```

2 tells me wttr.in is running out of queries, and does not give me the weather report for the default city, even though it tells me it does

3 tells me it's +17°C in my location, which it definitely is not

**Comment by chubin** [comment]
@Jonta Please test it now

**Comment by Jonta** [comment]
@chubin Only saw this just now. All 3 seem to work well now

**Comment by Jonta** [comment]
1: `
Follow @igor_chubin for wttr.in updates` (took >10 s to respond the first time)
2:
```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
</html>
```
Next time I tried: `Unknown location; please try [my coordinates]`
3: `curl: (52) Empty reply from server`

**Comment by chubin** [comment]
Was down for some time on Apr 24, but quickly recovered. Thank you all for reporting!

**Comment by Jonta** [comment]
`Sorry, we are running out of queries to the weather service at the moment.`

(Just for the record)

**Comment by chubin** [comment]
Should work already, please recheck and thank you for reporting :+1:

**Comment by Sergey5588** [comment]
У меня тоже, может что то с РФ связаное?

**Comment by chubin** [comment]
Всё должно опять работать

**Comment by fierce-goose** [comment]
сейчас тоже не работает, но это ладно, подождать могу. Но оно показывает мои координаты :( пофиксите это пж, у меня оно на вейбаре стоит

**Comment by chubin** [comment]
Иногда у нас заканчиваются данные, тогда происходит вот это. Данные заканчиваются тогда, когда очень большой наплыв запросов в день, как например, был вчера. Рано или поздно мы это пофиксим

**Comment by jakewilliamson88** [comment]
> ...would you support the service with $1/month if it would reduce number of outages by 80%? (serious question)

@chubin Did anything ever come of this? I'm willing to contribute
