### ISSUE TITLE
Specify day in query

### ISSUE THREAD

**Issue by lonyelon** [chubin/wttr.in#645]
Hi!

Is it possible to do a query like this:
```sh
curl 'wttr.in/Pontevedra?format=3'
```

But getting the weather prediction for tomorrow?

Thanks a lot!

**Comment by chubin** [comment]
Hi Sergio, no it is not possible directly, but it is easily doable with additional tools.

```
$ curl -s wttr.in/ | sed -n 8,17p
                                                       ┌─────────────┐
┌──────────────────────────────┬───────────────────────┤  Sun 31 Oct ├───────────────────────┬──────────────────────────────┐
│            Morning           │             Noon      └──────┬──────┘     Evening           │             Night            │
├──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┤
│     \   /     Sunny          │     \   /     Sunny          │     \   /     Clear          │     \   /     Clear          │
│      .-.      +8(6) °C       │      .-.      +14(12) °C     │      .-.      +11(10) °C     │      .-.      +8(6) °C       │
│   ― (   ) ―   ↖ 15-21 km/h   │   ― (   ) ―   ↖ 17-19 km/h   │   ― (   ) ―   ↖ 13-18 km/h   │   ― (   ) ―   ↖ 12-25 km/h   │
│      `-’      10 km          │      `-’      10 km          │      `-’      10 km          │      `-’      10 km          │
│     /   \     0.0 mm | 0%    │     /   \     0.0 mm | 0%    │     /   \     0.0 mm | 0%    │     /   \     0.0 mm | 0%    │
└──────────────────────────────┴──────────────────────────────┴──────────────────────────────┴──────────────────────────────┘
```

Would it help?

**Comment by lonyelon** [comment]
> Hi Sergio, no it is not possible directly, but it is easily doable with additional tools.
> 
> ```
> $ curl -s wttr.in/ | sed -n 8,17p
>                                                        ┌─────────────┐
> ┌──────────────────────────────┬───────────────────────┤  Sun 31 Oct ├───────────────────────┬──────────────────────────────┐
> │            Morning           │             Noon      └──────┬──────┘     Evening           │             Night            │
> ├──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┤
> │     \   /     Sunny          │     \   /     Sunny          │     \   /     Clear          │     \   /     Clear          │
> │      .-.      +8(6) °C       │      .-.      +14(12) °C     │      .-.      +11(10) °C     │      .-.      +8(6) °C       │
> │   ― (   ) ―   ↖ 15-21 km/h   │   ― (   ) ―   ↖ 17-19 km/h   │   ― (   ) ―   ↖ 13-18 km/h   │   ― (   ) ―   ↖ 12-25 km/h   │
> │      `-’      10 km          │      `-’      10 km          │      `-’      10 km          │      `-’      10 km          │
> │     /   \     0.0 mm | 0%    │     /   \     0.0 mm | 0%    │     /   \     0.0 mm | 0%    │     /   \     0.0 mm | 0%    │
> └──────────────────────────────┴──────────────────────────────┴──────────────────────────────┴──────────────────────────────┘
> ```
> 
> Would it help?

I solved it using the JSON data, but thanks for the reply!
And sorry for not answering before :)
