### ISSUE TITLE
404 status not cached

### ISSUE THREAD

**Issue by krzysztofrewak** [chubin/wttr.in#646]
I thought I would fix that, but running this application in local environment is harder than I thought. My someone with more Python skills will fix that.

Anyway, there's a bug in one of basic features of your API. I believe the problem lies here: https://github.com/chubin/wttr.in/blob/master/lib/wttr_srv.py#L366 - during caching response with the fast mode:
```python
    # first, we try to process the query as fast as possible
    # (using the cache and static files),
    # and only if "fast_mode" was unsuccessful,
    # use the full track
    parsed_query = parse_request(location, request, query, fast_mode=True)
    response = _response(parsed_query, query, fast_mode=True)

    http_code = 200
    try:
        if not response:
            parsed_query = parse_request(location, request, query)
            response = _response(parsed_query, query)
            #if not response or (isinstance(response, str) and not response.strip()):
            #    return RuntimeError("Empty answer")

            if parsed_query["location"] == NOT_FOUND_LOCATION:
                http_code = 404
```

Everything is okay when a proper location is cached. When we are calling non-existing place, API responds with 404, but it seems that this response is cached too. Second call for the same non-existing place returns status code 200.

See it yourself: https://wttr.in/xdxdxdxdxdxd and https://wttr.in/xdxdxdxdxdxd (with Postman or something like that)

First call:
![obraz](https://user-images.githubusercontent.com/10898728/136832825-da751124-8e90-4bd4-80a9-c4db1757be1a.png)

And the second one:
![obraz](https://user-images.githubusercontent.com/10898728/136832871-9f467141-4240-4f21-95b6-fdfeb046853c.png)

**Comment by chubin** [comment]
Yes, it is a bug; I acknowledge it, and I will fix it. Thank you for reporting!

**Comment by chubin** [comment]
It must be fixed now, please test it

**Comment by krzysztofrewak** [comment]
> It must be fixed now, please test it

@chubin, it works perfectly. Thanks! :)
