### ISSUE TITLE
Wrong translation. Inconsistency of indicators for Ukrainian and Russian localization.

### ISSUE THREAD

**Issue by aliskinr** [chubin/wttr.in#647]
Here are two screenshots (in one screenshot). In the Russian and Ukrainian versions, not only the translation is inconsistent, but the numbers are different. I only changed the localization parameters ru and uk.

Вот два скриншота (на одном скриншоте). В русской и украинской версии не только перевод несоответствует, а и цифры разные. Я менял только параметры локализации ru и uk.

![Screenshot_20211011_203917](https://user-images.githubusercontent.com/82435321/136835400-d72ea559-3ebd-4dc0-bdfc-639c5ca821f8.png)

**Comment by chubin** [comment]
Probably a duplicate of #668 (or other way around).
It is a caching issue; see #668 for the details.

**Comment by chubin** [comment]
I close this one; please comment if it should be reopen
