### ISSUE TITLE
can't specify units with one-line input command

### ISSUE THREAD

**Issue by mrsteve0924** [chubin/wttr.in#650]
this works  
curl https://wttr.in/99501?format=1

and this  
curl https://wttr.in/99501?format="%c+%t\n"

gives me units in Fahrenheit as I want, but when i am connected to a VPN it defaults to celsius.  I can't figure out how to set it back to Fahrenheit.  tried using the "u" option in various ways, but doesn't work

like:  
curl https://wttr.in/99501?u?format=1
or  
curl https://wttr.in/99501?format=1?u

is there a format that works with one-line input?

**Comment by rohitnairtech** [comment]
Can you give me more information about the VPN? I tried it and it works for me.

**Comment by Jed28** [comment]
I'm having the same issue, my VPN is Private Internet Access. I wish my results to be in Celsius but it's forced to be in Fahrenheit. I've tied
[https://wttr.in/Sydney?m?format=%C\n%t\n%f\n%w\n%p\n%S\n%s](https://wttr.in/Sydney?m?format=%C\n%t\n%f\n%w\n%p\n%S\n%s) This ignores all format options and is still in Fahrenheit.
[https://wttr.in/Sydney?format=%C\n%t\n%f\n%w\n%p\n%S\n%s?m](https://wttr.in/Sydney?format=%C\n%t\n%f\n%w\n%p\n%S\n%s?m) Yields correct formatting but in Fahrenheit
When I connect to Australia Melbourne I get the above issues but if I connect to Australia Sydney it's in Celsius. I sometimes have to swap servers to keep my speed up.

**Comment by Jed28** [comment]
Perfect! I've tested with various servers and got the correct results using &. I would mark this closed if I was the OP.

**Comment by chubin** [comment]
Maybe we should add it to the README file, because I saw this error already many times

**Comment by giovannicoppola** [comment]
Hi @chubin, `&m` works for me to toggle the temperature format when used with `curl` but it doesn't when included in a `requests` payload string in a Python script. What am I doing wrong?

**Comment by trekkie1701c** [comment]
As far as I can tell, requests will change '&' to '%26' if you include it literally, which will break the way wttr works.  I've done a little bit of experimenting to see if I can change that behavior in a script, but I haven't stumbled on a solution for that.
