### ISSUE TITLE
Localisation for Tamil language -தமிழ்

### ISSUE THREAD

**Issue by parthi1984** [chubin/wttr.in#663]
I would like to help in translation for Tamil language - தமிழ். Please let me know how I can contribute to this idea.

---

To do:

- [x] add Tamil translation for `Weather report`, `Morning`, `Noon`, `Evening`, `Night`
- [x] Translate weather condintion names into Tamil
- [x] Translate messages into Tamil
- [x] Translate help file into Tamil
- [x] v2.wttr.in translation
- [x] add your name to the translators list?

**Comment by chubin** [comment]
Thanks a lot! I've merged it and deployed.

https://ta.wttr.in

Could you please also translate these words:

* Morning
* Noon
* Evening
* Night
* Weather report

?

And also please add your name and Github/Twitter account to the translators list
so that it is visible here:

http://ta.wttr.in/:translation

**Comment by parthi1984** [comment]
PFB the translations.

You can add my GitHub id (parthi1984) to the Authors list.

   - Morning - காலை
   - Noon - நண்பகல்
   - Evening - சாயங்காலம்
   - Night - இரவு
   - Weather report - வானிலை அறிக்கை
   -

**Comment by chubin** [comment]
Thank you. I committed your translations and deployed them. Now they are available live.
The problem with formatting is still there of course, but the translation part is now fully done, I believe,
and it can be already used for the one-line format queries.
Thanks a lot for your help.

**Comment by parthi1984** [comment]
Thanks

**Comment by chubin** [comment]
I moved the rendering related tasks to #676, and so this one can be closed now.
@parthi1984 Thank you very much for you help!
