### ISSUE TITLE
[ISSUE]Macedonian is made in Bulgarian

### ISSUE THREAD

**Issue by MatejMecka** [chubin/wttr.in#67]
I got data for my city Skopje which is in the Republic of Macedonia but the website gives the text in Bulgarian. 

Bulgarian and Macedonian may have the same roots but we have different letters and it's a different language and as younger people try to look at sites they don't understand Bulgarian.

You can add an option to choose the language it'd be really nice

and probably try translating it to Macedonian. If you need help DM me on Twitter or i'll submit them here

**Comment by MatejMecka** [comment]
I see it's fixed. Thank you @chubin.

**Comment by chubin** [comment]
@MatejMecka: How do you see that it is fixed? Can do you check it?
It should not be fixed yet. You can choose the language indeed, but Macedonian is not (yet) supported.
Can you help me with translation into Macedonian?

**Comment by MatejMecka** [comment]
I'm getting data in English now instead of Bulgarian. But i'll help you :) 

Where should I send you the translations?

**Comment by chubin** [comment]
Have you tried Bulgarian also? Does it work for you? Use ?lang=bg or -H "Accept-Language: bg"
Does it work?

**Comment by MatejMecka** [comment]
Tested it. Works

**Comment by chubin** [comment]
We can partially translate it now (time, date, title), and partially later (weather conditions).
Can you please translate these Bulgarian words/phrases?

> Прогноза за времето в
> Сутрин
> Обяд
> Вечер
> Нощ

**Comment by chubin** [comment]
Is this translation correct?

> Прогноза за времето во
> Утро
> Подобни
> Вечер
> Ноќ

**Comment by MatejMecka** [comment]
The 3rd one is Пладне the rest are correct

**Comment by chubin** [comment]
> Прогноза за времето во
> Утро
> Пладне
> Вечер
> Ноќ

Right?

**Comment by MatejMecka** [comment]
Yep :)

**Comment by chubin** [comment]
Please check if it works:

http://wttr.in/Skopje?lang=mk

or 

curl -H "Accept-Language: mk" http://wttr.in/Skopje

The weather condition names are not yet translated. That is the next step

**Comment by MatejMecka** [comment]
For Night I'm getting sunny even though the translations are good?

**Comment by chubin** [comment]
Clear or Sunny?

**Comment by MatejMecka** [comment]
Clear but it displays sunny

**Comment by chubin** [comment]
Yes, it is a known bug (#52). We will fix it soon :)
But back to the translation: as soon as I'm ready to translate the weather conditions names, I will ping you here. And thank you, Matej, for your help. Now wttr.in speaks Macedonian also (almost)

**Comment by MatejMecka** [comment]
No Problem. I'll be glad to help :)

**Comment by chubin** [comment]
@MatejMecka Hi Matej,
can you please translate these messages in Macedonian?

```
113: Clear
116: Partly cloudy
119: Cloudy  
122: Overcast
143: Mist
176: Patchy rain nearby  
176: Patchy rain possible
179: Patchy snow possible 
182: Patchy sleet possible
185: Patchy freezing drizzle possible
200: Thundery outbreaks in nearby
200: Thundery outbreaks possible
227: Blowing snow
230: Blizzard
248: Fog
260: Freezing fog
263: Patchy light drizzle
266: Light drizzle   
281: Freezing drizzle
284: Heavy freezing drizzle
293: Patchy light rain
296: Light rain
299: Moderate rain at times
302: Moderate rain
305: Heavy rain at times
308: Heavy rain
311: Light freezing rain
314: Moderate or heavy freezing rain
317: Light sleet
320: Moderate or heavy sleet
323: Patchy light snow
326: Light snow
329: Patchy moderate snow
332: Moderate snow
335: Patchy heavy snow
338: Heavy snow 
350: Ice pellets
353: Light rain shower
356: Moderate or heavy rain shower
359: Torrential rain shower
362: Light sleet showers
365: Moderate or heavy sleet showers
368: Light snow showers
371: Moderate or heavy snow showers
386: Patchy light rain in area with thunder
386: Patchy light rain with thunder
389: Moderate or heavy rain in area with thunder
389: Moderate or heavy rain with thunder
392: Patchy light snow with thunder
395: Moderate or heavy snow in area with thunder
395: Moderate or heavy snow with thunder
```

If it helps, there are some translations in Builgarian and Russian:

(Bulgarian)
```
113: Слънчево
116: Частична облачност
119: Облачно
122: Плътна облачност
143: Лека мъгла
176: Дъждове на отделни места в околността
179: Снеговалежи на отделни места в околността
200: Прояви на гръмотевици в околността
230: Снежна буря
248: Тежка мъгла
260: Преохладена мъгла
263: Леки превалявания на отделни места
266: Леки превалявания
293: Слаби дъждове на отделни места
296: Слаби дъждове
302: Умерени дъждове
317: Слаба суграшица
323: Слаби снеговалежи на отделни места
326: Слаби снеговалежи
329: Умерени снеговалежи на отделни места
332: Умерени снеговалежи
335: Силни снеговалежи на отделни места
338: Силни снеговалежи
353: Краткотрайни слаби дъждове
356: Краткотрайни умерени или силни дъждове
359: Обилни краткотрайни дъждове
362: Краткотрайни слаби суграшици
368: Краткотрайни слаби снеговалежи
371: Краткотрайни умерени или силни снеговалежи
389: Умерени или силни дъждове на отделни места в области с гръмотевици
```

(Russian)
```
113: Ясно
116: Переменная облачность
119: Облачно
122: Пасмурно
143: Дымка
176: Местами дождь
179: Местами снег
182: Местами дождь со снегом
185: Местами замерзающая морось
200: Местами грозы
227: Поземок
230: Метель
248: Туман
260: Переохлажденный туман
263: Местами слабая морось
266: Слабая морось
281: Замерзающая морось
284: Сильная замерзающая морось
293: Местами небольшой дождь
296: Небольшой дождь
299: Временами умеренный дождь
302: Умеренный дождь
305: Временами сильный дождь
308: Сильный дождь
311: Слабый переохлажденный дождь
314: Умеренный или сильный переохлажденный дождь
317: Небольшой дождь со снегом
320: Умеренный или сильный дождь со снегом
323: Местами небольшой снег
326: Небольшой снег
329: Местами умеренный снег
332: Умеренный снег
335: Местами сильный снег
338: Сильный снег
350: Ледяной дождь
353: Небольшой ливневый дождь
356: Умеренный или сильный ливневый дождь
359: Сильные ливни
362: Небольшой ливневый дождь со снегом
368: Небольшой снег
371: Умеренный или сильный снег
386: В отдельных районах местами небольшой дождь с грозой
389: В отдельных районах умеренный или сильный дождь с грозой
392: В отдельных районах местами небольшой снег с грозой
395: В отдельных районах умеренный или сильный снег с грозой
```

There are some messages in English that have no translations to Bulgarian,
but I hope that we can translate everything in Macedonian.
Thank you very much for your help!

**Comment by anselal** [comment]
I know that here in github we should keep a language, but Macedonia is in Greece not in FYROM. Can you pkease fix these ?

**Comment by chubin** [comment]
@anselal What exactly should I fix? You mean wttr.in should show "Skopje, FRYOM" or "Skopje, Republic of Macedonia" instead of "Skopje, Macedonia"?

**Comment by anselal** [comment]
@chubin "Skopje, FYROM" is the right thing to say.

**Comment by MatejMecka** [comment]
@anselal We are not FYROM! We are Macedonia. So Please don't try to do that unless you like to piss of a lot of Macedonians. @chubin Just noticied. I'll translate them rn

**Comment by chubin** [comment]
@MatejMecka thank you very much for the translation! We see many queries coming from your country, and I think the users doing them will be really happy to see that now wttr.in supports their language.

Please check also wttr.in/:translation I've add there your name if you don't mind

**Comment by MatejMecka** [comment]
@chubin After having time I finally did it. Sorry for being so late but I'll attach it here. Hope it helps you :)

p.s Every sentence in Macedonian begins with an Uppercase letter so if I forgot somewhere to add an uppercase letter don't judge. Thanks.

[translations.txt](https://github.com/chubin/wttr.in/files/924504/translations.txt)

**Comment by chubin** [comment]
@MatejMecka Matej, thank you very much for the translation!
It was much work, but you did it! Thank you!

I've uploaded your translation on the server. Please check it here:

http://wttr.in/%D0%A1%D0%BA%D0%BE%D0%BF%D1%98%D0%B5?lang=mk

Looks perfect.

Do you want commit your translation with your credentials?
If yes, use this file please: 

[mk.txt](https://github.com/chubin/wttr.in/files/949044/mk.txt)

(clone, commit, pull request). The translation files are located here:

share/translations/

**Comment by MatejMecka** [comment]
I made #102 with my own credentials. Thanks for the project. I'm glad to help

**Comment by chubin** [comment]
@MatejMecka Thank you very much, Matej! Could you please translate the last part:
several messages in lib/translations.py
? And after that I could upload the translation on the server

**Comment by chubin** [comment]
@MatejMecka Updated.
You can check error messages here:

http://mk.wttr.in/XXXXXXX

Thank you very much for the help!
