### ISSUE TITLE
list of all available locations

### ISSUE THREAD

**Issue by sprawdzoneit** [chubin/wttr.in#673]
where can i find list of all available locations in wttr.in ?

**Comment by chubin** [comment]
you can't find the whole list of available locations, but you can any of them as input
with additional qualifying words if needed. You can also check the `Location:` line
of the query, to be sure that the correct location was found.

```
~$ curl -s wttr.in/Dąbrowa+Białostocka | grep Location:
Location: Dąbrowa Białostocka, gmina Dąbrowa Białostocka, powiat sokólski, województwo podlaskie, 16-200, Polska [53.654439,23.3485102]
~$ curl -s wttr.in/Dąbrowa+Górnicza | grep Location:
Location: Dąbrowa Górnicza, śląskie, Polska [50.3309808,19.1963279]
```

**Comment by chubin** [comment]
I close this one; please comment if it should be reopen
