### ISSUE TITLE
One line weather ouputs 2 lines

### ISSUE THREAD

**Issue by Mystik01** [chubin/wttr.in#680]
So I request for one line weather, it works but it also needs another empty line. I was using in a python program and assumed it was my issue but I tried it in in Insomnia and it outputs and extra empty line. Is it my issue or why does it do that?
I was able to remove the extra line using `.strip()`  I'm just curious.
https://wttr.in/London?format=3&T

![image](https://user-images.githubusercontent.com/65687597/141186114-1c96d608-2f38-4daa-a3a9-3495d2cf18be.png)

**Comment by Mystik01** [comment]
Closed because I can just use .strip()

**Comment by chubin** [comment]
you can use the %-notation format:

```
curl wttr.in/Nice?format=%C+%t
```
