### ISSUE TITLE
Weather text/metrics placed a bit above the icon (Partial Fog, fog)

### ISSUE THREAD

**Issue by ivankovnatsky** [chubin/wttr.in#686]
i3status-rust:

![image](https://user-images.githubusercontent.com/75213/145372242-c18092a5-f1e5-49e6-964c-b8df74839731.png)

![image](https://user-images.githubusercontent.com/75213/145372922-04c6463d-9bb5-41ba-8ccb-214f6e09b62d.png)

command line:

![image](https://user-images.githubusercontent.com/75213/145372406-6f9749b6-b73f-4394-81ba-61e78a310e78.png)

![image](https://user-images.githubusercontent.com/75213/145373138-a11930fe-0c85-41bd-a9df-b97f0cda7f28.png)

I presume this is have to do with this exact icon, but if something could be done to make the text align vertically that would be great.

Update:

another weather icon:

![image](https://user-images.githubusercontent.com/75213/145567053-292eebed-a72d-451e-8c37-9de60bb00081.png)

**Comment by chubin** [comment]
It is very interesting effect, I've never met it before; I can't really explain it; if I understand it tight, the fog icon affects the subsequent characters rendering, and they are placed higher than they should. It looks like a bug to me, not in wttr.in of course,  but in the software that is doing the rendering (`i3` in this case).

* Have you created issues in other projects regarding this?
* Can you reproduce it printing this character directly?
* Do you know about other characters that have the same effect?

**Comment by ivankovnatsky** [comment]
Thanks, not relevant anymore.
