### ISSUE TITLE
Trying 5.9.243.187:80

### ISSUE THREAD

**Issue by backslash-f** [chubin/wttr.in#687]
```
$ curl -s "wttr.in/Berlin?format=%l:+%t+%f+%C+%c" --verbose
*   Trying 5.9.243.187:80...
```

or

```
$ curl wttr.in/London --verbose                        
*   Trying 5.9.243.187:80...
```

I guess something is offline?

**Comment by chubin** [comment]
Actually not; nothing is offline; I've just checked it. Do you still have this problem?

**Comment by backslash-f** [comment]
Yes. Must be something on my end then. `¯\_(ツ)_/¯`

**Comment by chubin** [comment]
can you curl `https://` ?
can you curl other services, like `ifconfig.co` ?

**Comment by backslash-f** [comment]
I can. O.o

I just check that my router's firewall is blocking out packages against `5.9.243.187`.
I've absolutely no clue why. But it's definitely on my end, we can close this one.

Thanks for checking anyway! 👍🏻
