### ISSUE TITLE
geoloc not solved

### ISSUE THREAD

**Issue by pflegende** [chubin/wttr.in#694]
https://v2.wttr.in
returns:
Unknown location; please try ~50.97456,11.02974

https://wttr.in
https://wttr.in/Erfurt

returns:
a blankscreen

this new beaivor since today
before some years "perfect"

- is our first issue for wttr.in -

:)

**Comment by ScanuNicco** [comment]
Same issue here. I've been using the JSON API for nearly a year and today is the first issue I've had. `https://wttr.in/?format=j1` returns `Unknown location; please try ~37.8044557,-122.2713563`.

**Comment by MAGICCC** [comment]
Seems like https://github.com/chubin/wttr.in/issues/638

**Comment by pflegende** [comment]
seems fixed now

behavior no more seen
29.1.2022, 08:56:17 Erfurt
