### ISSUE TITLE
Add xh as a plain text agent

### ISSUE THREAD

**Issue by victorz** [chubin/wttr.in#695]
It would be great if `xh` were added as a plain text agent, so that the terminal wouldn't be flooded with HTML markup when using `xh` as a request utility. :pray: :heart:

https://github.com/chubin/wttr.in/blob/8bdc54bb7097badbb2bfb9867ccaaa42b94a6636/cmd/srv.go#L21

**Comment by hello-smile6** [comment]
> It would be great if `xh` were added as a plain text agent, so that the terminal wouldn't be flooded with HTML markup when using `xh` as a request utility. 🙏 ❤️
> 
> https://github.com/chubin/wttr.in/blob/8bdc54bb7097badbb2bfb9867ccaaa42b94a6636/cmd/srv.go#L21

Just use `?A` at the end of the URL.

**Comment by victorz** [comment]
> Just use `?A` at the end of the URL.

That solves everything. Thanks! :heart: Closing.

**Comment by e-user** [comment]
I still think this should be done the right way and `xh` should be added. I'm also using xh and if it weren't for this bug report, I would've never found out about the option.

**Comment by victorz** [comment]
> I still think this should be done the right way and `xh` should be added. I'm also using xh and if it weren't for this bug report, I would've never found out about the option.

I mean, true. The "A" format isn't really documented. The documentation I see is this:

> wttr.in currently supports five output formats:
> - ANSI for the terminal;

It doesn't really tell you how to activate that format as far as I can see.

**Comment by hello-smile6** [comment]
#698 will make the documentation more accessible.

**Comment by victorz** [comment]
> #698 will make the documentation more accessible.

Awesome, seems like this is in the works. Closing. Thanks!
