### ISSUE TITLE
How the scalability problem is (not yet) solved

### ISSUE THREAD

**Issue by mcint** [chubin/wttr.in#704]
What can the community do to help this service stay up and operational? Whether technical contributions--some measure of caching, advocacy (or funding) for more capacity, or a deeper exploration of the deployment?

![Screen Shot 2022-02-23 at 8 10 12 PM](https://user-images.githubusercontent.com/601708/155456519-873b447e-8fbf-4fc4-8fcb-1066738597b1.png)

How [may we] attempt to solve the scalability problem?

**Comment by mcint** [comment]
Secondary question: When does the capacity timer reset? (It's 4am UTC as I post this, so hopefully not midnight UTC, which would imply max daily requests was reached in 4 hours)

**Comment by chubin** [comment]
The capacity timer resets at 0:00:00 UTC.

This is a generic message, and it is sometimes displayed when some other problems occur (in rare cases, but it is possible).
Probably it was exactly the case on 24 Feb.

At the moment, the data capacity is though on the limit, but almost always (except some days with peak loads) it suffices to handle the requests.

Thank you for reaching me out, and ping me again if the service will not available :+1:
