### ISSUE TITLE
WEBSITE IS NOT FINDING ANY WEATHER

### ISSUE THREAD

**Issue by Sussy-OS** [chubin/wttr.in#706]
@chubin *ANY* location I type into wttr.in comes out as a 404! *PLEASE* HELP!

**Comment by gw8ndal** [comment]
same for me, every city returns a 404 error

**Comment by Sussy-OS** [comment]
> same for me, every city returns a 404 error

I hope he finds a fix. (It's probably the weather server he is using is down.)

**Comment by ManOfDiamond** [comment]
> > same for me, every city returns a 404 error
> 
> I hope he finds a fix. (It's probably the weather server he is using is down.)

most probably, yeah

**Comment by chubin** [comment]
Please test it now

**Comment by gw8ndal** [comment]
> Please test it now

It still doesn't work

**Comment by ManOfDiamond** [comment]
> Please test it now

yup, now it works, atleast for me

**Comment by gw8ndal** [comment]
nvm it works now, thank you

**Comment by Sussy-OS** [comment]
@chubin It works now, thanks!
