### ISSUE TITLE
Show only tomorrows forecast/temperature?

### ISSUE THREAD

**Issue by kiryo** [chubin/wttr.in#710]
I think showing only tomorrows forecast would be really good.
Correct me if i missed this.
Example: wttr.in/Country?format=%t Shows temperature at the moment. There could be quick way to get tomorrows temperature and conditions with quick parameter.

By the way excellent work!

**Comment by chubin** [comment]
@kiryo Thanks a lot! Regarding the one-line forecast format, I think it is a good idea and it should be added.

We already have issue similar to this one:

* #329 
* #447 

Is it the same, or do you propose something different?

**Comment by kiryo** [comment]
Thank you for reply. Yes pretty much. Just parameter for tomorrow or day after that would be great!
Looking forward for this :)

**Comment by gessel** [comment]
I see #710 is closed, but it seems by OP not as completed yet, no?  If it is possible to show only tomorrow's forecast on the one-liner, what is the syntax?
