### ISSUE TITLE
This utility no longer works... It is constantly saturated with requests

### ISSUE THREAD

**Issue by richlysakowski** [chubin/wttr.in#711]
curl wttr.in/boston

Sorry, we are running out of queries to the weather service at the moment.
Here is the weather report for the default city (just to show you what it looks like).
We will get new queries as soon as possible.
You can follow https://twitter.com/igor_chubin for the updates.

**Comment by MAGICCC** [comment]
https://github.com/chubin/wttr.in/issues/522

**Comment by hello-smile6** [comment]
Can reproduce, https://vnc-gnome.9pfs.repl.co/vnc_lite.html

**Comment by chubin** [comment]
Fixed
