### ISSUE TITLE
Don`t working

### ISSUE THREAD

**Issue by HueRtx** [chubin/wttr.in#720]
24.04.2022
13:10 UTC
weather don`t display
![curl](https://whowho.ru/9YJer.png)

**Comment by Write** [comment]
Can confirm

**Comment by gw8ndal** [comment]
Yep, its not showing anything

**Comment by Write** [comment]
Certainly related to an API Rate limitation like few months ago

**Comment by gw8ndal** [comment]
Yes, maybe it's time to update that limit

**Comment by chubin** [comment]
@gw8ndal I agree, the only problem that the data is not for free, so probably we will need something like a funding campaign. I will think about it.
