### ISSUE TITLE
curl wttr.in no content

### ISSUE THREAD

**Issue by handec** [chubin/wttr.in#721]
The page and command curl http://wttr.in seem to have no response except the twitter follow link. 

`curl wttr.in` returns

`Follow @igor_chubin for wttr.in updates
`

**Comment by dm2912** [comment]
same. 

empty response from curl, location not found in conky

**Comment by rywilliams86** [comment]
same report here from multiple platforms. Getting this:

pi@raspberrypi:~ $ curl wttr.in

Follow @igor_chubin for wttr.in updates
pi@raspberrypi:~ $ curl https://wttr.in

Follow @igor_chubin for wttr.in updates
pi@raspberrypi:~ $ curl https://wttr.in/80538

Follow @igor_chubin for wttr.in updates
pi@raspberrypi:~ $

**Comment by ollintzinlab** [comment]
#638

**Comment by Corin-EU** [comment]
I have been having the same problem, curl connect but no data other than "follow chubin" comes back.

May I suggest that if the wttr.in service exceeds the number of queries permitted from whatever weather service provider it uses, it returns a message similar to "Number of queries exceeded for today" rather than just a blank?

**Comment by Write** [comment]
Fixed

**Comment by tillkuhn** [comment]
Unfixed again :-( 
At least since yesterday (May 4th 2022) there's no weather data anymore, even though the message was improved 

```
$ curl wttr.in

Sorry, we are running out of queries to the weather service at the moment.
Here is the weather report for the default city (just to show you what it looks like).
We will get new queries as soon as possible.
You can follow https://twitter.com/igor_chubin for the updates.
======================================================================================
```

**Comment by mcnuggetsx20** [comment]
Now it works for some cities, but for others doesn't. For instance Warsaw works, but London does not.

**Comment by johnnyontheweb** [comment]
Today it's not working even without city for me

**Comment by johnnyontheweb** [comment]
Tested right now and seems back to work

**Comment by mcnuggetsx20** [comment]
@johnnyontheweb well now it doesn't work at all for me. There is a problem with the number of requests sent. They're saying they're working on it though, so maybe we just need to wait a little bit.

**Comment by mcnuggetsx20** [comment]
Started working again

**Comment by chubin** [comment]
Closing this one, the problem was fixed
