### ISSUE TITLE
Wrong title for location not found

### ISSUE THREAD

**Issue by Skillkiller** [chubin/wttr.in#728]
Currently the title is calculated incorrectly if the specified location is not found. The title is always created from the first line of the sout. <https://github.com/chubin/wttr.in/blob/d5517350218d908593a8c62b4771069cb394eb5e/lib/view/wttr.py#L120>
![image](https://user-images.githubusercontent.com/18444809/168265685-1fa3157a-7d6c-47b7-b038-05f3d4aaa270.png)

**Comment by chubin** [comment]
It looks better now. Please check it; your changes are already deployed live
