### ISSUE TITLE
В русской локали перед днём недели не хватает пробела

### ISSUE THREAD

**Issue by romanesko** [chubin/wttr.in#73]
Кажется ровнее будет с пробелом впереди, чем с пробелом после точки месяца — она и так разряжает пространство, да и её вообще можно опустить. Ну и если честно — то месяц можно указывать тремя буквами, в русском же нет совпадений по трём, и тогда всё красиво вместится 

![](https://monosnap.com/file/2eNfJJ1K6oGwZg2sTedQ1W0qW3s1CE.png)

**Comment by chubin** [comment]
Да, верно насчёт пробела. Что касается четырёхбуквенных сокращений, они стандартны, берутся из данных локали. Мы можем, конечно, их патчить своим нестандартным способом,
но вот надо ли?

**Comment by romanesko** [comment]
Можно, в общем, расширить рамку, но я за то, чтобы коснуться сокращений, т.к.
1. Четыре буквы вместо трёх не дают большей информации
2. Актуальнейшая тут проблема фиксированной ширины: «май» — три символа, «июнь» — четыре «сент.» — пять
2. Есть действующий ГОСТ 7.12-93, где указаны именно трёхбуквенные сокращения месяцев

Если сокращать все месяцы до трёх букв и убрать точки, то это будет самое изящное решение, как мне кажется

**Comment by chubin** [comment]
Переменная ширина проблемы тут не составляет, тут динамически рамочка генерится. К тому же учтите, что нужно поддерживать не только русскую локаль, сейчас поддерживаются около 20, а запланированы в будущем более 100. Там ширина слов может существенно отличаться (да и ширина символов). Но вернёмся к русскому.

Я попытался найти сейчас, где какие сокращения рекомендуются. В «Русском орфографическом словарь» РАН указывается сокращение "февр.". Самое интересное, что в ГОСТе, который вы указываете, также рекомендуется сокращение "февр."

http://nauka.kz/upload/files/07._GOST_7.12-1993.pdf (страница 17).

С другой стороны в локали GNU/Linux используется трёхбуквенное сокращение "фев" (правда, я не знаю, на каком стандарте это основывается).

**Comment by romanesko** [comment]
Забавно, я проверил несколько месяцев перед отправкой, и все они попались трёхбуквенные… но вот февраль…)

Если рамочка динамическая, то, конечно, проще расширить рамочку.

В GNU/Linux скорее всего калька с английского. Вполне логично, вдруг особенность того, что бывают другие языки не рассчитает англоговорящий разработчик и предусмотрит под месяц три символа. Тут скорее подумали, чем случайно получилось.

**Comment by chubin** [comment]
В принципе, вы можем вообще отказаться от сокращений, ширины хватит. Вопрос только в том, получится ли безошибочно масштабировать это решение на все языки особенно с учётом падежей и изменяющихся падежей в зависимости от числа (в некоторых языках).

С другой стороны это решило бы проблему суахили, с которой мы сейчас боремся, там проблема в том, что все дни недели (не месяцы, правда, а дни недели) одинаково начинаются, и сокращения вообще выглядят уникально:

Jumapili, Jumatatu, Jumanne, Jumatano, Alhamisi, Ijumaa и Jumamosi
и сокращения, соответственно, J2, J3, J4, J5, Alh, Ij и J1.
Очень прикольно выглядит дата

**Comment by romanesko** [comment]
🙈

**Comment by chubin** [comment]
Please check if it is better now. I've just fixed it in the running code, but not yet committed the change. Does it look better now?

**Comment by romanesko** [comment]
Да, так прям хорошо!

**Comment by chubin** [comment]
Всё, тогда закрываем!
