### ISSUE TITLE
Is the website abandoned?

### ISSUE THREAD

**Issue by mlv-** [chubin/wttr.in#739]

**Comment by U1s2e3r4n5a6m7e** [comment]
Just look at Libreddit (front-end for Reddit), Invidious (front-end for YouTube) and SearXNG (metasearch engine). People contributing this services by hosting to make more instances. But why not for wttr.in 🤨  Is this what happens when information not decentralized?

**Comment by FallCheetah7373** [comment]
is it actually abandoned? because few days ago it went down and got back up?

**Comment by Guleixibian2009** [comment]
I'm getting `PR_END_OF_FILE_ERROR` in Firefox now.

**Comment by smvd** [comment]
Same, what is going on?

**Comment by Guleixibian2009** [comment]
When I curl for a png format I only got a `502`. (After maybe 4:00 UTC?

**Comment by smvd** [comment]
If i hit `Amsterdam.png` i get the `502` but for `Paris.png` it throws `500`

**Comment by Guleixibian2009** [comment]
Got this in WSL:

```
guleixibian@Guleixibian2009:/mnt/d$ curl https://wttr.in
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to wttr.in:443
```

**Comment by smvd** [comment]
Pretty shure its `http` only so it makes sense OpenSSL errors out.

**Comment by ODog2028** [comment]
When I run `curl wttr.in` I get `Empty reply from server`. When I view from web I get an `nginx Internal Server Error`.

**Comment by ODog2028** [comment]
`wttr.in` has a SSL Certificate that chrome sees as valid.

**Comment by Qlimax1975** [comment]
this is what i get while running curl wttr.in in terminal : curl: (56) Recv failure: Connection reset by peer

**Comment by adarshajit** [comment]
Is the project slowly getting abandoned? `curl wttr.in` in the terminal does not work anymore. like @Qlimax1975 mentioned.

**Comment by chubin** [comment]
Nothing is abandoned. No panic!

**Comment by ODog2028** [comment]
The Website is Back!

**Comment by chubin** [comment]
@ODog2028 It was actually back already yesterday, as I closed the issue, but anyway thank you for your confirmation + thanks to all who reported the issue, and sorry for this outage.
