### ISSUE TITLE
Hide "New feature... for the localized version"

### ISSUE THREAD

**Issue by FlorianLoch** [chubin/wttr.in#74]
I think it would be nice to hide the hint in case one is actually using it via the "Accept-Language" header. I just wanted to to this myself but the regarding coding doesn't seem to be in this repository. ;)

**Comment by chubin** [comment]
It's a good tip Florian! Thank you. We should do it indeed, on the other hand another new feature is to be released soon, so in this case the "Accept-Language" header will be irrelevant.
But we should probably disable the announcement of a feature (or change it with an announcement of some other feature) is the feature is being used. It's a good idea

**Comment by FlorianLoch** [comment]
So I am excited to see what new feature will come to my favourite way of checking weather in the cli ;)

**Comment by chubin** [comment]
I hope you will like the new feature :)

**Comment by Fdebijl** [comment]
To add to this @chubin, would it at all be possible to add a flag to hide 'New feature...' footer entirely? I've had wttr.in in my MOTD for a while now and it's quite lovely indeed, but the footer has bothered me somewhat.

I'm talking about this bit right here if that was not evident
`New feature: multilingual location names wttr.in/станция+Восток (in UTF-8) and location search wttr.in/~Kilimanjaro (just add ~ before) Follow @igor_chubin for wttr.in updates [new 7 features in the last 3 months]
`

**Comment by chubin** [comment]
@Fdebijl Good Idea! We'll make it

**Comment by MindTooth** [comment]
As this been implemented?  Clutter the terminal a bit :/
