### ISSUE TITLE
Incorrectly detects San Francisco, CA as Colonia San Francisco, Mexico

### ISSUE THREAD

**Issue by lfaraone** [chubin/wttr.in#75]
![wttr in - google chrome_031](https://cloud.githubusercontent.com/assets/73410/23098111/c51fba9e-f63d-11e6-96ba-4f0b3cc61a70.png)

MaxMind's GeoIP database detects my IP as:
> 	San Francisco, California, United States, North America

**Comment by chubin** [comment]
Duplicates #63
