### ISSUE TITLE
wttr.in/$location doesn't work anymore?

### ISSUE THREAD

**Issue by AmarOk1412** [chubin/wttr.in#76]
Hi, 
I try to get the meteo with `curl wttr.in/London` and get `ERROR`.
http://wttr.in/London doesn't work too. (And if I replace London by another city, I've got the same result)

**Comment by eubenesa** [comment]
`wttr.in/Boston` getting `ERROR` as well.

**Comment by chubin** [comment]
Fixed. @AmarOk1412 @eubenesa Thank you for reporting!
