### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by chubin** [chubin/wttr.in#77]
Initial Japanese translation is available at wttr.in (wttr.in/Tokyo?lang=ja), but we need some proofreading to be sure, that the translation is really correct and flawless.

Interface elements (in English):

```
Weather report for:
Morning
Noon
Evening
Night
```
Interface elements (in Japanese):
```
天気予報：
朝
昼
夕
夜
```

Weather conditions descriptions/names (in English):

```
113: Clear
116: Partly cloudy
119: Cloudy  
122: Overcast
143: Mist
176: Patchy rain possible
179: Patchy snow possible 
182: Patchy sleet possible
185: Patchy freezing drizzle possible
200: Thundery outbreaks possible
227: Blowing snow
230: Blizzard
248: Fog
260: Freezing fog
263: Patchy light drizzle
266: Light drizzle   
281: Freezing drizzle
284: Heavy freezing drizzle
293: Patchy light rain
296: Light rain
299: Moderate rain at times
302: Moderate rain
305: Heavy rain at times
308: Heavy rain
311: Light freezing rain
314: Moderate or heavy freezing rain
317: Light sleet
320: Moderate or heavy sleet
323: Patchy light snow
326: Light snow
329: Patchy moderate snow
332: Moderate snow
335: Patchy heavy snow
338: Heavy snow 
350: Ice pellets
353: Light rain shower
356: Moderate or heavy rain shower
359: Torrential rain shower
362: Light sleet showers
365: Moderate or heavy sleet showers
368: Light snow showers
371: Moderate or heavy snow showers
386: Patchy light rain with thunder
389: Moderate or heavy rain with thunder
392: Patchy light snow with thunder
395: Moderate or heavy snow with thunder
```

Weather conditions descriptions/names (in Japanese):
```
(come soon)
```

I thank @ryunix for the help with the translation/proofreading/verification.

**Comment by ryunix** [comment]
I checked interface elements.

正午 are 12 PM just.
I think that 昼 is good.

**Comment by chubin** [comment]
Fixed. Thank you @ryunix!

**Comment by ryunix** [comment]
It is harder than I imagined.
Because it's finer than the classification of the weather in Japan.

Please comment on the current translation content.
I think that it is easier to modify from there.

**Comment by chubin** [comment]
@ryunix We should translate error messages also:

```
ERROR: Unknown location:

We were unable to find your location,
so we have brought you to Oymyakon,
one of the coldest permanently inhabited locales on the planet.
```

They are not translated at all.

**Comment by ryunix** [comment]
I have completed translation of error messages.

```
エラー: 未知の場所です:

指定された場所が見つかりませんでした。
代わりにオイミャコンの天気予報を表示しています。
オイミャコンは地球上で最も寒い居住地の一つです。
```

**Comment by chubin** [comment]
Thank you very much!
What do you think, is it better to write: 
```
ERROR: 未知の場所です:
```
or

```
エラー: 未知の場所です:
```

**Comment by ryunix** [comment]
I think the first one is better.  😄

**Comment by chubin** [comment]
Please try: curl wttr.in/dddXXX123?lang=ja or open the link in browser. That is how it looks like

**Comment by ryunix** [comment]
I checked.  LGTM 👍

**Comment by chubin** [comment]
Some of the weather conditions names translations:

```
113: 快晴
116: 所により曇り
119: 曇り
122: 本曇り
143: もや
176: 近くで所により雨
179: 近くで所により雪
200: 近くで雷の発生
227: 吹雪
230: 猛吹雪
248: 霧
260: 着氷性の霧
263: 所により霧雨
266: 霧雨
293: 所により弱い雨
296: 弱い雨
299: 時々穏やかな雨
302: 穏やかな雨
305: 時々大雨
308: 大雨
317: 軽いみぞれ
320: 穏やかなまたは強いみぞれ
323: 所により小雪
326: 小雪
329: 所により穏やかな雪
332: 穏やかな雪
335: 所により大雪
338: 大雪
353: 軽いにわか雨
356: 穏やかなまたは強いにわか雨
359: 急な豪雨
362: 急な軽いみぞれ
368: 急な軽い雪
371: 穏やかなまたは強い急な雪
386: 所により雷を伴う弱い雨
389: 雷を伴う穏やかなまたは強い雨
```

**Comment by ryunix** [comment]
Sorry for late response.  🙇 

I checked weather conditions descriptions/names.

```
122: 曇り
143: 靄
176: 所により雨
179: 所により雪
182: 所により凍雨
185: 所により着氷性の霧雨
200: 雷雨の発生
263: 所により弱い霧雨
266: 弱い霧雨
281: 着氷性の霧雨
284: 強い着氷性の霧雨
299: 時々雨
302: 雨
305: 時々強い雨
308: 強い雨
311: 弱い着氷性の雨
314: 着氷性の雨または強い着氷性の雨
317: 弱い凍雨
320: 凍雨または強い凍雨
323: 所により弱い雪
326: 弱い雪
329: 所により雪
332: 雪
335: 所により強い雪
338: 強い雪
350: 凍雨
353: 弱い驟雨
356: 驟雨または強い驟雨
359: 激しい驟雨
362: 弱い凍雨
365: 凍雨または強い凍雨
368: 弱い驟雪
371: 驟雪または強い驟雪
389: 雷を伴う雨または強い雨
392: 所により雷を伴う弱い雪
395: 雷を伴う雪または強い雪
```

My translation rules:

```
light: 弱い
moderate: (Omit)
heavy: 強い

rain: 雨
rain shower: 驟雨
snow: 雪
snow shower: 驟雪
sleet: 凍雨
drizzle: 霧雨

freezing: 着氷性
```

**Comment by chubin** [comment]
@ryunix Hi, ryunix! Thank you very much for the translation and excuse me for the late response.
I tried to fix the png rendering of the Japanese translation (see for example: http://wttr.in/Tokio_lang=ja.png ), but didn't manage to fix it. Not yet, though the problem is localized. I hope to get it fixed it soon.

Also, wttr.in supports Japanese for input now. So you can use queries like that now: http://wttr.in/東京
What do you think about the feature?

Thank you very much for your translation once again.
I have several questions about it:
1. If you didn't translate something (116 for example), does it mean, that the original translation is correct?
2. If you translated something, though it was translated already, does it mean that the original translation is not really correct, and it's better to use you translation?

So, if I understand right, I just need to merge these two lists this way:
```
translation = original_trsanslation
translation.update(your_translation)
```
(just override original translations with yours)

Correct?

**Comment by ryunix** [comment]
@chubin Hi, chubin!

I've checked. -> http://wttr.in/Tokio_lang=ja.png
hmm...  My machine are correct output.
I'll upload screenshot.
![2017-03-26 0 00 23](https://cloud.githubusercontent.com/assets/7754313/24323378/d8af357c-11b7-11e7-803a-20c207465cb0.png)

**Comment by chubin** [comment]
No, the problem is not with the curl output (VT100 format) but with the PNG files.
If you download this file: http://wttr.in/Tokio_lang=ja.png (note .png at the end of the URL)
with wget 
```wget http://wttr.in/Tokio_lang=ja.png```
or open it in the browser, you will see it.

**Comment by ryunix** [comment]
Japanese input supports are very cool!  👍 
However, I found a mistake in translation of location information section.

- Case of http://wttr.in/東京?lang=en
  Location: 東京, ...
- Case of http://wttr.in/東京?lang=ja
  未知の場所です: 東京, ...

"未知の場所です" means "Unknown location".  😱 
In this case, I think "位置情報" is good.

**Comment by ryunix** [comment]
Oops, I confirmed png file is wrong.

**Comment by ryunix** [comment]
> 1. If you didn't translate something (116 for example), does it mean, that the original translation is correct?

Yes!
I'm sorry that explanation is not enough.

> 2. If you translated something, though it was translated already, does it mean that the original translation is not really correct, and it's better to use you translation?

There may be some incorrect translations.
However, I used a word close to the weather forecast in Japan.
Also, since the width of the table is limited, I also thought about reducing the number of characters.

**Comment by chubin** [comment]
Thank you very much for the explanation! It was clear enough before, but I asked it still, because I wanted to check it twice. You have invested so much time in it, that it would be really pity if I confused something.

Thank you very much for this translation: 位置情報 Now it is fixed!

And the good news: the png generation is already fixed now!! Try this for example:  http://wttr.in/%E3%83%91%E3%83%AA.png?lang=ja (I've just noted that some characters are missing in the png:  パリ but they are there in the ANSI and HTML outputs). But anyway, the png looks really nice now

**Comment by ryunix** [comment]
I've understand your source code.
Correct!

P.S.  Sorry to separate comments more than once.

**Comment by ryunix** [comment]
You're welcome.  😄 
And sorry for late response.

Wow, its nice!
But, Characters that look like "[]" in the header are strange.
"パリ" are Japanese Katakana.
Do you have any other necessary information?

**Comment by chubin** [comment]
The problem with Kataka is fixed! So, PNG + Japanese is working fully correct now (please recheck).
So the only thing that has to be done now here is to switch to your translations.

**Comment by ryunix** [comment]
I've checked "Katakana" Problem.

However, location information problem seems to have occurred again.
Please check it.

**Comment by chubin** [comment]
Yes, indeed. It was my fault. It is fixed now.
I've added a boilerplate for the Japanese translation in the repository: share/translations/ja.txt
Could you please check in your translation with your credentials and give me a pull request?
(just to have the translations in the code belonging to their original author)

**Comment by ryunix** [comment]
I've checked location information problem.  😄 

Okay, I'll work from now.
Like this?

```
113: 快晴                               : Clear
113: 晴れ                               : Sunny
```

**Comment by chubin** [comment]
Exactly

**Comment by chubin** [comment]
Merged your translations. Thank you very much! Now I need some time to start using them on the server

**Comment by ryunix** [comment]
Thank you too.
I'm looking forward to release.  😸

**Comment by chubin** [comment]
@ryunix 
I've switched Japanese translation on wttr.in on your translation.
You can check how it looks like and check if everything is corrected translation.
Also, I've found one term that was not translated.

I've added it here: https://github.com/chubin/wttr.in/blob/master/share/translations/ja.txt
can you please translate it?

**Comment by ryunix** [comment]
@chubin hi.  Thank you for release. 🎉 

Okay, I'll translate it.
Wait a minute.

**Comment by chubin** [comment]
Hi! Thank you very much for the help. Now we fully support Japanese!
Can you please translate the last thing:
"wttr.in supports wttr.in now! Now you can use your language for input as well as for output. Thanks @ryunix for it"

And we can release it completely and close the issue :)

**Comment by ryunix** [comment]
I'll try it.  😄 
I think that "wttr.in supports wttr.in now!" is probably "wttr.in supports Japanese now!".
Is't correct?

**Comment by chubin** [comment]
Yes of course, that was my fault. You are right, "wttr.in supports Japanese now"

**Comment by ryunix** [comment]
I've completed translation!

"wttr.in は日本語をサポートしています！入力と出力に日本語を使用できるようになりました。ありがとう @ryunix"

**Comment by chubin** [comment]
Done!! Thank you very much!
The issue can be closed now.

If there will be some new messages that we will need to translate to Japanese, I will post them here.
Thank you very much once again. It was really good job!! I hope that it will be useful for wttr.in users in Japan, and they will be really glad to use their own language when accessing wttr.in  ￼:tada:

**Comment by chubin** [comment]
@ryunix hi! I need your help again. We are translating the new view (`curl v2.wttr.in`)
into different languages of the world.
Could you please take a look at it and the Japanese translation?
It is just a single line:

[lib/translations_v2.py](https://github.com/chubin/wttr.in/blob/master/lib/translations_v2.py)

**Comment by ryunix** [comment]
hi, I'll start right away.

**Comment by chubin** [comment]
@ryunix Thank you! Merged
