### ISSUE TITLE
Country missing?

### ISSUE THREAD

**Issue by olegsvs** [chubin/wttr.in#777]
The screenshots from the readme also indicate the country. Is it removed or can it be turned on with options?
E.g.: https://wttr.in/London_0f_transparency=255.png
![image](https://user-images.githubusercontent.com/4546216/185250501-8a2c6de5-5fb5-4fd5-be2a-ab6421d8efdc.png)

**Comment by zachyboy12** [comment]
Hello @olegsvs!

You can set the country by using this (example using London):

 ```
curl wttr.in/london
```

**Comment by jahway603** [comment]
I see the country right after running curl. Are you not seeing this?

```
$ curl https://wttr.in/London
Weather report: London

     \  /       Partly cloudy
   _ /"".-.     62 °F          
     \_(   ).   ↖ 4 mph        
     /(___(__)  6 mi           
                0.0 in    
```

**Comment by olegsvs** [comment]
> 
But the country is not in the output(screenshot from readme)
![image](https://user-images.githubusercontent.com/4546216/196007324-62f4b803-4b5b-4681-adde-e1d9f850810f.png)

**Comment by chubin** [comment]
This is not a bug, this is intentionally.

1. If you don't specify any location, it detects your location and shows it in the forma `City, Country`
2. If you specify a location, it shows in the same form as it was specified

```
~$ curl wttr.in/London,%20UK?0
Weather report: London, UK

     \  /       Partly cloudy
   _ /"".-.     18 °C
     \_(   ).   ↑ 19 km/h
     /(___(__)  10 km
                0.0 mm
~$ curl wttr.in/London?0
Weather report: London

     \  /       Partly cloudy
   _ /"".-.     18 °C
     \_(   ).   ↑ 19 km/h
     /(___(__)  10 km
                0.0 mm
```

Try this one:

https://wttr.in/London,%20UK_0f_transparency=255.png
