### ISSUE TITLE
Windspeed in m/s for some locales

### ISSUE THREAD

**Issue by chubin** [chubin/wttr.in#78]
From an email of one wttr.in users:

> Hello Igor!
> 
> I’ve noticed something that should be changed in the Swedish translation.
> When we talk about wind speeds in Sweden we use m/s, not km/h.

**Comment by davewhipp** [comment]
Hi @chubin . I saw that windspeed in m/s is now [supported in wego](https://github.com/schachmat/wego/commit/59e0142a998397fa2a69e45b3d950da5c1d1246b), so perhaps we can ask that you add a flag to support this for wttr.in? Like Sweden, windspeeds in Finland are given in m/s.

**Comment by chubin** [comment]
The problem is that wego that is used at wttr.in and the mainstream wego are diverged, and that flag was not yet supported in our wttr.in installation. But it is a really small thing to fix, so we will implement it soon.

**Comment by davewhipp** [comment]
Sounds good. I mostly wanted to let you know because I had asked about adding that feature to wego and they just merged it in yesterday. Thanks!

**Comment by chubin** [comment]
Windspeed in m/s is supported not. Use ?M for it
