### ISSUE TITLE
wttr.in certificate expired!

### ISSUE THREAD

**Issue by vitich** [chubin/wttr.in#782]
notBefore=Jun 11 11:43:20 2022 GMT
notAfter=Sep  9 11:43:19 2022 GMT
![Знімок екрану_2022-09-09_15-07-41](https://user-images.githubusercontent.com/12166319/189347110-f9ac8612-5f13-4ecd-945a-6d14a9b73ae6.png)

**Comment by vitich** [comment]
Try acme.sh

**Comment by nickforddev** [comment]
https://certbot.eff.org/ is quite nice for auto-renewing letsencrypt certs
