### ISSUE TITLE
nginx version running wttr.in is SUPER old from 2017

### ISSUE THREAD

**Issue by jahway603** [chubin/wttr.in#790]
nginx version running wttr.in is SUPER old from 2017
- wttr.in is running [nginx 1.10.3, released Jan 31, 2017](https://github.com/nginx/nginx/releases/tag/release-1.10.3)
- latest nginx is [version 1.23.1, released Jul 19, 2022](https://github.com/nginx/nginx/releases/tag/release-1.23.1)

Discovered when running the following:
```
$ curl -I wttr.in/London
HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Thu, 13 Oct 2022 18:37:26 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 8673
Connection: keep-alive
Access-Control-Allow-Origin: *
```

Unsure where or who this needs to be reported to, but this is a security issue.

**Comment by chubin** [comment]
Accepted. Will be fixed.

**Comment by jahway603** [comment]
@chubin checking back on this issue & now you've hidden the version of nginx being used. Was this security issue addressed or not?

```
$ curl -I wttr.in/London
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Length: 8626
Content-Type: text/plain; charset=utf-8
Date: Thu, 08 Dec 2022 17:40:51 GMT
```

**Comment by chubin** [comment]
Now it is not nginx at all. Now, it is the wttr.in server itself which accepts the incoming HTTP/HTTPS queries. The code is not yet in master:

https://github.com/chubin/wttr.in/blob/chubin/logging/srv.go#L72

**Comment by jahway603** [comment]
That's a great feature! :+1:  Closing this issue as nginx is not used anymore, so no more security concern then.
