### ISSUE TITLE
Empty User Agent string causes 500 error

### ISSUE THREAD

**Issue by ikben** [chubin/wttr.in#8]
I was playing around with curl before looking at the source code and this generates a 500 error: `curl 'http://wttr.in/' -H 'User-Agent: '`.

You may want to add an extra check or try block around https://github.com/chubin/wttr.in/blob/master/bin/srv.py#L225

**Comment by chubin** [comment]
Ok, if user agent is emty, it returns html output now (or do you think, that it would be better to return a console output in this case?). (it is only on wttr.in now, not yet commited)

**Comment by ikben** [comment]
Great! I don't think the beaviour really matters. An empty header is probably someone like me who's just fooling around with inputs.

**Comment by chubin** [comment]
It works now. I close the issue, though the actual code was not committed on github (not yet) (see #71).
