### ISSUE TITLE
Portuguese Translation

### ISSUE THREAD

**Issue by garaujo** [chubin/wttr.in#80]
Hi.
Please correct this Portuguese translation:

Morning = Manhã (not Amanhã that means Tomorrow)

Thanks for this great service.

**Comment by chubin** [comment]
Fixed. Thank you very much for the reporting

**Comment by chubin** [comment]
@garaujo 

Gonçalo hi! We are translating the new view (`curl v2.wttr.in`).
Could you please take a look at it and the Portuguese translation?
It is just a single line:

[lib/translations_v2.py](https://github.com/chubin/wttr.in/blob/master/lib/translations_v2.py)

**Comment by garaujo** [comment]
Hi Igor.
The new version looks very nice!

Here goes my Portuguese translation proposal.

"pt": ("Previsão do tempo para:", "Tempo", "Fuso horário", "Agora", "Alvorada", "Nascer do sol", "Zénite", "Pôr do sol", "Crepúsculo"),

Good job!

Gonçalo Araújo

**Comment by chubin** [comment]
@garaujo Thank you, Gonçalo! I used your translation for `pt-br` too; I am not sure that it was right, but I hope yes
