### ISSUE TITLE
wttr.in is currently down

### ISSUE THREAD

**Issue by obehrens** [chubin/wttr.in#811]
Hello, the website wttr.in is currently down.

Error: 502 Bad Gateway

![Screenshot_20221116_135223](https://user-images.githubusercontent.com/118389417/202268107-709ef3f0-ca3b-42e9-955e-e48aa047b2ca.png)

**Comment by michalspano** [comment]
+1

**Comment by obehrens** [comment]
Back up for me

**Comment by michalspano** [comment]
Appears to be fixed now. Cool!
