### ISSUE TITLE
wttr.in seems to be down

### ISSUE THREAD

**Issue by acagastya** [chubin/wttr.in#814]
Hi, I tried `curl wttr.in` today at 05:49:20 UTC, and I got a `curl: (52) Empty reply from server` response.  Can you please check why the server is down?

**Comment by chubin** [comment]
Now it works again. Please check

**Comment by digitaltrails** [comment]
Down at the moment.

**Comment by chubin** [comment]
@digitaltrail sHow exactly do you check it? What query do you use? I can't reproduce it, it works for me

**Comment by obehrens** [comment]
Here is the error I'm getting:
![Screenshot_20221121_102638](https://user-images.githubusercontent.com/118389417/203096492-9d81db0a-54fd-40b7-b027-263efbd6c12c.png)

**Comment by obehrens** [comment]
Well, it seems to be back up for now.


I'm not sure why, but the site has been going down pretty often for various reasons. Here is my uptime kuma log:

![Screenshot 2022-11-21 at 10-47-25 Uptime Kuma](https://user-images.githubusercontent.com/118389417/203098357-ef174f01-feef-4e14-be72-ca71cd75ec7c.png)
