### ISSUE TITLE
Suddendly got  Unknown location

### ISSUE THREAD

**Issue by UmbraDB** [chubin/wttr.in#825]
Hello!

First of all I would like to thank you for providing wttr.in it's really useful, I love it's concept and I've been using it in my conky.

I guess this problem is not from wttr.in itself but maybe from a service provider, sorry I'm not deep into wttr.in code or how it works, but I'm getting a good output for my capital city, or even going directly to https://wttr.in/odivelas? it works, just not for my actual location, this provided that just some hours ago i was getting a good and precise forecast, but since some hours ago I'm getting the  bellow output (I just posted the top part, i guess the output is not relevant as this looks like a default value to Oymyakon). I'm just dropping this here in case there is a wttr.in that you might want to look in.

I'm not using any VPN or any kind of spoofing when testing wttr.in,  I am however denying all incoming connections via firewall but it wasn't a problem before.

This is an approximated location 38.8046961,-9.1940222.

head output of https://wttr.in/?&lang=en    :
```
>>>    _  _    ___  _  _        
>>>   | || |  / _ \| || |         
>>>   | || |_| | | | || |_         
>>>   |__   _| |_| |__   _|         
>>>      |_|  \___/   |_|       
>>>                          
>>>   404 UNKNOWN LOCATION: Odivelas, PT   
>>>                    
----
Weather report: Oymyakon
```

hope to have helped in some way if it is a wttr.in problem.

**Comment by ameintjes** [comment]
Also getting this, for Cape Town, South Africa

"404 UNKNOWN LOCATION: Cape Town, ZA"

**Comment by Soundtoxin** [comment]
Getting this for "MSP" (airport code) as of recently.

**Comment by ameintjes** [comment]
Seems to be working again

**Comment by bsstephan** [comment]
I've been seeing sporatic issues for a couple days as well. For example, a user of my IRC bot queried for 'http://wttr.in/ytz?format=j1' and the bot reported a 404, and then a moment later I did that exact same request in a curl and got results. Is there some kind of user agent filtering or something going on?

**Comment by josephwb** [comment]
My location in North Bay Ontario Canada is also not working. I have used the command `curl -4 wttr.in/North_Bay` for years. Replacing the underscore with `+` does not fix things. Specifying GPS coordinates (46.32,-79.47) also fails.

**Comment by chubin** [comment]
Thanks for your reports. Yes, there were some problems with geolocation (and locations resolution) in the last time. I've fixed them now (the fixes are not yet in master).

I've checked your locations, and it seems to work now:

```
$ curl -s http://wttr.in/ytz | grep Location:
Location: Billy Bishop Toronto City Airport, 1 Lakeshore Avenue, Old Toronto, ON M5V 1A1, Canada [43.628057,-79.3979912]
$ curl -s http://wttr.in/Cape+Town,+South+Africa | grep Location:
Location: Cape Town, City of Cape Town, Western Cape, South Africa [-33.928992,18.417396]
$ curl -s http://wttr.in/MSP | grep Location:
Location: Minneapolis-Saint Paul International Airport, 4300, Glumack Drive, Minneapolis, Hennepin County, Minnesota, 55450, USA [44.878019050000006,-93.2209280537696]
$ curl -s http://wttr.in/odivelas | grep Location:
Location: Odivelas, ODV, Lisboa, Grande Lisboa, Área Metropolitana de Lisboa, Portugal [38.7926342,-9.1826701]
$ curl -s http://wttr.in/38.8046961,-9.1940222 | grep Location:
Location: Externato Pica Pau, Rua do Poder Local, 2620-196 Ramada, Portugal [38.8042721,-9.1934588]
```

Please test.

**Comment by Soundtoxin** [comment]
Weather working again as expected for MSP location. Thank you.

**Comment by josephwb** [comment]
Working for me as well for both name and GPS :)

**Comment by chubin** [comment]
Super. Then we have fixed it :+1:

**Comment by UmbraDB** [comment]
Sry for The delay but also everything is working fine here now!
