### ISSUE TITLE
Weather in Lithuania

### ISSUE THREAD

**Issue by TruncatedDinosour** [chubin/wttr.in#828]
Hello ppl

for the past like 3 (?) days i have not been able to check my weather
using wttr.in and its kinda sad

i live in lithuania and it gives me this error:

```md
>>>    _  _    ___  _  _
>>>   | || |  / _ \| || |
>>>   | || |_| | | | || |_
>>>   |__   _| |_| |__   _|
>>>      |_|  \___/   |_|
>>>
>>>   404 UNKNOWN LOCATION: Šilutė, Lithuania
>>>
----

...

 We were unable to find your location
 so we have brought you to Oymyakon,
 one of the coldest permanently inhabited locales on the planet.

Follow @igor_chubin for wttr.in updates
```

am i just stupid or did it get removed, any alternatives or ways to get it back ?

**Comment by chubin** [comment]
No, you are doing everything right. It is the same problem as here:  #825.

For some time (hopefully, today is the last day) location resolution will be unstable, but after the transition to the new code is complete, it will work even better as before.

**Comment by TruncatedDinosour** [comment]
> No, you are doing everything right. It is the same problem as here: #825.
> 
> For some time (hopefully, today is the last day) location resolution will be unstable, but after the transition to the new code is complete, it will work even better as before.

Thank you, closing this because #825 already exists :+1:

**Comment by TruncatedDinosour** [comment]
reopening because #825 was closed

**Comment by chubin** [comment]
Please try again. Is it now better, or now changes?

**Comment by TruncatedDinosour** [comment]
> Please try again. Is it now better, or now changes?

I think yeah

```md
   _`/"".-.     Patchy rain possible
    ,\_(   ).   +5(1) °C
     /(___(__)  → 25 km/h
       ‘ ‘ ‘ ‘  10 km
      ‘ ‘ ‘ ‘   0.1 mm
```

although what is that 10km, it's showing 10km in all fields, also the wind, it seems too agressive to be true, rn the wind is 2 m/s which is 7.2 km/h

**Comment by TruncatedDinosour** [comment]
but the location issue is resolved, it works for me, just the wind data is very very weird and not sure what that 10 km is which is appearing in every entry, but anyway, i think this is a seperate issue, thanks
