### ISSUE TITLE
wttr.in is down

### ISSUE THREAD

**Issue by leonardodipace** [chubin/wttr.in#856]
The service seems to be down: here's what I get when trying to access the website:

![image](https://user-images.githubusercontent.com/63299726/225048605-70d50092-10ed-4279-87c9-886de27515d8.png)

Also, `curl wttr.in` gives back `curl: (52) Empty reply from server`.

**Comment by jacklolidk** [comment]
+1,
my weather display isn't showing anything now :(

**Comment by Al-Sharabi** [comment]
Omg I thought something was wrong from my end until I figured that the website is down.

**Comment by gonzarizzo** [comment]
+1

**Comment by jerichosy** [comment]
Looks like it's been down for [2 days](https://www.isitdownrightnow.com/wttr.in.html).

**Comment by Al-Sharabi** [comment]
> Looks like it's been down for [2 days](https://www.isitdownrightnow.com/wttr.in.html), giving ERR_HTTP2_PROTOCOL_ERROR.

It was working for me yesterday.

**Comment by saltasatelites** [comment]
> > Looks like it's been down for [2 days](https://www.isitdownrightnow.com/wttr.in.html), giving ERR_HTTP2_PROTOCOL_ERROR.
> 
> It was working for me yesterday.

And this morning too.

**Comment by chubin** [comment]
And now?

**Comment by marslo** [comment]
down again

**Comment by astrorya** [comment]
Does the site just periodically go down temporarily? I've noticed it seems to go down for like a day once a week or something.

**Comment by gonzarizzo** [comment]
Yes, as far as I have seen, it periodically goes down for one or few days.

**Comment by nekiwo** [comment]
anyone running a public mirror perchance?

**Comment by EarOfWheat** [comment]
I just learned about this fun project, and encountered the same issue while trying various parameters. It seems the server has been unstable all along. 😂
