### ISSUE TITLE
wttr.in seems to be down 

### ISSUE THREAD

**Issue by cstamou** [chubin/wttr.in#871]
The service seems to be down ( curl wttr.in/London  for example times out ).  
no access through browser either.

![wttr_in](https://user-images.githubusercontent.com/66228697/235345538-b808b3eb-435b-4f0a-898f-acf01a1e6a29.png)

Thanx for your effords m8.

**Comment by burakai** [comment]
Same for me :(

**Comment by yamzee** [comment]
+1. My waybar wttr module has been blank for some hours now.

**Comment by jsvan** [comment]
+1

I just learned about wttr.in and it's the first time I'm trying to use it, so I'm happy the issue isn't something on my end :sweat_smile: but I hope the issue is resolved because it looks awesome!

**Comment by jsvan** [comment]
It's back up for me.

**Comment by jsvan** [comment]
It's back up for me.

**Comment by cstamou** [comment]
The service seems to be back up.

Thnx again.
