### ISSUE TITLE
Site down, again

### ISSUE THREAD

**Issue by bluecon** [chubin/wttr.in#903]
Service not available
curl wttr.in/Nuremberg?format=3
curl: (52) Empty reply from server

Could you please check. Thanks in advance.

**Comment by sikhdev** [comment]
I would recommend you visit the URL in a web browser to see what the reason is before opening an issue. The reason I say that is because going to the URL will show you the exact reason they are offline. Usually when you are getting this message its because they are out of capacity and just need to wait for the next day for the limit to reset.

Right now on the page I am seeing

```
Sorry, we processed more than 1M requests today and we ran out of our datasource capacity.
We hope to solve the problem as soon as possible, so you can enjoy
your favourite weather service 24x365 even if it rains or snows.
```

**Comment by EternityForest** [comment]
Could you add a donation link? This project seems to be extremely popular, I don't see why you couldn't get enough for a higher tier backend

**Comment by Kyngo** [comment]
Yeah, the website's _still_ totally down, with no kind of error whatsoever right now.

**Comment by Kyngo** [comment]
> I would recommend you visit the URL in a web browser to see what the reason is before opening an issue. The reason I say that is because going to the URL will show you the exact reason they are offline. Usually when you are getting this message its because they are out of capacity and just need to wait for the next day for the limit to reset.
> 
> Right now on the page I am seeing
> 
> ```
> Sorry, we processed more than 1M requests today and we ran out of our datasource capacity.
> We hope to solve the problem as soon as possible, so you can enjoy
> your favourite weather service 24x365 even if it rains or snows.
> ```

as specified by OP, the response he got is that `curl` rejected the connection. This is happening now as well if you enter a destination that has not been visited before. It seems that the application caches popular places to prevent slowdowns, but new places seem to take way longer than expected and thus the application crashes.

And, yes, a donation link like @EternityForest mentioned would be actually a nice way to help this project.

**Comment by vRobM** [comment]
Did anyone try self hosting this?

Or deploying your own instance on fly.io?

**Comment by EternityForest** [comment]
I wonder if it wouldn't make sense long term to move to a local client.

If the user's machine directly queried the NOAA API that doesn't need a key, only using the wttr.in servers as a fallback, you could probably remove the load from a lot of frequent users.

It's still really cool to have things accessible via curl, but people who use it often might like to switch to a proper client app that can use multiple backends.
