### ISSUE TITLE
Site Down?

### ISSUE THREAD

**Issue by dward2002** [chubin/wttr.in#916]
Is Anyone else having issues accessing the data is the site down?

**Comment by dward2002** [comment]
@chubin

**Comment by pmacedov** [comment]
Seems the site is having funding problems to expand capacity resulting in overload. I have to contact noaa direct for critical weather info. Hope it soon to be resolved because the easy way to check weather and integrate via command line with my necessities.

**Comment by chubin** [comment]
I am sorry for the instability that the service is experiencing in the last time. The load has substantially grown, and to handle it properly, several things must be fixed. I hope that I will find for it soon, but not earlier than 23-24 September. I am sorry for the inconvenience once again.

**Comment by vRobM** [comment]
Did anyone try self hosting this?

Or deploying your own instance on fly.io?

**Comment by brettf** [comment]
@chubin let us know if there's any code work to help out upon. Those of us showing up at Github to find out if the capabilities are working are also those who can (likely) help if you need it.

**Comment by chubin** [comment]
The problem has been resolved. The service is now available and responsive.
If you continue to experience any issues with the service, please inform me.

However, please note that there is one feature that is currently disabled and will require additional time to fix: PNG rendering. I will attempt to resolve this as quickly as possible. If you are utilizing this feature, I apologize for any inconvenience and follow #919 for updates.

**Comment by chubin** [comment]
No complains so far, I close the issue. If everything comes up, please reopen.
