### ISSUE TITLE
Curl wttr.in not working

### ISSUE THREAD

**Issue by jvybihal** [chubin/wttr.in#918]
This is what I see:

C:\Users>curl -v wttr.in
*   Trying 5.9.243.187:80...
* Connected to wttr.in (5.9.243.187) port 80 (#0)
> GET / HTTP/1.1
> Host: wttr.in
> User-Agent: curl/8.0.1
> Accept: */*
>
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server

**Comment by marcelarie** [comment]
It is working again.

```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Length: 8667
Content-Type: text/plain; charset=utf-8
Date: Tue, 19 Sep 2023 16:00:44 GMT
```

**Comment by marcelarie** [comment]
Not for Barcelona:

```console
$ curl 'wttr.in/Barcelona?format=3' -v
*   Trying 5.9.243.187:80...
* Connected to wttr.in (5.9.243.187) port 80 (#0)
> GET /Barcelona?format=3 HTTP/1.1
> Host: wttr.in
> User-Agent: curl/7.88.1
> Accept: */*
>
```

**Comment by chubin** [comment]
I am sorry for the instability that the service is experiencing in the last time. The load has substantially grown, and to handle it properly, several things must be fixed. I hope that I will find for it soon, but not earlier than 23-24 September. I am sorry for the inconvenience once again.

**Comment by vRobM** [comment]
This is self hostable right? So where is the list of all the self-hosted installs which would be good alternatives?

@chubin since you need resources globally, why not look into deploying on fly.io so you get distributed network and db benefits? Free to use for small projects and they may wish to sponsor you..

**Comment by chubin** [comment]
We have no problem with hosting, we don‘t consider changing our hosting provider, but if we would, fly.io would be not the best choice, because it has quite modest amount of traffic included, and the additional traffic is quite pricy

**Comment by vRobM** [comment]
Is there some level of caching happening currently? 

Traffic at different edges of the network make a big difference to how the source API usage is with and without edge or even memory caching.

In that respect most of the traffic can be made no-cost if it's mostly from CDN providers amplifying the core services.

**Comment by ophello** [comment]
https://open-meteo.com/ has recently been made which might be a useful API for this application.

**Comment by chubin** [comment]
The problem has been resolved. The service is now available and responsive.
If you continue to experience any issues with the service, please inform me.

However, please note that there is one feature that is currently disabled and will require additional time to fix: PNG rendering. I will attempt to resolve this as quickly as possible. If you are utilizing this feature, I apologize for any inconvenience and follow #919 for updates.

**Comment by ophello** [comment]
@chubin What API are you using to derive location based on IP?

**Comment by chubin** [comment]
The following services (in this order):

* geoip,
* ip2location,
* ipinfo.

**Comment by chubin** [comment]
No complaints so far, I close the issue. If everything comes up, please reopen.

**Comment by bakunjin** [comment]
Hello, I don't want to open new topic, I will ask here, 
shortly, I get result in terminal, I get weather when I type in terminal **curl wttr.in/Belgrade?2** but when I add code in .zshrc file I get failure result: it is written  **Weather unavailable now!!!** 

I use Kali linux and I wanted to make my terminal more beautiful, I edited .zshrc file and added code for weather:
```
curl wttr.in/Belgrade?2 --silent --max-time 3 > /tmp/now-weather
export readarray aWeather < /tmp/now-weather
rm -f /tmp/now-weather
if [[ "${aWeather[0]}" == "Weather report:"* ]] ; then
    WeatherSuccess=true
    echo "${aWeather[@]}"
else
    WeatherSuccess=false
fi
```

after that I must reload .zshrc file: **source /home/kali/.zshrc** 
then I start my terminal and as I told you, it is written: **Weather unavailable now!!!** 
but when I try curl command, I get weather result.
Im made screenshot, you can see it.

![curl-problem](https://github.com/user-attachments/assets/74da3669-557a-40f0-82eb-28ef34d025a6)
