### ISSUE TITLE
German Translation "Morning"

### ISSUE THREAD

**Issue by felix-d1strict** [chubin/wttr.in#920]
Hello,

in the German translation "Früh" is given as morning.
Technically this is correct, however I would say that in German speaking regions people tend to say "Morgen" in the weather report instead of "Früh".

https://github.com/chubin/wttr.in/blob/6b050470bcee33d265439b4e6df20e043cc621ad/share/we-lang/locale.go#L164

**Comment by chubin** [comment]
@felix-d1strict Ganz genau. Danke für die Hilfe, Felix!
