### ISSUE TITLE
Site Offline

### ISSUE THREAD

**Issue by arham-sayyed** [chubin/wttr.in#946]
the [official site](https://wttr.in) is offline
![image](https://github.com/chubin/wttr.in/assets/113809839/bbc9ec49-a8c2-4615-b89b-9552cb12f062)

**Comment by KenwoodFox** [comment]
Is this just dns or is it actually offline? i cant access it either :C

**Comment by RossoCorsa** [comment]
Can't `curl` also

`curl: (56) Recv failure: Connection reset by peer`

**Comment by jrdwiz** [comment]
The site is down and the dockerfile is broken.

**Comment by bosconb** [comment]
same issue

**Comment by chubin** [comment]
Fixed
