### ISSUE TITLE
Site not working 

### ISSUE THREAD

**Issue by dianaw353** [chubin/wttr.in#947]
I only see a white screen when trying to view wttr

**Comment by RossoCorsa** [comment]
`curl`  doesn't work too.

```
> GET /San+Francisco HTTP/1.1
> Host: v2.wttr.in
> User-Agent: curl/8.1.2
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Thu, 28 Dec 2023 18:20:31 GMT
< Content-Length: 0
<
* Connection #0 to host v2.wttr.in left intact
```

**Comment by AzlanCoding** [comment]
It was working just fine yesterday but today it's not working.

**Comment by AlejandroRZ** [comment]
curl wttr.in is also not working, it just doesn't do nothing when i type it in the terminal

**Comment by boredland** [comment]
I think it is back up again!

**Comment by dianaw353** [comment]
Now it seems the queries to the weather servies is out of compacity...

**Comment by dianaw353** [comment]
down again

**Comment by AzlanCoding** [comment]
Back online again
