### ISSUE TITLE
Some option cannot support Japanese

### ISSUE THREAD

**Issue by tani-page** [chubin/wttr.in#95]
Without tpq option, it works with Japanese.
http://wttr.in/Tokyo?lang=ja : OK
http://wttr.in/Tokyo_lang=ja.png : OK

With tpq option, it doesn't work with Japanese, while it works with English.
http://wttr.in/Tokyo?0tpq&lang=ja : ERROR
http://wttr.in/Tokyo?0tpq&lang=en : OK
http://wttr.in/Tokyo_0tpq_lang=ja.png : ERROR
http://wttr.in/Tokyo_0tpq_lang=en.png : OK

**Comment by chubin** [comment]
Thank you for reporting!

**Comment by tani-page** [comment]
It works with Japanese now. Thank you.
