### ISSUE TITLE
curl: (28) Failed to connect to wttr.in port 80 after 134285 ms: Couldn't connect to server

### ISSUE THREAD

**Issue by wewlad-dev** [chubin/wttr.in#950]
curl works fine, not a curl issue
and if I change the IP, it also works fine, my only suspect is that wttr.in has some sort of limiter on the query and blocks you if you exceed it, so what's the daily limit?
As I have a widget that automatically curl every X period of time, I can adjust that to the max limit per day.

also the verbose output 
`$ curl -v wttr.in/?q       `   
`* Host wttr.in:80 was resolved.`
`* IPv6: (none)`
`* IPv4: 5.9.243.187`
`*   Trying 5.9.243.187:80...`
`* connect to 5.9.243.187 port 80 from ... port 50692 failed: Connection timed out`
`* Failed to connect to wttr.in port 80 after 136005 ms: Couldn't connect to server`
`* Closing connection`
`curl: (28) Failed to connect to wttr.in port 80 after 136005 ms: Couldn't connect to server`

**Comment by chubin** [comment]
> and if I change the IP, it also works fine, my only suspect is that wttr.in has some sort of limiter on the query and blocks you if you exceed it, so what's the daily limit?

Yes, you are right. wttr.in has automatic filters which block too active clients.
Activity threshold is dynamic and depends on the current load, but it is typically in the range of several queries per second.

Amnesty happens on a daily basis, i.e. if your script was too aggressive with querying the service, you can either ping me (igor@chub.in) and let me know the IP address, or just wait until the end of the day.
