### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by mosaicthej** [chubin/wttr.in#961]
```bash
curl wttr.in
curl: (7) Failed to connect to wttr.in port 80 after 134 ms: Couldn't connect to server 

curl https://wttr.in
curl: (7) Failed to connect to wttr.in port 443 after 144 ms: Couldn't connect to server
```

**Comment by babymu5k** [comment]
yep getting same problems
```
curl: (7) Failed to connect to wttr.in port 80 after 65 ms: Couldn't connect to server
```
![image](https://github.com/chubin/wttr.in/assets/95881676/758db45f-7e17-408b-87dd-9e2c068f4689)

**Comment by French77** [comment]
There is nothing you can do except waiting. Probably the server is overloaded, down or unreachable because of a network problem, outage or a website maintenance is in progress...
![Server Status Check](https://github.com/chubin/wttr.in/assets/3099270/58cc38b0-e95f-4e15-ba02-61425bea5d60)

**Comment by chubin** [comment]
Please check again. It should be back online

**Comment by babymu5k** [comment]
yep its online again

**Comment by rkaletka** [comment]
looks like it is down again, which solution you're using as a server?

**Comment by duffxp** [comment]
This remains down:
```
$ curl wttr.in
curl: (52) Empty reply from server
```

```
$ curl https://wttr.in
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
```

**Comment by chubin** [comment]
Fixed
