### ISSUE TITLE
Can't go to wttr.in anymore

### ISSUE THREAD

**Issue by burnsboyamazing** [chubin/wttr.in#965]
Can't go to wttr.in anymore, it shows "ERR_HTTP2_PROTOCOL_ERROR" in Chrome.
![Screenshot 2024-02-08 3 28 23 PM](https://github.com/chubin/wttr.in/assets/154830140/577f1d28-d1d2-4c8e-bae9-5dbf33c95297)

**Comment by mkadrlik** [comment]
Down for me as well.

**Comment by MiguelCarino** [comment]
Still down for me.

**Comment by chubin** [comment]
Fixed

**Comment by mkadrlik** [comment]
ty sir

**Comment by burnsboyamazing** [comment]
No problem!

**Comment by burnsboyamazing** [comment]
Going to wttr.in is up. But, the issue's still closed as fixed.
![Screenshot 2024-02-09 9 48 40 PM](https://github.com/chubin/wttr.in/assets/154830140/981d8ca9-be56-4e2a-9fdf-008fa6ce2cfa)

**Comment by burnsboyamazing** [comment]
![Screenshot 2024-02-09 9 50 04 PM](https://github.com/chubin/wttr.in/assets/154830140/b2d41595-edc6-46b7-88a3-7474b306c643)
wttr.in/doha is working but not down.
