### ISSUE TITLE
wttr.in down

### ISSUE THREAD

**Issue by helloworlddan** [chubin/wttr.in#980]
Hi @chubin 

It seems the service is down. Can you check? Am currently unable to simply curl wttr.in

**Comment by josharghhh** [comment]
yep defs appears to be down. am trying to implement it into a cron script for an assignment at the moment but can't test :( hopefully devs get back up soon.

**Comment by chubin** [comment]
Still down? Please check again

**Comment by helloworlddan** [comment]
Nope, it's responding again. Thanks @chubin for the service you provide <3

**Comment by sigaloid** [comment]
Still intermittent issues here.. :(

**Comment by chubin** [comment]
@sigaloid It should work. Does it hang or returns an error for you?

**Comment by sigaloid** [comment]
It works now, it was hanging for 5+ seconds so it was time-ing out but seems to be all good now :)
