### ISSUE TITLE
timeouts ?

### ISSUE THREAD

**Issue by cmeesters** [chubin/wttr.in#984]
For a while, wttr.in did not seem to be working:

```bash
$ curl wttr.in/<city>
curl: (28) Failed to connect to wttr.in port 80 after 130698 ms: Couldn't connect to server
```

However, `traceroute` reliable traces to `static.187.243.9.5.clients.your-server.de` via `b6.xgu.ru` (which is also a weird address). 

Could you comment on these aspects? Thank you.

**Comment by chubin** [comment]
Works again
