### ISSUE TITLE
How to display celsius temperature in one-line output

### ISSUE THREAD

**Issue by DyiShiou** [chubin/wttr.in#987]
When I execute the following one-line output command

```bash
curl -s 'zh.wttr.in/{Beijing,Chifeng}?format=4'
```

It will display results with Fahrenheit temperature, but I wanna see celsius one, any option to fix this problem?

By the way, If I close my proxy, the command will display celsius temperature as expected.

Thanks

**Comment by vitusson** [comment]
It depends on from where the query is originated, it will display Fahrenheit if your proxy is in USA 
https://github.com/chubin/wttr.in?tab=readme-ov-file#weather-units
Use
`curl -s 'zh.wttr.in/{Beijing,Chifeng}?m&format=4'` to get metric units
