### ISSUE TITLE
https://wttr.in down?

### ISSUE THREAD

**Issue by h4rldev** [chubin/wttr.in#996]
I get SSL connection issues when I try to curl or visit the website.

**Comment by Thiago-Assis-T** [comment]
I can ping it, but can't seem to curl or open it in browser

**Comment by mechatour** [comment]
Confirmed here in UK also

**Comment by dibusure** [comment]
I think, yes

**Comment by BedBug2479** [comment]
Same timeout using curl/ps

**Comment by chubin** [comment]
We are currently experiencing a high volume of traffic, which may cause the service to be unavailable or work unreliably for a period of time. Please ensure that your scripts are configured correctly and that you are not sending an excessive number of queries (*excessive* means here many thousands query per minute, not 5 queries per minute) from the same IP address, as this may result in being automatically blocked by the system meant to manage heavy loads. Thank you for understanding.

**Comment by chubin** [comment]
Fixed
