### ISSUE TITLE
Looks like wttr.in is down

### ISSUE THREAD

**Issue by kumaranvpl** [chubin/wttr.in#999]
I believe wttr.in is down. https://wttr.in/ link is not working anymore and shows the following error
![image](https://github.com/chubin/wttr.in/assets/7011056/5e3e30b6-53e4-4c9f-868c-2bc8579d8707)

**Comment by mpmc** [comment]
OK here? And https://www.isitdownrightnow.com/wttr.in.html

**Comment by kumaranvpl** [comment]
It is working now. Closing the issue.
